"""Generator for notebook 17: RLHF"""
import nbformat

def md(text):
    return nbformat.v4.new_markdown_cell(text)

def code(text):
    return nbformat.v4.new_code_cell(text)

nb = nbformat.v4.new_notebook()

c1 = md(
    "# 17 - Reinforcement Learning from Human Feedback (RLHF)\n\n"
    "## Learning Objectives\n"
    "1. Understand the three-stage RLHF pipeline: SFT -> Reward Model -> PPO\n"
    "2. Implement Bradley-Terry preference model and train on pairwise comparisons\n"
    "3. Build a toy RLHF loop with reward hacking demonstration\n"
    "4. Compare RLHF (PPO) vs DPO vs SFT-only on quality vs compute tradeoff\n"
)

c2 = code(
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from sklearn.neural_network import MLPRegressor, MLPClassifier\n"
    "from sklearn.linear_model import LogisticRegression\n"
    "from sklearn.metrics import brier_score_loss\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "np.random.seed(42)\n"
    "print('Packages loaded: numpy', np.__version__)\n"
    "print('RLHF demo: Bradley-Terry model + toy PPO on synthetic preferences')\n"
)

c3 = md(
    "## Level 1: Bradley-Terry Preference Model\n\n"
    "The Bradley-Terry model estimates item quality scores from pairwise comparisons.\n"
    "P(item_i beats item_j) = sigmoid(score_i - score_j)\n"
    "Loss = -E[log sigmoid(score_winner - score_loser)]\n"
    "This is exactly the RLHF reward model objective.\n"
)

c4 = code(
    "# Bradley-Terry preference model\n"
    "def sigmoid(x):\n"
    "    return 1.0 / (1.0 + np.exp(-np.clip(x, -20, 20)))\n"
    "\n"
    "\n"
    "def generate_preference_data(true_scores, n_comparisons=500, noise=0.1):\n"
    "    # Generate pairwise comparisons from true underlying quality scores\n"
    "    n_items = len(true_scores)\n"
    "    pairs = []\n"
    "    labels = []\n"
    "    for _ in range(n_comparisons):\n"
    "        i, j = np.random.choice(n_items, size=2, replace=False)\n"
    "        # True win probability with noise\n"
    "        p_win = sigmoid(true_scores[i] - true_scores[j])\n"
    "        winner = i if np.random.random() < p_win else j\n"
    "        loser = j if winner == i else i\n"
    "        pairs.append((winner, loser))\n"
    "        labels.append(1)  # winner always listed first\n"
    "    return pairs\n"
    "\n"
    "\n"
    "def train_bradley_terry(n_items, pairs, n_epochs=200, lr=0.05):\n"
    "    # Learn quality scores theta via gradient ascent on log-likelihood\n"
    "    theta = np.zeros(n_items)\n"
    "    loss_history = []\n"
    "\n"
    "    for epoch in range(n_epochs):\n"
    "        grad = np.zeros(n_items)\n"
    "        total_loss = 0.0\n"
    "        for winner, loser in pairs:\n"
    "            # P(winner > loser) = sigmoid(theta_w - theta_l)\n"
    "            diff = theta[winner] - theta[loser]\n"
    "            prob = sigmoid(diff)\n"
    "            total_loss -= np.log(prob + 1e-9)\n"
    "            # Gradient: d/d_theta_w log sigmoid(tw - tl) = 1 - prob\n"
    "            #           d/d_theta_l = -(1 - prob)\n"
    "            grad[winner] += (1 - prob)\n"
    "            grad[loser] -= (1 - prob)\n"
    "\n"
    "        theta += lr * grad / len(pairs)\n"
    "        # Anchor: fix mean to zero (identifiability)\n"
    "        theta -= theta.mean()\n"
    "        loss_history.append(total_loss / len(pairs))\n"
    "\n"
    "    return theta, loss_history\n"
    "\n"
    "\n"
    "# Demo: 10 items with known quality scores\n"
    "n_items = 10\n"
    "true_scores = np.linspace(-2, 2, n_items)  # known ground truth\n"
    "np.random.shuffle(true_scores)\n"
    "\n"
    "pairs = generate_preference_data(true_scores, n_comparisons=400)\n"
    "learned_scores, loss_hist = train_bradley_terry(n_items, pairs, n_epochs=300)\n"
    "\n"
    "# Evaluate: correlation between learned and true scores\n"
    "corr = np.corrcoef(true_scores, learned_scores)[0, 1]\n"
    "print(f'Bradley-Terry Results:')\n"
    "print(f'  True-learned rank correlation: {corr:.3f}')\n"
    "print(f'  Final loss: {loss_hist[-1]:.4f}')\n"
    "\n"
    "# Ranking accuracy: does learned order match true order?\n"
    "true_rank = np.argsort(np.argsort(true_scores))\n"
    "learned_rank = np.argsort(np.argsort(learned_scores))\n"
    "rank_corr = np.corrcoef(true_rank, learned_rank)[0, 1]\n"
    "print(f'  Spearman rank correlation: {rank_corr:.3f}')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
    "axes[0].plot(loss_hist, color='#2c7bb6', linewidth=2)\n"
    "axes[0].set_xlabel('Epoch', fontsize=12)\n"
    "axes[0].set_ylabel('Negative Log-Likelihood', fontsize=12)\n"
    "axes[0].set_title('Bradley-Terry Training Loss', fontsize=12)\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "axes[1].scatter(true_scores, learned_scores, color='#d7191c', s=80, alpha=0.8,\n"
    "                edgecolors='black', linewidths=0.5)\n"
    "m, b = np.polyfit(true_scores, learned_scores, 1)\n"
    "x_line = np.linspace(true_scores.min(), true_scores.max(), 100)\n"
    "axes[1].plot(x_line, m * x_line + b, 'k--', alpha=0.5, label=f'fit (r={corr:.2f})')\n"
    "axes[1].set_xlabel('True Quality Score', fontsize=12)\n"
    "axes[1].set_ylabel('Learned BT Score', fontsize=12)\n"
    "axes[1].set_title('True vs Learned Reward Model', fontsize=12)\n"
    "axes[1].legend()\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_bradley_terry.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c5 = md(
    "## Level 2: Full RLHF Loop with Reward Hacking Demo\n\n"
    "Toy RLHF on a 10-vocab, 5-token sequence generation task.\n"
    "- SFT policy: uniform distribution (baseline)\n"
    "- Reward model: trained on pairwise preferences\n"
    "- PPO-style update: shift policy toward high-reward outputs\n"
    "- KL penalty: prevent policy from diverging too far from reference\n"
    "Show reward hacking when beta -> 0: RM score rises, true quality falls.\n"
)

c6 = code(
    "# Toy RLHF on discrete sequence generation\n"
    "# State: vocabulary of 10 tokens, sequences of length 5\n"
    "# 'True quality': number of token-0s in sequence (known oracle)\n"
    "# Reward model: learns from pairwise comparisons (imperfect proxy)\n"
    "\n"
    "VOCAB_SIZE = 10\n"
    "SEQ_LEN = 5\n"
    "\n"
    "\n"
    "def true_quality(seq):\n"
    "    # Oracle quality: fraction of token-0 (simple but evaluable)\n"
    "    return np.sum(seq == 0) / len(seq)\n"
    "\n"
    "\n"
    "def generate_sft_data(n=500):\n"
    "    # SFT demonstrations: bias toward token 0, but noisy\n"
    "    seqs = []\n"
    "    for _ in range(n):\n"
    "        probs = np.ones(VOCAB_SIZE) * 0.05\n"
    "        probs[0] = 0.55  # token-0 preferred\n"
    "        probs /= probs.sum()\n"
    "        seq = np.random.choice(VOCAB_SIZE, size=SEQ_LEN, p=probs)\n"
    "        seqs.append(seq)\n"
    "    return np.array(seqs)\n"
    "\n"
    "\n"
    "def train_reward_model(seqs_w, seqs_l, n_features=VOCAB_SIZE * SEQ_LEN):\n"
    "    # Reward model: predict which sequence is preferred\n"
    "    # Features: one-hot-ish (token counts per position)\n"
    "    def featurize(seqs):\n"
    "        X = []\n"
    "        for seq in seqs:\n"
    "            # Token frequency features\n"
    "            counts = np.bincount(seq, minlength=VOCAB_SIZE).astype(float)\n"
    "            counts /= SEQ_LEN  # normalize\n"
    "            X.append(counts)\n"
    "        return np.array(X)\n"
    "\n"
    "    X_w = featurize(seqs_w)\n"
    "    X_l = featurize(seqs_l)\n"
    "    # Reward difference as input\n"
    "    X_diff = np.concatenate([X_w - X_l, X_w, X_l], axis=1)\n"
    "    y = np.ones(len(X_diff))  # winner always listed first\n"
    "\n"
    "    rm = LogisticRegression(C=1.0, max_iter=500, random_state=42)\n"
    "    rm.fit(X_diff, y)\n"
    "    return rm, featurize\n"
    "\n"
    "\n"
    "def rm_score(rm, featurize, seq):\n"
    "    # Get reward model score for a single sequence\n"
    "    x = featurize([seq])[0]\n"
    "    # Use logit of class probability as scalar reward\n"
    "    proba = rm.predict_proba(np.concatenate([x, x, np.zeros_like(x)]).reshape(1, -1))[0, 1]\n"
    "    return np.log(proba + 1e-9) - np.log(1 - proba + 1e-9)\n"
    "\n"
    "\n"
    "def run_rlhf_loop(beta=0.1, n_steps=300, lr_policy=0.05):\n"
    "    # Policy: softmax distribution over VOCAB for each position\n"
    "    # For simplicity: position-independent token distribution (bag-of-tokens)\n"
    "    logits_ref = np.zeros(VOCAB_SIZE)  # uniform reference (SFT init)\n"
    "    logits = logits_ref.copy()\n"
    "\n"
    "    # Build reward model from SFT demonstrations\n"
    "    sft_data = generate_sft_data(500)\n"
    "    # Create preference pairs: higher true_quality wins\n"
    "    seqs_w, seqs_l = [], []\n"
    "    for _ in range(400):\n"
    "        i, j = np.random.randint(len(sft_data), size=2)\n"
    "        qi, qj = true_quality(sft_data[i]), true_quality(sft_data[j])\n"
    "        if qi > qj:\n"
    "            seqs_w.append(sft_data[i])\n"
    "            seqs_l.append(sft_data[j])\n"
    "        elif qj > qi:\n"
    "            seqs_w.append(sft_data[j])\n"
    "            seqs_l.append(sft_data[i])\n"
    "    rm, featurize = train_reward_model(seqs_w, seqs_l)\n"
    "\n"
    "    rm_scores_history = []\n"
    "    true_quality_history = []\n"
    "    kl_history = []\n"
    "\n"
    "    for step in range(n_steps):\n"
    "        # Sample batch of sequences from current policy\n"
    "        probs = np.exp(logits - logits.max())\n"
    "        probs /= probs.sum()\n"
    "        batch_seqs = [np.random.choice(VOCAB_SIZE, size=SEQ_LEN, p=probs)\n"
    "                      for _ in range(32)]\n"
    "\n"
    "        # Compute rewards: RM score - beta * KL penalty\n"
    "        rewards = []\n"
    "        for seq in batch_seqs:\n"
    "            rm_r = rm_score(rm, featurize, seq)\n"
    "            # KL(pi || pi_ref) approximated per token\n"
    "            probs_ref = np.exp(logits_ref - logits_ref.max())\n"
    "            probs_ref /= probs_ref.sum()\n"
    "            kl = np.sum(probs * np.log((probs + 1e-9) / (probs_ref + 1e-9)))\n"
    "            rewards.append(rm_r - beta * kl)\n"
    "\n"
    "        rewards = np.array(rewards)\n"
    "        # Normalize rewards for stable gradient\n"
    "        rewards = (rewards - rewards.mean()) / (rewards.std() + 1e-8)\n"
    "\n"
    "        # Policy gradient update: increase logits for tokens in high-reward seqs\n"
    "        grad = np.zeros(VOCAB_SIZE)\n"
    "        for seq, rew in zip(batch_seqs, rewards):\n"
    "            for token in seq:\n"
    "                # log prob gradient w.r.t. logit: 1 - prob[token] (REINFORCE)\n"
    "                grad[token] += rew * (1.0 - probs[token])\n"
    "        logits += lr_policy * grad / len(batch_seqs)\n"
    "\n"
    "        # Track metrics\n"
    "        probs_curr = np.exp(logits - logits.max())\n"
    "        probs_curr /= probs_curr.sum()\n"
    "        sample_seqs = [np.random.choice(VOCAB_SIZE, size=SEQ_LEN, p=probs_curr)\n"
    "                       for _ in range(64)]\n"
    "        rm_scores_history.append(np.mean([rm_score(rm, featurize, s) for s in sample_seqs]))\n"
    "        true_quality_history.append(np.mean([true_quality(s) for s in sample_seqs]))\n"
    "        probs_ref = np.exp(logits_ref - logits_ref.max())\n"
    "        probs_ref /= probs_ref.sum()\n"
    "        kl_history.append(np.sum(probs_curr * np.log((probs_curr + 1e-9) / (probs_ref + 1e-9))))\n"
    "\n"
    "    return rm_scores_history, true_quality_history, kl_history\n"
    "\n"
    "\n"
    "print('Running RLHF with beta=0.1 (standard)...')\n"
    "rm_01, tq_01, kl_01 = run_rlhf_loop(beta=0.1)\n"
    "print(f'  Final RM score: {np.mean(rm_01[-20:]):.3f}, True quality: {np.mean(tq_01[-20:]):.3f}')\n"
    "\n"
    "print('Running RLHF with beta=0.001 (reward hacking)...')\n"
    "rm_hack, tq_hack, kl_hack = run_rlhf_loop(beta=0.001)\n"
    "print(f'  Final RM score: {np.mean(rm_hack[-20:]):.3f}, True quality: {np.mean(tq_hack[-20:]):.3f}')\n"
    "print(f'  Reward hacking: RM score higher but true quality may differ')\n"
)

c7 = md(
    "## Real-World Example 1: Reward Model Calibration\n\n"
    "Train reward model on preference data and evaluate calibration.\n"
    "A well-calibrated RM has Brier score < 0.2 and accurate confidence estimates.\n"
    "Miscalibration is the root cause of reward hacking.\n"
)

c8 = code(
    "from sklearn.calibration import calibration_curve\n"
    "\n"
    "\n"
    "def evaluate_rm_calibration(n_items=50, n_comparisons_train=300, n_comparisons_test=200):\n"
    "    # Generate items with known quality scores\n"
    "    true_scores_cal = np.random.normal(0, 1, n_items)\n"
    "\n"
    "    def make_comparison_data(n_comps):\n"
    "        X, y = [], []\n"
    "        for _ in range(n_comps):\n"
    "            i, j = np.random.choice(n_items, size=2, replace=False)\n"
    "            p_win = sigmoid(true_scores_cal[i] - true_scores_cal[j])\n"
    "            label = 1 if np.random.random() < p_win else 0\n"
    "            # Features: one-hot item indices (simplified)\n"
    "            feat = np.zeros(2 * n_items)\n"
    "            feat[i] = 1.0  # item i features\n"
    "            feat[n_items + j] = 1.0  # item j features\n"
    "            X.append(feat)\n"
    "            y.append(label)\n"
    "        return np.array(X), np.array(y)\n"
    "\n"
    "    X_train, y_train = make_comparison_data(n_comparisons_train)\n"
    "    X_test, y_test = make_comparison_data(n_comparisons_test)\n"
    "\n"
    "    # Train reward model\n"
    "    rm_cal = LogisticRegression(C=0.1, max_iter=500, random_state=42)\n"
    "    rm_cal.fit(X_train, y_train)\n"
    "\n"
    "    # Get predicted probabilities on test set\n"
    "    y_pred_proba = rm_cal.predict_proba(X_test)[:, 1]\n"
    "\n"
    "    # Brier score\n"
    "    brier = brier_score_loss(y_test, y_pred_proba)\n"
    "\n"
    "    # Calibration curve\n"
    "    fraction_of_positives, mean_predicted = calibration_curve(\n"
    "        y_test, y_pred_proba, n_bins=10\n"
    "    )\n"
    "\n"
    "    return brier, fraction_of_positives, mean_predicted, y_pred_proba, y_test\n"
    "\n"
    "\n"
    "brier, frac_pos, mean_pred, proba_pred, y_actual = evaluate_rm_calibration()\n"
    "print(f'Reward Model Calibration:')\n"
    "print(f'  Brier score: {brier:.4f} (lower=better, random=0.25, perfect=0)')\n"
    "print(f'  Test accuracy: {np.mean((proba_pred > 0.5) == y_actual):.3f}')\n"
    "\n"
    "# Sample efficiency: Brier score vs training data size\n"
    "train_sizes = [50, 100, 200, 500, 1000]\n"
    "brier_scores = []\n"
    "for n_train in train_sizes:\n"
    "    bs, _, _, _, _ = evaluate_rm_calibration(n_comparisons_train=n_train)\n"
    "    brier_scores.append(bs)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "\n"
    "# Calibration curve\n"
    "axes[0].plot(mean_pred, frac_pos, 's-', color='#d7191c',\n"
    "             linewidth=2, markersize=8, label='RM calibration')\n"
    "axes[0].plot([0, 1], [0, 1], 'k--', alpha=0.5, label='Perfect calibration')\n"
    "axes[0].set_xlabel('Mean Predicted Probability', fontsize=12)\n"
    "axes[0].set_ylabel('Fraction of Positives', fontsize=12)\n"
    "axes[0].set_title(f'Reward Model Calibration Curve (Brier={brier:.3f})', fontsize=12)\n"
    "axes[0].legend()\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "# Brier score vs training size\n"
    "axes[1].plot(train_sizes, brier_scores, 'o-', color='#2c7bb6', linewidth=2, markersize=8)\n"
    "axes[1].axhline(y=0.2, color='#d7191c', linestyle='--', label='Good calibration threshold (0.2)')\n"
    "axes[1].set_xlabel('Training Comparisons', fontsize=12)\n"
    "axes[1].set_ylabel('Brier Score', fontsize=12)\n"
    "axes[1].set_title('RM Calibration vs Training Data Size', fontsize=12)\n"
    "axes[1].set_xscale('log')\n"
    "axes[1].legend()\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_calibration.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Minimum Brier score achieved: {min(brier_scores):.4f} at {train_sizes[np.argmin(brier_scores)]} comparisons')\n"
)

c9 = md(
    "## Real-World Example 2: KL Penalty Sweep\n\n"
    "Sweep beta in {0.001, 0.01, 0.1, 1.0} to show the reward-KL tradeoff.\n"
    "- Small beta: high RM reward but high KL (reward hacking risk)\n"
    "- Large beta: low KL but conservative reward gains\n"
    "This is the fundamental tension in RLHF training.\n"
)

c10 = code(
    "betas = [0.001, 0.01, 0.05, 0.1, 0.5, 1.0]\n"
    "beta_results = {}\n"
    "\n"
    "for beta in betas:\n"
    "    np.random.seed(42)\n"
    "    rm_hist, tq_hist, kl_hist = run_rlhf_loop(beta=beta, n_steps=200)\n"
    "    beta_results[beta] = {\n"
    "        'rm_final': np.mean(rm_hist[-30:]),\n"
    "        'tq_final': np.mean(tq_hist[-30:]),\n"
    "        'kl_final': np.mean(kl_hist[-30:]),\n"
    "        'rm_hist': rm_hist,\n"
    "        'kl_hist': kl_hist,\n"
    "    }\n"
    "\n"
    "print('KL Penalty Sweep Results:')\n"
    "print(f'{\"beta\":<8} {\"RM score\":<12} {\"True quality\":<15} {\"KL div\":<10}')\n"
    "print('-' * 45)\n"
    "for beta in betas:\n"
    "    r = beta_results[beta]\n"
    "    print(f'{beta:<8.3f} {r[\"rm_final\"]:<12.3f} {r[\"tq_final\"]:<15.3f} {r[\"kl_final\"]:<10.4f}')\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n"
    "colors_beta = plt.cm.viridis(np.linspace(0.1, 0.9, len(betas)))\n"
    "\n"
    "for idx, beta in enumerate(betas):\n"
    "    r = beta_results[beta]\n"
    "    axes[0].plot(r['rm_hist'], color=colors_beta[idx], label=f'beta={beta}', linewidth=1.5)\n"
    "    axes[1].plot(r['kl_hist'], color=colors_beta[idx], label=f'beta={beta}', linewidth=1.5)\n"
    "\n"
    "axes[0].set_title('RM Score over Training', fontsize=12)\n"
    "axes[0].set_xlabel('Step')\n"
    "axes[0].set_ylabel('RM Score')\n"
    "axes[0].legend(fontsize=8)\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "axes[1].set_title('KL Divergence over Training', fontsize=12)\n"
    "axes[1].set_xlabel('Step')\n"
    "axes[1].set_ylabel('KL(pi || pi_ref)')\n"
    "axes[1].legend(fontsize=8)\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "# Pareto frontier: RM score vs KL\n"
    "rm_finals = [beta_results[b]['rm_final'] for b in betas]\n"
    "kl_finals = [beta_results[b]['kl_final'] for b in betas]\n"
    "tq_finals = [beta_results[b]['tq_final'] for b in betas]\n"
    "sc = axes[2].scatter(kl_finals, rm_finals, c=betas, cmap='viridis',\n"
    "                     s=120, edgecolors='black', linewidths=0.8, zorder=5)\n"
    "for beta, kl, rm in zip(betas, kl_finals, rm_finals):\n"
    "    axes[2].annotate(f'b={beta}', (kl, rm), textcoords='offset points',\n"
    "                     xytext=(5, 5), fontsize=9)\n"
    "axes[2].set_xlabel('Final KL Divergence', fontsize=12)\n"
    "axes[2].set_ylabel('Final RM Score', fontsize=12)\n"
    "axes[2].set_title('Reward-KL Pareto Frontier', fontsize=12)\n"
    "plt.colorbar(sc, ax=axes[2], label='beta value')\n"
    "axes[2].set_facecolor('#f8f8f8')\n"
    "axes[2].grid(True, alpha=0.4)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_kl_sweep.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c11 = md(
    "## Real-World Example 3: DPO as RLHF Alternative\n\n"
    "Direct Preference Optimization (DPO) bypasses the reward model entirely.\n"
    "DPO loss: -log(sigma(beta * log(pi_theta(y_w)/pi_ref(y_w)) - beta * log(pi_theta(y_l)/pi_ref(y_l))))\n"
    "Compare: RLHF requires RM training + PPO; DPO needs only one supervised pass.\n"
)

c12 = code(
    "def run_dpo(preference_data, n_epochs=100, lr=0.05, beta=0.1):\n"
    "    # DPO on toy token distribution\n"
    "    # preference_data: list of (seq_w, seq_l) pairs\n"
    "    # Policy: logits over VOCAB_SIZE tokens\n"
    "    logits = np.zeros(VOCAB_SIZE)  # initialized to reference (uniform)\n"
    "    logits_ref = np.zeros(VOCAB_SIZE)  # frozen reference\n"
    "\n"
    "    def log_prob_seq(logits, seq):\n"
    "        # Sum of log probs for each token in sequence\n"
    "        probs = np.exp(logits - logits.max())\n"
    "        probs /= probs.sum()\n"
    "        return np.sum(np.log(probs[seq] + 1e-9))\n"
    "\n"
    "    losses = []\n"
    "    tq_history = []\n"
    "\n"
    "    for epoch in range(n_epochs):\n"
    "        grad = np.zeros(VOCAB_SIZE)\n"
    "        total_loss = 0.0\n"
    "\n"
    "        for seq_w, seq_l in preference_data:\n"
    "            # DPO implicit reward difference\n"
    "            log_pi_w = log_prob_seq(logits, seq_w)\n"
    "            log_pi_l = log_prob_seq(logits, seq_l)\n"
    "            log_ref_w = log_prob_seq(logits_ref, seq_w)\n"
    "            log_ref_l = log_prob_seq(logits_ref, seq_l)\n"
    "\n"
    "            # DPO reward signal\n"
    "            reward_diff = beta * ((log_pi_w - log_ref_w) - (log_pi_l - log_ref_l))\n"
    "            loss = -np.log(sigmoid(reward_diff) + 1e-9)\n"
    "            total_loss += loss\n"
    "\n"
    "            # Gradient: increase prob of winner tokens, decrease loser tokens\n"
    "            probs = np.exp(logits - logits.max())\n"
    "            probs /= probs.sum()\n"
    "            scale = (1 - sigmoid(reward_diff)) * beta\n"
    "\n"
    "            for tok in seq_w:\n"
    "                grad[tok] += scale * (1.0 - probs[tok])\n"
    "            for tok in seq_l:\n"
    "                grad[tok] -= scale * (1.0 - probs[tok])\n"
    "\n"
    "        logits += lr * grad / len(preference_data)\n"
    "        losses.append(total_loss / len(preference_data))\n"
    "\n"
    "        # Track true quality\n"
    "        probs_curr = np.exp(logits - logits.max())\n"
    "        probs_curr /= probs_curr.sum()\n"
    "        samples = [np.random.choice(VOCAB_SIZE, size=SEQ_LEN, p=probs_curr)\n"
    "                   for _ in range(64)]\n"
    "        tq_history.append(np.mean([true_quality(s) for s in samples]))\n"
    "\n"
    "    return logits, losses, tq_history\n"
    "\n"
    "\n"
    "# Build preference dataset\n"
    "np.random.seed(42)\n"
    "sft_data_dpo = generate_sft_data(300)\n"
    "dpo_pairs = []\n"
    "for _ in range(200):\n"
    "    i, j = np.random.randint(len(sft_data_dpo), size=2)\n"
    "    qi, qj = true_quality(sft_data_dpo[i]), true_quality(sft_data_dpo[j])\n"
    "    if qi > qj:\n"
    "        dpo_pairs.append((sft_data_dpo[i], sft_data_dpo[j]))\n"
    "    elif qj > qi:\n"
    "        dpo_pairs.append((sft_data_dpo[j], sft_data_dpo[i]))\n"
    "\n"
    "print(f'DPO training with {len(dpo_pairs)} preference pairs')\n"
    "_, dpo_losses, dpo_tq = run_dpo(dpo_pairs, n_epochs=100, beta=0.1)\n"
    "\n"
    "# Compare RLHF vs DPO true quality\n"
    "print(f'Final true quality - RLHF (beta=0.1): {np.mean(tq_01[-20:]):.3f}')\n"
    "print(f'Final true quality - DPO (beta=0.1):  {np.mean(dpo_tq[-20:]):.3f}')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "\n"
    "axes[0].plot(dpo_losses, color='#2c7bb6', linewidth=2, label='DPO loss')\n"
    "axes[0].set_xlabel('Epoch', fontsize=12)\n"
    "axes[0].set_ylabel('DPO Loss', fontsize=12)\n"
    "axes[0].set_title('DPO Training Loss', fontsize=12)\n"
    "axes[0].legend()\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "axes[1].plot(tq_01, color='#d7191c', label='RLHF (PPO, beta=0.1)', linewidth=2)\n"
    "axes[1].plot(np.linspace(0, len(tq_01)-1, len(dpo_tq)), dpo_tq,\n"
    "             color='#2c7bb6', label='DPO', linewidth=2, linestyle='--')\n"
    "axes[1].set_xlabel('Training Steps', fontsize=12)\n"
    "axes[1].set_ylabel('True Quality', fontsize=12)\n"
    "axes[1].set_title('True Quality: RLHF vs DPO', fontsize=12)\n"
    "axes[1].legend()\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_dpo_compare.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c13 = md(
    "## Comparison: RLHF (PPO) vs DPO vs SFT-only\n\n"
    "Quality vs training cost tradeoff across all three alignment approaches.\n"
)

c14 = code(
    "# Compute SFT-only baseline (no RL)\n"
    "np.random.seed(42)\n"
    "sft_only_data = generate_sft_data(500)\n"
    "sft_quality = np.mean([true_quality(s) for s in sft_only_data])\n"
    "\n"
    "# Summarize final quality for each method\n"
    "methods = ['SFT only', 'RLHF beta=0.001\\n(hacking)', 'RLHF beta=0.1\\n(standard)',\n"
    "           'RLHF beta=1.0\\n(conservative)', 'DPO beta=0.1']\n"
    "qualities = [\n"
    "    sft_quality,\n"
    "    np.mean(tq_hack[-30:]),\n"
    "    np.mean(tq_01[-30:]),\n"
    "    beta_results[1.0]['tq_final'],\n"
    "    np.mean(dpo_tq[-30:]),\n"
    "]\n"
    "rm_scores_final = [\n"
    "    0.0,  # SFT: no RM\n"
    "    beta_results[0.001]['rm_final'],\n"
    "    beta_results[0.1]['rm_final'],\n"
    "    beta_results[1.0]['rm_final'],\n"
    "    0.0,  # DPO: no explicit RM score\n"
    "]\n"
    "compute_cost = [1, 3, 3, 3, 2]  # relative units (SFT=1, RLHF=3 stages, DPO=2 stages)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n"
    "colors_m = ['#636363', '#d7191c', '#2c7bb6', '#1a9641', '#fd8d3c']\n"
    "\n"
    "x = np.arange(len(methods))\n"
    "bars = axes[0].bar(x, qualities, color=colors_m, alpha=0.85, edgecolor='black')\n"
    "axes[0].set_xticks(x)\n"
    "axes[0].set_xticklabels(methods, fontsize=9)\n"
    "axes[0].set_ylabel('True Quality Score', fontsize=12)\n"
    "axes[0].set_title('True Quality by Alignment Method', fontsize=12)\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4, axis='y')\n"
    "for bar, val in zip(bars, qualities):\n"
    "    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.003,\n"
    "                 f'{val:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')\n"
    "\n"
    "# Reward score vs compute cost scatter\n"
    "for m, q, rm, cost, color in zip(methods, qualities, rm_scores_final, compute_cost, colors_m):\n"
    "    label = m.replace('\\n', ' ')\n"
    "    axes[1].scatter(cost, q, s=150, color=color, edgecolors='black',\n"
    "                    linewidths=0.8, zorder=5)\n"
    "    axes[1].annotate(label, (cost, q), textcoords='offset points',\n"
    "                     xytext=(6, 3), fontsize=8)\n"
    "\n"
    "axes[1].set_xlabel('Relative Compute Cost (training stages)', fontsize=12)\n"
    "axes[1].set_ylabel('True Quality Score', fontsize=12)\n"
    "axes[1].set_title('Quality vs Compute Tradeoff', fontsize=12)\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_comparison.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c15 = md(
    "## Key Takeaways\n\n"
    "**Core idea:** RLHF trains a reward model from human preferences, then uses PPO "
    "to optimize the policy against that reward while penalizing KL divergence from the reference policy.\n\n"
    "**Variants and when to use:**\n\n"
    "| Method | RM needed | Online RL | Compute | Use when |\n"
    "|--------|----------|-----------|---------|----------|\n"
    "| SFT only | No | No | Low | Simple instruction following |\n"
    "| RLHF (PPO) | Yes | Yes | High | Complex alignment, growing data |\n"
    "| DPO | No (implicit) | No | Low | Fixed preference dataset, low compute |\n"
    "| KTO | No | No | Low | Single-response feedback (binary) |\n\n"
    "**Common failure modes:**\n"
    "- beta too small -> reward hacking (RM score up, true quality flat)\n"
    "- RM miscalibrated (Brier > 0.25) -> PPO optimizes wrong signal\n"
    "- KL explodes -> incoherent outputs, reduce LR or increase beta\n"
)

c16 = md(
    "## Exercises\n\n"
    "1. **Reward hacking detection**: In `run_rlhf_loop`, plot both RM score and `true_quality` on the same axes. "
    "At what step does hacking diverge?\n"
    "2. **Data efficiency**: Vary `n_comparisons_train` in `evaluate_rm_calibration`. "
    "What is the minimum needed for Brier < 0.2?\n"
    "3. **DPO beta sweep**: Run DPO with beta={0.01, 0.1, 1.0}. "
    "How does beta affect the quality-diversity tradeoff?\n"
    "4. **Combine DPO + RM**: Use DPO's final policy to generate new preference data, "
    "retrain RM, then run RLHF. Does iterative refinement help?\n"
)

nb.cells = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16]
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.8.0"}
}

out = '/home/sbisw/github/interviewprep-ml/rl/notebooks/17-rlhf.ipynb'
nbformat.write(nb, out)
print(f"Written: {out}")
print(f"Cells: {len(nb.cells)}")
code_lines = sum(
    len(''.join(c['source']).split('\n'))
    for c in nb.cells if c['cell_type'] == 'code'
)
print(f"Code lines: {code_lines}")
