"""Generator for notebook 19: Multi-Agent RL"""
import nbformat

def md(text):
    return nbformat.v4.new_markdown_cell(text)

def code(text):
    return nbformat.v4.new_code_cell(text)

nb = nbformat.v4.new_notebook()

c1 = md(
    "# 19 - Multi-Agent Reinforcement Learning\n\n"
    "## Learning Objectives\n"
    "1. Understand Nash equilibrium and why independent learners fail\n"
    "2. Implement Q-learning for matrix games (Prisoner's Dilemma, RPS)\n"
    "3. Build cooperative pursuit with CTDE (centralized critic, decentralized actors)\n"
    "4. Compare independent Q-learning vs CTDE on cooperative and competitive tasks\n"
)

c2 = code(
    "import numpy as np\n"
    "import matplotlib.pyplot as plt\n"
    "from sklearn.neural_network import MLPRegressor\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "np.random.seed(42)\n"
    "print('Packages loaded: numpy', np.__version__)\n"
    "print('MARL demo: matrix games, cooperative pursuit, competitive adversarial')\n"
)

c3 = md(
    "## Level 1: Matrix Game Q-Learning\n\n"
    "Two-player matrix games: Prisoner's Dilemma and Rock-Paper-Scissors.\n"
    "Each agent maintains independent Q-values for (action,) pairs.\n"
    "Does independent Q-learning converge to Nash equilibrium?\n"
)

c4 = code(
    "def run_prisoners_dilemma(n_steps=5000, alpha=0.1, eps=0.1):\n"
    "    # Payoff matrix: P[a1][a2] = (reward_agent1, reward_agent2)\n"
    "    # Actions: 0=Cooperate, 1=Defect\n"
    "    # Defect dominates, Nash = (Defect, Defect) -> payoff (-1, -1)\n"
    "    # Pareto optimal = (Cooperate, Cooperate) -> payoff (2, 2)\n"
    "    payoff = [\n"
    "        [(2, 2), (-1, 3)],   # row=Cooperate: vs C -> (2,2), vs D -> (-1,3)\n"
    "        [(3, -1), (-1, -1)]  # row=Defect: vs C -> (3,-1), vs D -> (-1,-1)\n"
    "    ]\n"
    "    n_actions = 2\n"
    "\n"
    "    # Q-tables: Q1[a] and Q2[a] (stateless single-stage game)\n"
    "    Q1 = np.zeros(n_actions)\n"
    "    Q2 = np.zeros(n_actions)\n"
    "\n"
    "    action_history_1 = []\n"
    "    action_history_2 = []\n"
    "    reward_history_1 = []\n"
    "\n"
    "    for step in range(n_steps):\n"
    "        # Epsilon-greedy\n"
    "        a1 = np.random.randint(n_actions) if np.random.random() < eps else np.argmax(Q1)\n"
    "        a2 = np.random.randint(n_actions) if np.random.random() < eps else np.argmax(Q2)\n"
    "\n"
    "        r1, r2 = payoff[a1][a2]\n"
    "\n"
    "        # Independent Q-update (single-step game: no next state)\n"
    "        Q1[a1] += alpha * (r1 - Q1[a1])\n"
    "        Q2[a2] += alpha * (r2 - Q2[a2])\n"
    "\n"
    "        action_history_1.append(a1)\n"
    "        action_history_2.append(a2)\n"
    "        reward_history_1.append(r1)\n"
    "\n"
    "    # Nash equilibrium analysis\n"
    "    final_policy_1 = np.argmax(Q1)  # deterministic\n"
    "    final_policy_2 = np.argmax(Q2)\n"
    "    coop_rate = np.mean(np.array(action_history_1[-500:]) == 0)\n"
    "\n"
    "    return action_history_1, action_history_2, reward_history_1, Q1, Q2\n"
    "\n"
    "\n"
    "def run_rps(n_steps=5000, alpha=0.05, eps=0.15):\n"
    "    # Rock-Paper-Scissors: Nash = uniform mix (1/3, 1/3, 1/3)\n"
    "    # Payoff: win=+1, lose=-1, tie=0\n"
    "    def payoff(a1, a2):\n"
    "        if a1 == a2:\n"
    "            return 0, 0\n"
    "        wins = {0: 2, 1: 0, 2: 1}  # 0=Rock beats Scissors, 1=Paper beats Rock, 2=Scissors beats Paper\n"
    "        if wins[a1] == a2:\n"
    "            return 1, -1\n"
    "        return -1, 1\n"
    "\n"
    "    n_actions = 3\n"
    "    Q1 = np.zeros(n_actions)\n"
    "    Q2 = np.zeros(n_actions)\n"
    "\n"
    "    action_hist_1 = []\n"
    "    reward_hist_1 = []\n"
    "\n"
    "    for step in range(n_steps):\n"
    "        a1 = np.random.randint(n_actions) if np.random.random() < eps else np.argmax(Q1)\n"
    "        a2 = np.random.randint(n_actions) if np.random.random() < eps else np.argmax(Q2)\n"
    "        r1, r2 = payoff(a1, a2)\n"
    "        Q1[a1] += alpha * (r1 - Q1[a1])\n"
    "        Q2[a2] += alpha * (r2 - Q2[a2])\n"
    "        action_hist_1.append(a1)\n"
    "        reward_hist_1.append(r1)\n"
    "\n"
    "    return action_hist_1, reward_hist_1, Q1, Q2\n"
    "\n"
    "\n"
    "# Run both games\n"
    "np.random.seed(42)\n"
    "ah1, ah2, rh1, Q1_pd, Q2_pd = run_prisoners_dilemma(n_steps=5000)\n"
    "np.random.seed(42)\n"
    "ah_rps, rh_rps, Q1_rps, Q2_rps = run_rps(n_steps=5000)\n"
    "\n"
    "print('Prisoner Dilemma Results:')\n"
    "print(f'  Agent 1 final Q: Cooperate={Q1_pd[0]:.2f}, Defect={Q1_pd[1]:.2f}')\n"
    "print(f'  Agent 2 final Q: Cooperate={Q2_pd[0]:.2f}, Defect={Q2_pd[1]:.2f}')\n"
    "print(f'  Converged to Nash (Defect,Defect)? {np.argmax(Q1_pd)==1 and np.argmax(Q2_pd)==1}')\n"
    "print(f'  Last 1000 cooperation rate A1: {np.mean(np.array(ah1[-1000:])==0):.2f}')\n"
    "\n"
    "print('Rock-Paper-Scissors Results:')\n"
    "print(f'  Agent 1 final Q: {Q1_rps}')\n"
    "action_names = ['Rock', 'Paper', 'Scissors']\n"
    "print(f'  Agent 1 preferred action: {action_names[np.argmax(Q1_rps)]}')\n"
    "print(f'  Nash equilibrium: uniform (each action prob=1/3)')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
    "window = 100\n"
    "coop_ma = np.convolve(np.array(ah1)==0, np.ones(window)/window, mode='valid')\n"
    "axes[0].plot(coop_ma, color='#2c7bb6', linewidth=1.5)\n"
    "axes[0].axhline(y=0.5, color='gray', linestyle='--', label='Nash: 0% cooperation')\n"
    "axes[0].set_title('Prisoner Dilemma: Cooperation Rate\\n(Nash=Defect)', fontsize=11)\n"
    "axes[0].set_xlabel('Step')\n"
    "axes[0].set_ylabel('Cooperation Rate (rolling)')\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "# RPS: action frequency over time\n"
    "ah_arr = np.array(ah_rps)\n"
    "for act, name, color in zip([0,1,2], action_names, ['#2c7bb6','#d7191c','#1a9641']):\n"
    "    freq_ma = np.convolve(ah_arr==act, np.ones(window)/window, mode='valid')\n"
    "    axes[1].plot(freq_ma, color=color, label=name, linewidth=1.5)\n"
    "axes[1].axhline(y=1/3, color='black', linestyle='--', alpha=0.6, label='Nash: 1/3 each')\n"
    "axes[1].set_title('Rock-Paper-Scissors: Action Frequencies\\n(Nash=uniform)', fontsize=11)\n"
    "axes[1].set_xlabel('Step')\n"
    "axes[1].set_ylabel('Action Frequency (rolling)')\n"
    "axes[1].legend(fontsize=9)\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/marl_matrix_games.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c5 = md(
    "## Level 2: Cooperative Pursuit with CTDE\n\n"
    "Two agents cooperate to catch a target on a 6x6 grid.\n"
    "CTDE: centralized Q(s1, s2, a1, a2) trained on joint state+actions.\n"
    "Decentralized execution: each agent acts using only its own observation.\n"
    "Compare: independent Q-learning vs joint Q (CTDE approximation).\n"
)

c6 = code(
    "class PursuitGridWorld:\n"
    "    # Two agents cooperating to catch one target on 6x6 grid\n"
    "    def __init__(self, size=6):\n"
    "        self.size = size\n"
    "        self.n_agents = 2\n"
    "        self.n_actions = 4  # up, down, left, right\n"
    "        self.deltas = [(-1,0),(1,0),(0,-1),(0,1)]\n"
    "\n"
    "    def reset(self):\n"
    "        # Random non-overlapping positions\n"
    "        positions = np.random.choice(self.size**2, size=3, replace=False)\n"
    "        self.agent1 = (positions[0] // self.size, positions[0] % self.size)\n"
    "        self.agent2 = (positions[1] // self.size, positions[1] % self.size)\n"
    "        self.target = (positions[2] // self.size, positions[2] % self.size)\n"
    "        return self._obs()\n"
    "\n"
    "    def _obs(self):\n"
    "        # State: (agent1_r, agent1_c, agent2_r, agent2_c, target_r, target_c)\n"
    "        return (self.agent1[0], self.agent1[1],\n"
    "                self.agent2[0], self.agent2[1],\n"
    "                self.target[0], self.target[1])\n"
    "\n"
    "    def _move(self, pos, action):\n"
    "        r, c = pos\n"
    "        dr, dc = self.deltas[action]\n"
    "        nr = max(0, min(self.size-1, r+dr))\n"
    "        nc = max(0, min(self.size-1, c+dc))\n"
    "        return (nr, nc)\n"
    "\n"
    "    def step(self, a1, a2):\n"
    "        self.agent1 = self._move(self.agent1, a1)\n"
    "        self.agent2 = self._move(self.agent2, a2)\n"
    "        # Target moves randomly\n"
    "        self.target = self._move(self.target, np.random.randint(self.n_actions))\n"
    "\n"
    "        # Catch: either agent adjacent to target\n"
    "        d1 = abs(self.agent1[0]-self.target[0]) + abs(self.agent1[1]-self.target[1])\n"
    "        d2 = abs(self.agent2[0]-self.target[0]) + abs(self.agent2[1]-self.target[1])\n"
    "        caught = (d1 <= 1) or (d2 <= 1)\n"
    "        # Bonus for both agents being close (cooperation)\n"
    "        both_close = (d1 <= 2) and (d2 <= 2)\n"
    "\n"
    "        reward = 1.0 if caught else (0.2 if both_close else -0.01)\n"
    "        return self._obs(), reward, caught\n"
    "\n"
    "\n"
    "def obs_to_idx(obs, size=6):\n"
    "    # Convert (a1r, a1c, a2r, a2c, tr, tc) to integer index\n"
    "    a1r, a1c, a2r, a2c, tr, tc = obs\n"
    "    return (a1r * size**5 + a1c * size**4 + a2r * size**3 +\n"
    "            a2c * size**2 + tr * size + tc)\n"
    "\n"
    "\n"
    "def agent_obs_idx(obs, agent_id, size=6):\n"
    "    # Individual agent observation: (agent_r, agent_c, target_r, target_c)\n"
    "    if agent_id == 0:\n"
    "        return obs[0] * size**3 + obs[1] * size**2 + obs[4] * size + obs[5]\n"
    "    else:\n"
    "        return obs[2] * size**3 + obs[3] * size**2 + obs[4] * size + obs[5]\n"
    "\n"
    "\n"
    "def run_independent_ql(n_episodes=800, alpha=0.1, gamma=0.9, eps=0.2, size=6):\n"
    "    env = PursuitGridWorld(size=size)\n"
    "    # Each agent has Q-table over local obs\n"
    "    n_local_states = size ** 4  # (ar, ac, tr, tc) per agent\n"
    "    Q1 = np.zeros((n_local_states, env.n_actions))\n"
    "    Q2 = np.zeros((n_local_states, env.n_actions))\n"
    "    catch_rates = []\n"
    "\n"
    "    for ep in range(n_episodes):\n"
    "        obs = env.reset()\n"
    "        done = False\n"
    "        t = 0\n"
    "        while not done and t < 40:\n"
    "            s1 = agent_obs_idx(obs, 0, size)\n"
    "            s2 = agent_obs_idx(obs, 1, size)\n"
    "\n"
    "            if np.random.random() < eps:\n"
    "                a1 = np.random.randint(env.n_actions)\n"
    "            else:\n"
    "                a1 = np.argmax(Q1[s1])\n"
    "            if np.random.random() < eps:\n"
    "                a2 = np.random.randint(env.n_actions)\n"
    "            else:\n"
    "                a2 = np.argmax(Q2[s2])\n"
    "\n"
    "            obs2, r, done = env.step(a1, a2)\n"
    "            s1_next = agent_obs_idx(obs2, 0, size)\n"
    "            s2_next = agent_obs_idx(obs2, 1, size)\n"
    "\n"
    "            # Independent updates: each agent uses shared reward\n"
    "            Q1[s1, a1] += alpha * (r + gamma * np.max(Q1[s1_next]) - Q1[s1, a1])\n"
    "            Q2[s2, a2] += alpha * (r + gamma * np.max(Q2[s2_next]) - Q2[s2, a2])\n"
    "            obs = obs2\n"
    "            t += 1\n"
    "        catch_rates.append(1.0 if done else 0.0)\n"
    "    return Q1, Q2, catch_rates\n"
    "\n"
    "\n"
    "print('Training independent Q-learners on pursuit...')\n"
    "np.random.seed(42)\n"
    "Q1_ind, Q2_ind, rates_ind = run_independent_ql(n_episodes=800)\n"
    "print(f'  Final 100-ep catch rate: {np.mean(rates_ind[-100:]):.2f}')\n"
)

c7 = md(
    "## Real-World Example 1: Competitive Game - Adversarial Reward\n\n"
    "Two agents with opposing rewards on a 5x5 grid.\n"
    "Agent 1 tries to reach goal; Agent 2 tries to block.\n"
    "Show non-convergence and cycling without proper equilibrium training.\n"
)

c8 = code(
    "def run_adversarial_game(n_episodes=600, alpha=0.1, gamma=0.9, eps=0.15):\n"
    "    # Zero-sum: agent1 gets +1 at goal, agent2 gets +1 for blocking\n"
    "    size = 4\n"
    "    n_actions = 4\n"
    "    deltas = [(-1,0),(1,0),(0,-1),(0,1)]\n"
    "    goal = (3, 3)\n"
    "\n"
    "    def move(pos, action):\n"
    "        r, c = pos\n"
    "        dr, dc = deltas[action]\n"
    "        return (max(0, min(size-1, r+dr)), max(0, min(size-1, c+dc)))\n"
    "\n"
    "    def to_state(p1, p2):\n"
    "        return p1[0]*size**3 + p1[1]*size**2 + p2[0]*size + p2[1]\n"
    "\n"
    "    n_states = size**4\n"
    "    Q1 = np.zeros((n_states, n_actions))\n"
    "    Q2 = np.zeros((n_states, n_actions))\n"
    "\n"
    "    success_history = []  # agent1 reaches goal\n"
    "    block_history = []    # agent2 blocks\n"
    "\n"
    "    for ep in range(n_episodes):\n"
    "        p1 = (0, 0)\n"
    "        p2 = (size-1, 0)  # agent2 starts at bottom-left\n"
    "        for step in range(30):\n"
    "            s = to_state(p1, p2)\n"
    "            a1 = (np.random.randint(n_actions) if np.random.random() < eps\n"
    "                  else np.argmax(Q1[s]))\n"
    "            a2 = (np.random.randint(n_actions) if np.random.random() < eps\n"
    "                  else np.argmax(Q2[s]))\n"
    "\n"
    "            p1_new = move(p1, a1)\n"
    "            p2_new = move(p2, a2)\n"
    "            s_new = to_state(p1_new, p2_new)\n"
    "\n"
    "            # Rewards\n"
    "            p1_reached = p1_new == goal\n"
    "            p2_blocked = p2_new == p1_new  # block by occupying same cell\n"
    "\n"
    "            r1 = (1.0 if p1_reached else (-0.5 if p2_blocked else -0.01))\n"
    "            r2 = (1.0 if p2_blocked else (-0.5 if p1_reached else -0.01))\n"
    "\n"
    "            Q1[s, a1] += alpha * (r1 + gamma * np.max(Q1[s_new]) - Q1[s, a1])\n"
    "            Q2[s, a2] += alpha * (r2 + gamma * np.max(Q2[s_new]) - Q2[s, a2])\n"
    "\n"
    "            p1, p2 = p1_new, p2_new\n"
    "            if p1_reached or p2_blocked:\n"
    "                break\n"
    "\n"
    "        success_history.append(1.0 if p1 == goal else 0.0)\n"
    "        block_history.append(1.0 if p1 == p2 else 0.0)\n"
    "\n"
    "    return success_history, block_history\n"
    "\n"
    "\n"
    "np.random.seed(42)\n"
    "success_hist, block_hist = run_adversarial_game(n_episodes=600)\n"
    "\n"
    "window = 30\n"
    "succ_ma = np.convolve(success_hist, np.ones(window)/window, mode='valid')\n"
    "block_ma = np.convolve(block_hist, np.ones(window)/window, mode='valid')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "\n"
    "x = np.arange(len(succ_ma))\n"
    "axes[0].plot(x, succ_ma, color='#2c7bb6', label='Agent1 success', linewidth=2)\n"
    "axes[0].plot(x, block_ma, color='#d7191c', label='Agent2 block rate', linewidth=2)\n"
    "axes[0].set_xlabel('Episode', fontsize=12)\n"
    "axes[0].set_ylabel('Rate (rolling avg)', fontsize=12)\n"
    "axes[0].set_title('Competitive Game: Success vs Block Rate\\n(shows oscillation)', fontsize=11)\n"
    "axes[0].legend()\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "# Show non-stationarity: rolling std of success rate\n"
    "rolling_std = [np.std(success_hist[max(0,i-50):i+50]) for i in range(0, len(success_hist), 10)]\n"
    "axes[1].plot(np.arange(len(rolling_std))*10, rolling_std, color='#fd8d3c', linewidth=2)\n"
    "axes[1].set_xlabel('Episode', fontsize=12)\n"
    "axes[1].set_ylabel('Rolling Std of Success Rate', fontsize=12)\n"
    "axes[1].set_title('Non-Stationarity in Competitive MARL\\n(high std = cycling)', fontsize=11)\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/marl_adversarial.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Final success rate A1: {np.mean(success_hist[-100:]):.2f}')\n"
    "print(f'Final block rate A2: {np.mean(block_hist[-100:]):.2f}')\n"
    "print('Non-convergence: rolling std remains high in zero-sum game')\n"
)

c9 = md(
    "## Real-World Example 2: Communication Protocol Learning\n\n"
    "Two agents must coordinate to reach different targets.\n"
    "Agent 1 knows target A location, Agent 2 knows target B location.\n"
    "They can share a 1-bit message to coordinate actions.\n"
)

c10 = code(
    "def run_communication_game(n_episodes=1000, alpha=0.1, gamma=0.9, eps=0.2):\n"
    "    # Simple communication: Agent1 sends binary message m\n"
    "    # Agent2 receives m and conditions action on it\n"
    "    # Task: Agent1 goes to target A, Agent2 goes to target B\n"
    "    # But agents don't know each other's targets directly\n"
    "\n"
    "    # State: (target_A_location, target_B_location, both at goal?)\n"
    "    # Simplified: target is in left half or right half (binary)\n"
    "    n_target_configs = 4  # (A_side, B_side) each in {0,1}\n"
    "    n_messages = 2  # Agent1 sends 0 or 1\n"
    "    n_actions = 2  # go left or go right\n"
    "\n"
    "    # Agent1: Q1[target_A_side, action] (chooses action AND message)\n"
    "    Q1 = np.zeros((2, n_messages * n_actions))  # combined: (msg, action)\n"
    "    # Agent2: Q2[message, target_B_side, action]\n"
    "    Q2 = np.zeros((n_messages, 2, n_actions))\n"
    "\n"
    "    success_rates = []\n"
    "    message_corr = []  # does message correlate with target location?\n"
    "\n"
    "    for ep in range(n_episodes):\n"
    "        target_A = np.random.randint(2)  # 0=left, 1=right\n"
    "        target_B = np.random.randint(2)\n"
    "\n"
    "        # Agent1 observes target_A, chooses message m and action a1\n"
    "        combined_action = (np.random.randint(n_messages * n_actions)\n"
    "                           if np.random.random() < eps\n"
    "                           else np.argmax(Q1[target_A]))\n"
    "        m = combined_action // n_actions\n"
    "        a1 = combined_action % n_actions\n"
    "\n"
    "        # Agent2 receives message m, observes target_B, chooses action\n"
    "        a2 = (np.random.randint(n_actions) if np.random.random() < eps\n"
    "              else np.argmax(Q2[m, target_B]))\n"
    "\n"
    "        # Reward: both agents reach correct target\n"
    "        a1_correct = (a1 == target_A)\n"
    "        a2_correct = (a2 == target_B)\n"
    "        r = 1.0 if (a1_correct and a2_correct) else 0.0\n"
    "\n"
    "        # Q-updates\n"
    "        Q1[target_A, combined_action] += alpha * (r - Q1[target_A, combined_action])\n"
    "        Q2[m, target_B, a2] += alpha * (r - Q2[m, target_B, a2])\n"
    "\n"
    "        success_rates.append(r)\n"
    "        message_corr.append(m == target_A)  # does message encode target correctly?\n"
    "\n"
    "    return success_rates, message_corr, Q1, Q2\n"
    "\n"
    "\n"
    "np.random.seed(42)\n"
    "comm_success, msg_corr, Q1_comm, Q2_comm = run_communication_game(n_episodes=1000)\n"
    "\n"
    "window = 50\n"
    "succ_ma = np.convolve(comm_success, np.ones(window)/window, mode='valid')\n"
    "msg_ma = np.convolve(msg_corr, np.ones(window)/window, mode='valid')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "x = np.arange(len(succ_ma))\n"
    "\n"
    "axes[0].plot(x, succ_ma, color='#2c7bb6', linewidth=2, label='Joint success')\n"
    "axes[0].axhline(y=0.25, color='gray', linestyle='--', label='Random baseline (0.25)')\n"
    "axes[0].axhline(y=1.0, color='#1a9641', linestyle=':', label='Optimal (1.0)')\n"
    "axes[0].set_xlabel('Episode', fontsize=12)\n"
    "axes[0].set_ylabel('Success Rate', fontsize=12)\n"
    "axes[0].set_title('Communication Game: Learning to Coordinate', fontsize=12)\n"
    "axes[0].legend()\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "axes[1].plot(x, msg_ma, color='#d7191c', linewidth=2, label='Message = Target A side')\n"
    "axes[1].axhline(y=0.5, color='gray', linestyle='--', label='Random (0.5)')\n"
    "axes[1].axhline(y=1.0, color='#1a9641', linestyle=':', label='Perfect protocol (1.0)')\n"
    "axes[1].set_xlabel('Episode', fontsize=12)\n"
    "axes[1].set_ylabel('Message Informativeness', fontsize=12)\n"
    "axes[1].set_title('Emergent Communication Protocol\\n(Does message encode target?)', fontsize=11)\n"
    "axes[1].legend()\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/marl_communication.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Final success rate: {np.mean(comm_success[-100:]):.2f}')\n"
    "print(f'Message encodes target correctly: {np.mean(msg_corr[-100:]):.2f}')\n"
)

c11 = md(
    "## Real-World Example 3: Emergent Specialization\n\n"
    "N=4 cooperative agents on a larger grid, each with different strengths.\n"
    "No explicit role assignment: specialization emerges from learning.\n"
    "Track which agents specialize in which zones/tasks over training.\n"
)

c12 = code(
    "def run_specialization(n_agents=4, size=8, n_episodes=600, alpha=0.1, gamma=0.9, eps=0.2):\n"
    "    # Multi-target collection: 4 targets, 4 agents\n"
    "    # Shared reward when any target is collected\n"
    "    n_targets = n_agents\n"
    "    n_actions = 4\n"
    "    deltas = [(-1,0),(1,0),(0,-1),(0,1)]\n"
    "\n"
    "    def move(pos, action):\n"
    "        r, c = pos\n"
    "        dr, dc = deltas[action]\n"
    "        return (max(0, min(size-1, r+dr)), max(0, min(size-1, c+dc)))\n"
    "\n"
    "    # Fixed target positions (one per quadrant)\n"
    "    targets = [(1, 1), (1, 6), (6, 1), (6, 6)]\n"
    "\n"
    "    # Each agent has Q-table keyed by (own_pos_idx, nearest_target_idx)\n"
    "    n_pos = size ** 2\n"
    "    Q_all = [np.zeros((n_pos, n_targets, n_actions)) for _ in range(n_agents)]\n"
    "\n"
    "    collection_history = []  # how many targets collected per episode\n"
    "    specialization_history = [[] for _ in range(n_agents)]  # which target each agent collected\n"
    "\n"
    "    for ep in range(n_episodes):\n"
    "        # Random agent starting positions\n"
    "        start_pos = []\n"
    "        used = set()\n"
    "        for i in range(n_agents):\n"
    "            while True:\n"
    "                p = (np.random.randint(size), np.random.randint(size))\n"
    "                if p not in used:\n"
    "                    used.add(p)\n"
    "                    start_pos.append(p)\n"
    "                    break\n"
    "\n"
    "        agent_pos = list(start_pos)\n"
    "        targets_collected = set()\n"
    "        episode_collections = [None] * n_agents\n"
    "\n"
    "        for step in range(50):\n"
    "            if len(targets_collected) == n_targets:\n"
    "                break\n"
    "\n"
    "            for i in range(n_agents):\n"
    "                if episode_collections[i] is not None:\n"
    "                    continue  # agent already collected its target\n"
    "\n"
    "                # Nearest uncollected target\n"
    "                r_pos, c_pos = agent_pos[i]\n"
    "                best_t = -1\n"
    "                best_dist = 999\n"
    "                for t_idx, (tr, tc) in enumerate(targets):\n"
    "                    if t_idx not in targets_collected:\n"
    "                        d = abs(r_pos - tr) + abs(c_pos - tc)\n"
    "                        if d < best_dist:\n"
    "                            best_dist = d\n"
    "                            best_t = t_idx\n"
    "\n"
    "                if best_t == -1:\n"
    "                    continue\n"
    "\n"
    "                s = r_pos * size + c_pos\n"
    "                a = (np.random.randint(n_actions) if np.random.random() < eps\n"
    "                     else np.argmax(Q_all[i][s, best_t]))\n"
    "                new_pos = move(agent_pos[i], a)\n"
    "                s2 = new_pos[0] * size + new_pos[1]\n"
    "\n"
    "                # Check collection\n"
    "                if new_pos == targets[best_t] and best_t not in targets_collected:\n"
    "                    r_val = 1.0\n"
    "                    targets_collected.add(best_t)\n"
    "                    episode_collections[i] = best_t\n"
    "                else:\n"
    "                    r_val = -0.01\n"
    "\n"
    "                Q_all[i][s, best_t, a] += alpha * (\n"
    "                    r_val + gamma * np.max(Q_all[i][s2, best_t]) - Q_all[i][s, best_t, a]\n"
    "                )\n"
    "                agent_pos[i] = new_pos\n"
    "\n"
    "        collection_history.append(len(targets_collected))\n"
    "        for i in range(n_agents):\n"
    "            if episode_collections[i] is not None:\n"
    "                specialization_history[i].append(episode_collections[i])\n"
    "\n"
    "    return collection_history, specialization_history\n"
    "\n"
    "\n"
    "np.random.seed(42)\n"
    "print('Running cooperative specialization (N=4 agents, 4 targets)...')\n"
    "coll_hist, spec_hist = run_specialization(n_agents=4, size=8, n_episodes=600)\n"
    "print(f'Final 100-ep mean targets collected: {np.mean(coll_hist[-100:]):.2f} / 4')\n"
    "\n"
    "# Analyze specialization: which targets does each agent prefer?\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "\n"
    "window = 30\n"
    "coll_ma = np.convolve(coll_hist, np.ones(window)/window, mode='valid')\n"
    "axes[0].plot(coll_ma, color='#2c7bb6', linewidth=2)\n"
    "axes[0].axhline(y=4, color='#1a9641', linestyle='--', label='Max (4 targets)')\n"
    "axes[0].set_xlabel('Episode', fontsize=12)\n"
    "axes[0].set_ylabel('Targets Collected per Episode', fontsize=12)\n"
    "axes[0].set_title('Cooperative Collection: Learning Curve', fontsize=12)\n"
    "axes[0].legend()\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "# Specialization heatmap: agent x target preference\n"
    "spec_matrix = np.zeros((4, 4))\n"
    "for i, hist in enumerate(spec_hist):\n"
    "    if hist:\n"
    "        last_half = hist[len(hist)//2:]\n"
    "        for t in last_half:\n"
    "            spec_matrix[i, t] += 1\n"
    "        if spec_matrix[i].sum() > 0:\n"
    "            spec_matrix[i] /= spec_matrix[i].sum()\n"
    "\n"
    "im = axes[1].imshow(spec_matrix, cmap='Blues', vmin=0, vmax=1)\n"
    "plt.colorbar(im, ax=axes[1])\n"
    "axes[1].set_xticks([0,1,2,3])\n"
    "axes[1].set_xticklabels(['Target 0\\n(1,1)', 'Target 1\\n(1,6)',\n"
    "                          'Target 2\\n(6,1)', 'Target 3\\n(6,6)'], fontsize=9)\n"
    "axes[1].set_yticks([0,1,2,3])\n"
    "axes[1].set_yticklabels([f'Agent {i}' for i in range(4)])\n"
    "axes[1].set_title('Emergent Specialization\\n(late training target preferences)', fontsize=11)\n"
    "for i in range(4):\n"
    "    for j in range(4):\n"
    "        axes[1].text(j, i, f'{spec_matrix[i,j]:.2f}',\n"
    "                     ha='center', va='center', fontsize=10,\n"
    "                     color='white' if spec_matrix[i,j] > 0.5 else 'black')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/marl_specialization.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c13 = md(
    "## Comparison: Independent Q-learning vs CTDE vs Self-Play\n\n"
    "Performance on cooperative (pursuit) and competitive (adversarial) tasks.\n"
)

c14 = code(
    "# Run CTDE-style cooperative Q (joint Q over agent pair actions)\n"
    "def run_ctde_pursuit(n_episodes=800, alpha=0.1, gamma=0.9, eps=0.2, size=4):\n"
    "    # Simplified 4x4 pursuit: joint state = (a1, a2, target) positions\n"
    "    # Centralized Q: Q(joint_state, a1, a2) -> scalar\n"
    "    n_actions = 4\n"
    "    deltas = [(-1,0),(1,0),(0,-1),(0,1)]\n"
    "\n"
    "    def move(pos, action):\n"
    "        r, c = pos\n"
    "        dr, dc = deltas[action]\n"
    "        return (max(0, min(size-1, r+dr)), max(0, min(size-1, c+dc)))\n"
    "\n"
    "    def to_jstate(p1, p2, target):\n"
    "        return (p1[0]*size**5 + p1[1]*size**4 +\n"
    "                p2[0]*size**3 + p2[1]*size**2 +\n"
    "                target[0]*size + target[1])\n"
    "\n"
    "    n_joint_states = size**6\n"
    "    n_joint_actions = n_actions ** 2\n"
    "    # Use dict for Q to save memory (most states unvisited)\n"
    "    Q_joint = {}\n"
    "    catch_rates = []\n"
    "\n"
    "    for ep in range(n_episodes):\n"
    "        positions = np.random.choice(size**2, size=3, replace=False)\n"
    "        p1 = (positions[0]//size, positions[0]%size)\n"
    "        p2 = (positions[1]//size, positions[1]%size)\n"
    "        target = (positions[2]//size, positions[2]%size)\n"
    "        done = False\n"
    "\n"
    "        for step in range(40):\n"
    "            js = to_jstate(p1, p2, target)\n"
    "            if js not in Q_joint:\n"
    "                Q_joint[js] = np.zeros(n_joint_actions)\n"
    "\n"
    "            if np.random.random() < eps:\n"
    "                ja = np.random.randint(n_joint_actions)\n"
    "            else:\n"
    "                ja = np.argmax(Q_joint[js])\n"
    "\n"
    "            a1 = ja // n_actions\n"
    "            a2 = ja % n_actions\n"
    "\n"
    "            p1_new = move(p1, a1)\n"
    "            p2_new = move(p2, a2)\n"
    "            # Target moves randomly\n"
    "            target = move(target, np.random.randint(n_actions))\n"
    "\n"
    "            d1 = abs(p1_new[0]-target[0]) + abs(p1_new[1]-target[1])\n"
    "            d2 = abs(p2_new[0]-target[0]) + abs(p2_new[1]-target[1])\n"
    "            caught = (d1 <= 1) or (d2 <= 1)\n"
    "            both_close = (d1 <= 2) and (d2 <= 2)\n"
    "            r = 1.0 if caught else (0.2 if both_close else -0.01)\n"
    "\n"
    "            js2 = to_jstate(p1_new, p2_new, target)\n"
    "            if js2 not in Q_joint:\n"
    "                Q_joint[js2] = np.zeros(n_joint_actions)\n"
    "\n"
    "            Q_joint[js][ja] += alpha * (r + gamma * np.max(Q_joint[js2]) - Q_joint[js][ja])\n"
    "            p1, p2 = p1_new, p2_new\n"
    "            if caught:\n"
    "                done = True\n"
    "                break\n"
    "\n"
    "        catch_rates.append(1.0 if done else 0.0)\n"
    "\n"
    "    return catch_rates\n"
    "\n"
    "\n"
    "print('Training CTDE joint Q-learning on pursuit (4x4)...')\n"
    "np.random.seed(42)\n"
    "rates_ctde = run_ctde_pursuit(n_episodes=800)\n"
    "\n"
    "# Also re-run independent QL on same smaller grid\n"
    "print('Training independent Q-learning on pursuit (4x4)...')\n"
    "np.random.seed(42)\n"
    "_, _, rates_ind_small = run_independent_ql(n_episodes=800, size=4)\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
    "window = 50\n"
    "c_ctde = np.convolve(rates_ctde, np.ones(window)/window, mode='valid')\n"
    "c_ind = np.convolve(rates_ind_small, np.ones(window)/window, mode='valid')\n"
    "\n"
    "ax = axes[0]\n"
    "ep_range = np.arange(len(c_ctde))\n"
    "ax.plot(ep_range, c_ctde, color='#d7191c', label='CTDE (joint Q)', linewidth=2)\n"
    "ax.plot(ep_range, c_ind[:len(c_ctde)], color='#2c7bb6',\n"
    "        label='Independent Q-learning', linewidth=2)\n"
    "ax.set_xlabel('Episode', fontsize=12)\n"
    "ax.set_ylabel('Catch Rate', fontsize=12)\n"
    "ax.set_title('Cooperative Pursuit: CTDE vs Independent QL', fontsize=12)\n"
    "ax.legend()\n"
    "ax.set_facecolor('#f8f8f8')\n"
    "ax.grid(True, alpha=0.4)\n"
    "\n"
    "# Summary bar\n"
    "ax2 = axes[1]\n"
    "methods_bar = ['Indep. QL\\n(6x6)', 'Indep. QL\\n(4x4)', 'CTDE\\n(4x4)', 'Comm.\\nGame']\n"
    "perfs = [\n"
    "    np.mean(rates_ind[-100:]),\n"
    "    np.mean(rates_ind_small[-100:]),\n"
    "    np.mean(rates_ctde[-100:]),\n"
    "    np.mean(comm_success[-100:]),\n"
    "]\n"
    "colors_bar = ['#636363', '#2c7bb6', '#d7191c', '#fd8d3c']\n"
    "bars = ax2.bar(methods_bar, perfs, color=colors_bar, alpha=0.85, edgecolor='black')\n"
    "ax2.set_ylabel('Success Rate', fontsize=12)\n"
    "ax2.set_title('MARL Method Comparison', fontsize=12)\n"
    "ax2.set_facecolor('#f8f8f8')\n"
    "ax2.grid(True, alpha=0.4, axis='y')\n"
    "for bar, val in zip(bars, perfs):\n"
    "    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,\n"
    "             f'{val:.2f}', ha='center', va='bottom', fontsize=11, fontweight='bold')\n"
    "\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/marl_comparison.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c15 = md(
    "## Key Takeaways\n\n"
    "**Core idea:** Multi-agent RL requires agents to coordinate or compete while each agent's "
    "policy changes make the environment non-stationary for all others. CTDE handles this by "
    "using centralized critics during training while keeping execution decentralized.\n\n"
    "**Variants and when to use:**\n\n"
    "| Method | Non-stationarity | Scales to N agents | Use when |\n"
    "|--------|-----------------|-------------------|----------|\n"
    "| Independent QL | Ignored | Yes | Simple cooperative, large N |\n"
    "| CTDE (MADDPG/QMIX) | Handled | ~10 agents | Cooperative, moderate N |\n"
    "| Self-play | Symmetric | Yes | Competitive/symmetric |\n"
    "| Communication | Explicit | ~20 agents | Partial observability |\n\n"
    "**Common failure modes:**\n"
    "- Independent QL cycles in competitive games (non-stationarity)\n"
    "- CTDE centralized Q exponential growth with N (O(A^N) joint actions)\n"
    "- Reward shaping credit: agents claim shared reward for others' work\n"
)

c16 = md(
    "## Exercises\n\n"
    "1. **Prisoner's Dilemma with communication**: Add a 1-bit message before each round. "
    "Can agents learn to cooperate better than Nash equilibrium?\n"
    "2. **CTDE scaling**: Run `run_ctde_pursuit` on 5x5 grid. "
    "How does joint Q table size scale? At what N does memory become an issue?\n"
    "3. **RPS and Nash**: In `run_rps`, verify the learned strategy approaches "
    "the Nash (1/3,1/3,1/3). Try different alpha values.\n"
    "4. **Specialization emergence**: In `run_specialization`, fix agents to always "
    "go to their nearest target (hardcoded). Does emergent specialization still occur?\n"
)

nb.cells = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16]
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.8.0"}
}

out = '/home/sbisw/github/interviewprep-ml/rl/notebooks/19-multi-agent-rl.ipynb'
nbformat.write(nb, out)
print(f"Written: {out}")
print(f"Cells: {len(nb.cells)}")
code_lines = sum(
    len(''.join(c['source']).split('\n'))
    for c in nb.cells if c['cell_type'] == 'code'
)
print(f"Code lines: {code_lines}")
