"""Generator for notebook 17: RLHF (torch-based, per task spec)"""
import nbformat

def md(text):
    return nbformat.v4.new_markdown_cell(text)

def code(text):
    return nbformat.v4.new_code_cell(text)

nb = nbformat.v4.new_notebook()

c1 = md(
    "# 17 - RLHF (Reinforcement Learning from Human Feedback)\n\n"
    "## Learning Objectives\n"
    "1. Implement Bradley-Terry preference model from scratch\n"
    "2. Train a reward model on pairwise comparisons\n"
    "3. Implement PPO fine-tuning with KL penalty on a toy language model\n"
    "4. Demonstrate reward hacking and KL penalty defense\n"
)

c2 = code(
    "import numpy as np\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "import torch.optim as optim\n"
    "import matplotlib\n"
    "matplotlib.use('Agg')\n"
    "import matplotlib.pyplot as plt\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "np.random.seed(42)\n"
    "torch.manual_seed(42)\n"
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
    "print(f'Using device: {device}')\n"
    "print(f'NumPy: {np.__version__}, PyTorch: {torch.__version__}')\n"
    "print('RLHF demo: Bradley-Terry + toy PPO + KL penalty + DPO')\n"
)

c3 = md(
    "## Level 1: Bradley-Terry Preference Model\n\n"
    "Items have true quality scores q_i. P(i beats j) = sigma(q_i - q_j).\n"
    "Train Bradley-Terry model to recover q from pairwise comparisons.\n"
    "Loss = -E[log sigma(q_winner - q_loser)]\n"
)

c4 = code(
    "# Bradley-Terry: learn item quality from pairwise outcomes\n"
    "N_ITEMS = 10\n"
    "np.random.seed(42)\n"
    "torch.manual_seed(42)\n"
    "true_quality = np.random.randn(N_ITEMS)  # ground truth scores\n"
    "\n"
    "\n"
    "def sigmoid_np(x):\n"
    "    return 1.0 / (1.0 + np.exp(-np.clip(x, -20, 20)))\n"
    "\n"
    "\n"
    "def generate_comparisons(quality, n=300):\n"
    "    \"\"\"Generate pairwise comparisons: (winner_idx, loser_idx).\n"
    "    P(i beats j) = sigmoid(quality[i] - quality[j]).\n"
    "    \"\"\"\n"
    "    pairs = []\n"
    "    for _ in range(n):\n"
    "        i, j = np.random.choice(len(quality), 2, replace=False)\n"
    "        prob_i_wins = sigmoid_np(quality[i] - quality[j])\n"
    "        if np.random.random() < prob_i_wins:\n"
    "            pairs.append((i, j))  # i wins\n"
    "        else:\n"
    "            pairs.append((j, i))  # j wins\n"
    "    return pairs\n"
    "\n"
    "\n"
    "comparisons = generate_comparisons(true_quality, n=400)\n"
    "\n"
    "# Train Bradley-Terry model with torch\n"
    "# q_est: learnable quality vector, shape (N_ITEMS,)\n"
    "q_est = torch.zeros(N_ITEMS, requires_grad=True, device=device)\n"
    "optimizer = torch.optim.Adam([q_est], lr=0.1)\n"
    "\n"
    "losses = []\n"
    "for epoch in range(300):\n"
    "    total_loss = torch.tensor(0.0, device=device)\n"
    "    for winner, loser in comparisons:\n"
    "        # P(winner beats loser) = sigma(q_winner - q_loser)\n"
    "        diff = q_est[winner] - q_est[loser]\n"
    "        # Negative log likelihood\n"
    "        total_loss = total_loss + (-torch.log(torch.sigmoid(diff) + 1e-9))\n"
    "    total_loss = total_loss / len(comparisons)\n"
    "    optimizer.zero_grad()\n"
    "    total_loss.backward()\n"
    "    optimizer.step()\n"
    "    losses.append(total_loss.item())\n"
    "\n"
    "q_final = q_est.detach().cpu().numpy()\n"
    "q_final -= q_final.mean()  # center for identifiability\n"
    "correlation = np.corrcoef(true_quality, q_final)[0, 1]\n"
    "print(f'Bradley-Terry Results:')\n"
    "print(f'  True-learned correlation: {correlation:.4f}')\n"
    "print(f'  Final NLL: {losses[-1]:.4f}')\n"
    "\n"
    "# Visualize\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
    "axes[0].plot(losses, color='#2c7bb6', linewidth=2)\n"
    "axes[0].set_xlabel('Epoch', fontsize=12)\n"
    "axes[0].set_ylabel('Negative Log-Likelihood', fontsize=12)\n"
    "axes[0].set_title('Bradley-Terry Training Loss', fontsize=12)\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "axes[1].scatter(true_quality, q_final, color='#d7191c', s=80, alpha=0.8,\n"
    "                edgecolors='black', linewidths=0.5)\n"
    "m, b = np.polyfit(true_quality, q_final, 1)\n"
    "xline = np.linspace(true_quality.min(), true_quality.max(), 100)\n"
    "axes[1].plot(xline, m * xline + b, 'k--', alpha=0.5,\n"
    "             label=f'fit (r={correlation:.2f})')\n"
    "axes[1].set_xlabel('True Quality', fontsize=12)\n"
    "axes[1].set_ylabel('Learned BT Score', fontsize=12)\n"
    "axes[1].set_title('True vs Learned Reward Model', fontsize=12)\n"
    "axes[1].legend()\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_bt.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Bradley-Terry plot saved.')\n"
)

c5 = md(
    "## Level 2: Full RLHF Pipeline (Toy Language Model)\n\n"
    "Toy setup: 8-token vocab, max length 6. 'Good' responses have high sum of quality tokens.\n"
    "Stage 1: Train reward model on pairwise preferences.\n"
    "Stage 2: PPO fine-tuning with KL penalty to prevent reward hacking.\n"
    "Demonstrate that small beta causes reward hacking (RM score rises, KL explodes).\n"
)

c6 = code(
    "# Toy LM: 8-token vocab, sequence length 6\n"
    "VOCAB_SIZE = 8\n"
    "SEQ_LEN = 6\n"
    "GOOD_TOKENS = {5, 6, 7}  # high-quality tokens\n"
    "\n"
    "\n"
    "class ToyLM(nn.Module):\n"
    "    \"\"\"Minimal autoregressive LM: next-token logits from one-hot current token.\"\"\"\n"
    "    def __init__(self, vocab_size: int = 8, hidden: int = 32):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(\n"
    "            nn.Linear(vocab_size, hidden),\n"
    "            nn.ReLU(),\n"
    "            nn.Linear(hidden, vocab_size),\n"
    "        )\n"
    "\n"
    "    def forward(self, x_onehot: torch.Tensor) -> torch.Tensor:\n"
    "        return self.net(x_onehot)  # shape: (batch, vocab_size)\n"
    "\n"
    "\n"
    "class RewardModel(nn.Module):\n"
    "    \"\"\"Reward model: takes flattened sequence one-hot, outputs scalar reward.\"\"\"\n"
    "    def __init__(self, vocab_size: int = 8, seq_len: int = 6, hidden: int = 32):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(\n"
    "            nn.Linear(vocab_size * seq_len, hidden),\n"
    "            nn.ReLU(),\n"
    "            nn.Linear(hidden, 1),\n"
    "        )\n"
    "\n"
    "    def forward(self, seq_onehot: torch.Tensor) -> torch.Tensor:\n"
    "        \"\"\"seq_onehot: (batch, seq_len * vocab_size)\"\"\"\n"
    "        return self.net(seq_onehot).squeeze(-1)  # (batch,)\n"
    "\n"
    "\n"
    "def sample_sequence(\n"
    "    lm: ToyLM,\n"
    "    vocab_size: int = VOCAB_SIZE,\n"
    "    seq_len: int = SEQ_LEN,\n"
    "    temperature: float = 1.0,\n"
    ") -> list:\n"
    "    \"\"\"Sample a token sequence from the LM.\"\"\"\n"
    "    seq = []\n"
    "    x = torch.zeros(1, vocab_size, device=device)\n"
    "    x[0, 0] = 1.0  # BOS token\n"
    "    for _ in range(seq_len):\n"
    "        with torch.no_grad():\n"
    "            logits = lm(x) / temperature\n"
    "        probs = torch.softmax(logits, dim=-1)\n"
    "        token = torch.multinomial(probs, 1).item()\n"
    "        seq.append(token)\n"
    "        x = torch.zeros(1, vocab_size, device=device)\n"
    "        x[0, token] = 1.0\n"
    "    return seq\n"
    "\n"
    "\n"
    "def true_reward(seq: list) -> float:\n"
    "    \"\"\"Oracle quality: proportion of good tokens in sequence.\"\"\"\n"
    "    return sum(t in GOOD_TOKENS for t in seq) / len(seq)\n"
    "\n"
    "\n"
    "def seq_to_onehot(seq: list, vocab_size: int = VOCAB_SIZE,\n"
    "                  seq_len: int = SEQ_LEN) -> torch.Tensor:\n"
    "    \"\"\"Convert token list to flattened one-hot tensor.\"\"\"\n"
    "    x = torch.zeros(seq_len * vocab_size, device=device)\n"
    "    for i, t in enumerate(seq):\n"
    "        x[i * vocab_size + t] = 1.0\n"
    "    return x\n"
    "\n"
    "\n"
    "# ---- Stage 1: Train Reward Model from pairwise preferences ----\n"
    "torch.manual_seed(42)\n"
    "policy = ToyLM().to(device)\n"
    "ref_policy = ToyLM().to(device)\n"
    "# Copy policy weights to reference (frozen)\n"
    "ref_policy.load_state_dict(policy.state_dict())\n"
    "for p in ref_policy.parameters():\n"
    "    p.requires_grad_(False)\n"
    "\n"
    "rm = RewardModel().to(device)\n"
    "rm_optimizer = torch.optim.Adam(rm.parameters(), lr=1e-3)\n"
    "\n"
    "# Generate preference pairs from initial policy\n"
    "pref_data = []\n"
    "with torch.no_grad():\n"
    "    for _ in range(600):\n"
    "        seqA = sample_sequence(policy)\n"
    "        seqB = sample_sequence(policy)\n"
    "        rA, rB = true_reward(seqA), true_reward(seqB)\n"
    "        if abs(rA - rB) < 1e-6:\n"
    "            continue  # skip ties\n"
    "        if rA > rB:\n"
    "            pref_data.append((seq_to_onehot(seqA), seq_to_onehot(seqB)))\n"
    "        else:\n"
    "            pref_data.append((seq_to_onehot(seqB), seq_to_onehot(seqA)))\n"
    "\n"
    "print(f'Collected {len(pref_data)} preference pairs')\n"
    "\n"
    "# Train RM: Bradley-Terry loss\n"
    "rm_losses = []\n"
    "for epoch in range(150):\n"
    "    batch_size = min(64, len(pref_data))\n"
    "    idx = np.random.choice(len(pref_data), batch_size, replace=False)\n"
    "    batch_w = torch.stack([pref_data[i][0] for i in idx])\n"
    "    batch_l = torch.stack([pref_data[i][1] for i in idx])\n"
    "    r_w = rm(batch_w)\n"
    "    r_l = rm(batch_l)\n"
    "    loss = -torch.log(torch.sigmoid(r_w - r_l) + 1e-9).mean()\n"
    "    rm_optimizer.zero_grad()\n"
    "    loss.backward()\n"
    "    rm_optimizer.step()\n"
    "    rm_losses.append(loss.item())\n"
    "\n"
    "print(f'RM training complete. Final loss: {rm_losses[-1]:.4f}')\n"
    "\n"
    "# ---- Stage 2: PPO-style fine-tuning with KL penalty ----\n"
    "policy_opt = torch.optim.Adam(policy.parameters(), lr=1e-3)\n"
    "kl_beta = 0.1\n"
    "reward_history = []\n"
    "kl_history = []\n"
    "true_quality_history = []\n"
    "\n"
    "for step in range(200):\n"
    "    # Sample batch of sequences\n"
    "    seqs = [sample_sequence(policy) for _ in range(16)]\n"
    "\n"
    "    # RM rewards (no grad through RM)\n"
    "    with torch.no_grad():\n"
    "        rm_rewards = torch.stack(\n"
    "            [rm(seq_to_onehot(s).unsqueeze(0)).squeeze() for s in seqs]\n"
    "        )\n"
    "\n"
    "    # REINFORCE with KL penalty\n"
    "    policy_opt.zero_grad()\n"
    "    total_loss = torch.tensor(0.0, device=device)\n"
    "\n"
    "    for seq in seqs:\n"
    "        x = torch.zeros(1, VOCAB_SIZE, device=device)\n"
    "        x[0, 0] = 1.0  # BOS\n"
    "        log_probs = []\n"
    "        ref_log_probs = []\n"
    "        for token in seq:\n"
    "            logits = policy(x)\n"
    "            with torch.no_grad():\n"
    "                ref_logits = ref_policy(x)\n"
    "            lp = torch.log_softmax(logits, dim=-1)[0, token]\n"
    "            ref_lp = torch.log_softmax(ref_logits, dim=-1)[0, token]\n"
    "            log_probs.append(lp)\n"
    "            ref_log_probs.append(ref_lp)\n"
    "            x = torch.zeros(1, VOCAB_SIZE, device=device)\n"
    "            x[0, token] = 1.0\n"
    "\n"
    "        log_prob = sum(log_probs)\n"
    "        ref_log_prob = sum(ref_log_probs).detach()\n"
    "        kl = log_prob - ref_log_prob  # KL approx per sequence\n"
    "\n"
    "        with torch.no_grad():\n"
    "            r_rm = rm(seq_to_onehot(seq).unsqueeze(0)).squeeze()\n"
    "        # PPO objective: maximize (reward - beta * KL)\n"
    "        total_loss = total_loss + (-(r_rm - kl_beta * kl) * log_prob)\n"
    "\n"
    "    (total_loss / len(seqs)).backward()\n"
    "    torch.nn.utils.clip_grad_norm_(policy.parameters(), 1.0)\n"
    "    policy_opt.step()\n"
    "\n"
    "    # Track metrics\n"
    "    with torch.no_grad():\n"
    "        avg_rm_reward = rm_rewards.mean().item()\n"
    "    avg_true_quality = np.mean([true_reward(s) for s in seqs])\n"
    "    reward_history.append(avg_rm_reward)\n"
    "    true_quality_history.append(avg_true_quality)\n"
    "\n"
    "print(f'PPO (beta=0.1) - Final RM reward: {np.mean(reward_history[-20:]):.4f}')\n"
    "print(f'PPO (beta=0.1) - Final true quality: {np.mean(true_quality_history[-20:]):.4f}')\n"
)

c7 = md(
    "## Real-World Example 1: Reward Model Calibration\n\n"
    "Evaluate reward model calibration: scatter plot of true_reward vs rm_reward for 100 samples.\n"
    "Compute Pearson correlation between RM score and oracle quality.\n"
    "A well-calibrated RM aligns with true quality; miscalibration leads to reward hacking.\n"
)

c8 = code(
    "# Reward model calibration: RM score vs oracle quality\n"
    "np.random.seed(42)\n"
    "torch.manual_seed(42)\n"
    "eval_seqs = [sample_sequence(policy) for _ in range(100)]\n"
    "\n"
    "oracle_rewards = np.array([true_reward(s) for s in eval_seqs])\n"
    "with torch.no_grad():\n"
    "    rm_scores = np.array([\n"
    "        rm(seq_to_onehot(s).unsqueeze(0)).squeeze().item()\n"
    "        for s in eval_seqs\n"
    "    ])\n"
    "\n"
    "pearson_r = np.corrcoef(oracle_rewards, rm_scores)[0, 1]\n"
    "\n"
    "# Brier-style calibration: normalize RM scores to [0,1] and compare to oracle\n"
    "rm_min, rm_max = rm_scores.min(), rm_scores.max()\n"
    "if rm_max - rm_min > 1e-6:\n"
    "    rm_normalized = (rm_scores - rm_min) / (rm_max - rm_min)\n"
    "else:\n"
    "    rm_normalized = np.full_like(rm_scores, 0.5)\n"
    "brier_approx = np.mean((rm_normalized - oracle_rewards) ** 2)\n"
    "\n"
    "print(f'RM Calibration Results:')\n"
    "print(f'  Pearson correlation (RM vs oracle): {pearson_r:.4f}')\n"
    "print(f'  Brier-like MSE: {brier_approx:.4f}')\n"
    "\n"
    "# Sample efficiency: correlation vs number of pref pairs\n"
    "n_pairs_list = [50, 100, 200, 400, 600]\n"
    "corr_by_n = []\n"
    "torch.manual_seed(99)\n"
    "for n_pairs in n_pairs_list:\n"
    "    rm_cal = RewardModel().to(device)\n"
    "    opt_cal = torch.optim.Adam(rm_cal.parameters(), lr=1e-3)\n"
    "    subset = pref_data[:n_pairs] if n_pairs <= len(pref_data) else pref_data\n"
    "    for _ in range(80):\n"
    "        idx_c = np.random.choice(len(subset), min(32, len(subset)), replace=False)\n"
    "        bw = torch.stack([subset[i][0] for i in idx_c])\n"
    "        bl = torch.stack([subset[i][1] for i in idx_c])\n"
    "        loss_c = -torch.log(torch.sigmoid(rm_cal(bw) - rm_cal(bl)) + 1e-9).mean()\n"
    "        opt_cal.zero_grad(); loss_c.backward(); opt_cal.step()\n"
    "    with torch.no_grad():\n"
    "        sc = np.array([rm_cal(seq_to_onehot(s).unsqueeze(0)).squeeze().item()\n"
    "                       for s in eval_seqs])\n"
    "    corr_by_n.append(np.corrcoef(oracle_rewards, sc)[0, 1])\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "\n"
    "axes[0].scatter(oracle_rewards, rm_scores, alpha=0.7, color='#d7191c',\n"
    "                s=60, edgecolors='black', linewidths=0.4)\n"
    "m, b = np.polyfit(oracle_rewards, rm_scores, 1)\n"
    "xline = np.linspace(oracle_rewards.min(), oracle_rewards.max(), 100)\n"
    "axes[0].plot(xline, m * xline + b, 'k--', alpha=0.6,\n"
    "             label=f'r={pearson_r:.2f}')\n"
    "axes[0].set_xlabel('Oracle True Quality', fontsize=12)\n"
    "axes[0].set_ylabel('RM Score', fontsize=12)\n"
    "axes[0].set_title('Reward Model Calibration\\n(RM score vs oracle)', fontsize=11)\n"
    "axes[0].legend()\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "axes[1].plot(n_pairs_list, corr_by_n, 'o-', color='#2c7bb6',\n"
    "             linewidth=2, markersize=8)\n"
    "axes[1].axhline(y=0.7, color='#d7191c', linestyle='--',\n"
    "                label='Good calibration threshold (r=0.7)')\n"
    "axes[1].set_xlabel('Training Preference Pairs', fontsize=12)\n"
    "axes[1].set_ylabel('Pearson r (RM vs oracle)', fontsize=12)\n"
    "axes[1].set_title('RM Quality vs Training Data Size', fontsize=12)\n"
    "axes[1].legend()\n"
    "axes[1].set_facecolor('#f8f8f8')\n"
    "axes[1].grid(True, alpha=0.4)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_calibration.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "print(f'Best correlation: {max(corr_by_n):.4f} at {n_pairs_list[np.argmax(corr_by_n)]} pairs')\n"
)

c9 = md(
    "## Real-World Example 2: KL Penalty Sweep\n\n"
    "Train with beta in {0.01, 0.1, 1.0}.\n"
    "Plot: RM reward (y) vs KL-divergence from reference (x) for each beta.\n"
    "Small beta: high reward but high KL (reward hacking). Large beta: stable but conservative.\n"
    "This is the fundamental reward-safety tradeoff in RLHF.\n"
)

c10 = code(
    "def run_ppo_with_beta(\n"
    "    beta: float,\n"
    "    n_steps: int = 150,\n"
    "    batch_size: int = 16,\n"
    ") -> tuple:\n"
    "    \"\"\"Run PPO fine-tuning with a given KL penalty beta.\n"
    "    Returns (rm_reward_history, kl_history, true_quality_history).\n"
    "    \"\"\"\n"
    "    torch.manual_seed(42)\n"
    "    pol = ToyLM().to(device)\n"
    "    ref = ToyLM().to(device)\n"
    "    ref.load_state_dict(pol.state_dict())\n"
    "    for p in ref.parameters():\n"
    "        p.requires_grad_(False)\n"
    "    opt = torch.optim.Adam(pol.parameters(), lr=1e-3)\n"
    "\n"
    "    rm_hist, kl_hist, tq_hist = [], [], []\n"
    "\n"
    "    for step in range(n_steps):\n"
    "        seqs = [sample_sequence(pol) for _ in range(batch_size)]\n"
    "        opt.zero_grad()\n"
    "        total_loss = torch.tensor(0.0, device=device)\n"
    "        step_kls = []\n"
    "\n"
    "        for seq in seqs:\n"
    "            x = torch.zeros(1, VOCAB_SIZE, device=device)\n"
    "            x[0, 0] = 1.0\n"
    "            log_probs = []\n"
    "            ref_log_probs = []\n"
    "            for token in seq:\n"
    "                logits = pol(x)\n"
    "                with torch.no_grad():\n"
    "                    ref_logits = ref(x)\n"
    "                lp = torch.log_softmax(logits, dim=-1)[0, token]\n"
    "                ref_lp = torch.log_softmax(ref_logits, dim=-1)[0, token]\n"
    "                log_probs.append(lp)\n"
    "                ref_log_probs.append(ref_lp)\n"
    "                x = torch.zeros(1, VOCAB_SIZE, device=device)\n"
    "                x[0, token] = 1.0\n"
    "\n"
    "            log_prob = sum(log_probs)\n"
    "            ref_log_prob = sum(ref_log_probs).detach()\n"
    "            kl_val = (log_prob - ref_log_prob).item()\n"
    "            step_kls.append(abs(kl_val))\n"
    "\n"
    "            with torch.no_grad():\n"
    "                r_rm = rm(seq_to_onehot(seq).unsqueeze(0)).squeeze()\n"
    "            total_loss = total_loss + (-(r_rm - beta * (log_prob - ref_log_prob)))\n"
    "\n"
    "        (total_loss / len(seqs)).backward()\n"
    "        torch.nn.utils.clip_grad_norm_(pol.parameters(), 1.0)\n"
    "        opt.step()\n"
    "\n"
    "        with torch.no_grad():\n"
    "            rm_scores_step = [\n"
    "                rm(seq_to_onehot(s).unsqueeze(0)).squeeze().item() for s in seqs\n"
    "            ]\n"
    "        rm_hist.append(np.mean(rm_scores_step))\n"
    "        kl_hist.append(np.mean(step_kls))\n"
    "        tq_hist.append(np.mean([true_reward(s) for s in seqs]))\n"
    "\n"
    "    return rm_hist, kl_hist, tq_hist\n"
    "\n"
    "\n"
    "betas = [0.01, 0.1, 1.0]\n"
    "beta_results = {}\n"
    "\n"
    "for beta in betas:\n"
    "    print(f'Running PPO with beta={beta}...')\n"
    "    rm_h, kl_h, tq_h = run_ppo_with_beta(beta, n_steps=150)\n"
    "    beta_results[beta] = {\n"
    "        'rm_final': float(np.mean(rm_h[-30:])),\n"
    "        'kl_final': float(np.mean(kl_h[-30:])),\n"
    "        'tq_final': float(np.mean(tq_h[-30:])),\n"
    "        'rm_hist': rm_h,\n"
    "        'kl_hist': kl_h,\n"
    "    }\n"
    "    print(f'  beta={beta}: RM={beta_results[beta][\"rm_final\"]:.3f}, '\n"
    "          f'KL={beta_results[beta][\"kl_final\"]:.3f}, '\n"
    "          f'TrueQ={beta_results[beta][\"tq_final\"]:.3f}')\n"
    "\n"
    "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n"
    "colors_beta = ['#d7191c', '#2c7bb6', '#1a9641']\n"
    "\n"
    "for beta, color in zip(betas, colors_beta):\n"
    "    r = beta_results[beta]\n"
    "    axes[0].plot(r['rm_hist'], color=color, label=f'beta={beta}', linewidth=1.5)\n"
    "    axes[1].plot(r['kl_hist'], color=color, label=f'beta={beta}', linewidth=1.5)\n"
    "\n"
    "axes[0].set_title('RM Reward over Training', fontsize=12)\n"
    "axes[0].set_xlabel('Step'); axes[0].set_ylabel('RM Reward')\n"
    "axes[0].legend(); axes[0].set_facecolor('#f8f8f8'); axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "axes[1].set_title('KL Divergence over Training', fontsize=12)\n"
    "axes[1].set_xlabel('Step'); axes[1].set_ylabel('KL(pi || pi_ref)')\n"
    "axes[1].legend(); axes[1].set_facecolor('#f8f8f8'); axes[1].grid(True, alpha=0.4)\n"
    "\n"
    "# Pareto: RM reward vs KL divergence (lower-right is ideal)\n"
    "rm_finals = [beta_results[b]['rm_final'] for b in betas]\n"
    "kl_finals = [beta_results[b]['kl_final'] for b in betas]\n"
    "sc = axes[2].scatter(kl_finals, rm_finals, c=betas, cmap='RdYlGn_r',\n"
    "                     s=150, edgecolors='black', linewidths=0.8, zorder=5)\n"
    "for beta, kl, rm_val in zip(betas, kl_finals, rm_finals):\n"
    "    axes[2].annotate(f'b={beta}', (kl, rm_val),\n"
    "                     textcoords='offset points', xytext=(5, 5), fontsize=10)\n"
    "axes[2].set_xlabel('Final KL Divergence', fontsize=12)\n"
    "axes[2].set_ylabel('Final RM Reward', fontsize=12)\n"
    "axes[2].set_title('Reward-KL Pareto Frontier', fontsize=12)\n"
    "plt.colorbar(sc, ax=axes[2], label='beta')\n"
    "axes[2].set_facecolor('#f8f8f8'); axes[2].grid(True, alpha=0.4)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_kl_sweep.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c11 = md(
    "## Real-World Example 3: DPO Alternative\n\n"
    "Direct Preference Optimization (DPO) bypasses PPO entirely.\n"
    "DPO loss: -log sigma(beta * (log pi(y_w|x)/pi_ref(y_w|x) - log pi(y_l|x)/pi_ref(y_l|x)))\n"
    "No reward model needed. One supervised pass over preference data.\n"
    "Compare: RLHF requires RM training + PPO; DPO needs only one supervised stage.\n"
)

c12 = code(
    "def compute_seq_log_prob(\n"
    "    model: ToyLM, seq: list, vocab_size: int = VOCAB_SIZE\n"
    ") -> torch.Tensor:\n"
    "    \"\"\"Compute sum of log probs for a token sequence under model.\"\"\"\n"
    "    x = torch.zeros(1, vocab_size, device=device)\n"
    "    x[0, 0] = 1.0  # BOS\n"
    "    log_prob = torch.tensor(0.0, device=device)\n"
    "    for token in seq:\n"
    "        logits = model(x)\n"
    "        lp = torch.log_softmax(logits, dim=-1)[0, token]\n"
    "        log_prob = log_prob + lp\n"
    "        x = torch.zeros(1, vocab_size, device=device)\n"
    "        x[0, token] = 1.0\n"
    "    return log_prob\n"
    "\n"
    "\n"
    "def run_dpo(\n"
    "    pref_pairs: list,  # list of (winner_onehot, loser_onehot)\n"
    "    n_epochs: int = 80,\n"
    "    lr: float = 1e-3,\n"
    "    beta: float = 0.1,\n"
    ") -> tuple:\n"
    "    \"\"\"DPO training on preference data.\n"
    "    DPO loss = -log sigma(beta * [log pi(y_w)/pi_ref(y_w) - log pi(y_l)/pi_ref(y_l)])\n"
    "    Returns (dpo_policy, losses, tq_history).\n"
    "    \"\"\"\n"
    "    torch.manual_seed(42)\n"
    "    dpo_policy = ToyLM().to(device)\n"
    "    dpo_ref = ToyLM().to(device)\n"
    "    dpo_ref.load_state_dict(dpo_policy.state_dict())\n"
    "    for p in dpo_ref.parameters():\n"
    "        p.requires_grad_(False)\n"
    "    dpo_opt = torch.optim.Adam(dpo_policy.parameters(), lr=lr)\n"
    "\n"
    "    # Reconstruct token sequences from one-hot tensors for log prob computation\n"
    "    def onehot_to_seq(oh: torch.Tensor) -> list:\n"
    "        oh_np = oh.cpu().numpy()\n"
    "        seq = []\n"
    "        for i in range(SEQ_LEN):\n"
    "            seg = oh_np[i * VOCAB_SIZE:(i + 1) * VOCAB_SIZE]\n"
    "            tok = int(np.argmax(seg))\n"
    "            seq.append(tok)\n"
    "        return seq\n"
    "\n"
    "    losses_dpo = []\n"
    "    tq_history = []\n"
    "\n"
    "    for epoch in range(n_epochs):\n"
    "        batch_idx = np.random.choice(len(pref_pairs), min(32, len(pref_pairs)), replace=False)\n"
    "        batch_loss = torch.tensor(0.0, device=device)\n"
    "\n"
    "        for idx in batch_idx:\n"
    "            w_oh, l_oh = pref_pairs[idx]\n"
    "            seq_w = onehot_to_seq(w_oh)\n"
    "            seq_l = onehot_to_seq(l_oh)\n"
    "\n"
    "            log_pi_w = compute_seq_log_prob(dpo_policy, seq_w)\n"
    "            log_pi_l = compute_seq_log_prob(dpo_policy, seq_l)\n"
    "            with torch.no_grad():\n"
    "                log_ref_w = compute_seq_log_prob(dpo_ref, seq_w)\n"
    "                log_ref_l = compute_seq_log_prob(dpo_ref, seq_l)\n"
    "\n"
    "            # DPO implicit reward difference\n"
    "            reward_diff = beta * ((log_pi_w - log_ref_w) - (log_pi_l - log_ref_l))\n"
    "            loss = -torch.log(torch.sigmoid(reward_diff) + 1e-9)\n"
    "            batch_loss = batch_loss + loss\n"
    "\n"
    "        (batch_loss / len(batch_idx)).backward()\n"
    "        torch.nn.utils.clip_grad_norm_(dpo_policy.parameters(), 1.0)\n"
    "        dpo_opt.step()\n"
    "        dpo_opt.zero_grad()\n"
    "        losses_dpo.append((batch_loss / len(batch_idx)).item())\n"
    "\n"
    "        # Track true quality of samples from DPO policy\n"
    "        with torch.no_grad():\n"
    "            dpo_seqs = [sample_sequence(dpo_policy) for _ in range(32)]\n"
    "        tq_history.append(np.mean([true_reward(s) for s in dpo_seqs]))\n"
    "\n"
    "    return dpo_policy, losses_dpo, tq_history\n"
    "\n"
    "\n"
    "print('Running DPO training...')\n"
    "dpo_pol, dpo_losses, dpo_tq = run_dpo(pref_data, n_epochs=80, beta=0.1)\n"
    "print(f'DPO final true quality: {np.mean(dpo_tq[-20:]):.4f}')\n"
    "print(f'RLHF (beta=0.1) final true quality: {np.mean(true_quality_history[-20:]):.4f}')\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(12, 5))\n"
    "\n"
    "axes[0].plot(dpo_losses, color='#2c7bb6', linewidth=2, label='DPO loss')\n"
    "axes[0].set_xlabel('Epoch', fontsize=12)\n"
    "axes[0].set_ylabel('DPO Loss', fontsize=12)\n"
    "axes[0].set_title('DPO Training Loss', fontsize=12)\n"
    "axes[0].legend(); axes[0].set_facecolor('#f8f8f8'); axes[0].grid(True, alpha=0.4)\n"
    "\n"
    "# Compare quality curves: RLHF vs DPO\n"
    "axes[1].plot(true_quality_history, color='#d7191c',\n"
    "             label='RLHF (PPO, beta=0.1)', linewidth=2)\n"
    "steps_dpo = np.linspace(0, len(true_quality_history) - 1, len(dpo_tq))\n"
    "axes[1].plot(steps_dpo, dpo_tq, color='#2c7bb6',\n"
    "             label='DPO (beta=0.1)', linewidth=2, linestyle='--')\n"
    "axes[1].set_xlabel('Training Steps', fontsize=12)\n"
    "axes[1].set_ylabel('True Quality', fontsize=12)\n"
    "axes[1].set_title('True Quality: RLHF vs DPO', fontsize=12)\n"
    "axes[1].legend(); axes[1].set_facecolor('#f8f8f8'); axes[1].grid(True, alpha=0.4)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_dpo_compare.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
)

c13 = md(
    "## Comparison: RLHF (PPO) vs DPO\n\n"
    "Bar chart comparing PPO-RLHF vs DPO: training stages, true quality, RM reward.\n"
)

c14 = code(
    "# Comparison: PPO RLHF vs DPO vs SFT baseline\n"
    "torch.manual_seed(42)\n"
    "sft_pol = ToyLM().to(device)  # untrained = SFT baseline\n"
    "with torch.no_grad():\n"
    "    sft_seqs = [sample_sequence(sft_pol) for _ in range(100)]\n"
    "sft_quality = float(np.mean([true_reward(s) for s in sft_seqs]))\n"
    "\n"
    "methods = ['SFT only', 'RLHF\\n(PPO b=0.01)', 'RLHF\\n(PPO b=0.1)',\n"
    "           'RLHF\\n(PPO b=1.0)', 'DPO\\n(b=0.1)']\n"
    "qualities = [\n"
    "    sft_quality,\n"
    "    float(beta_results[0.01]['tq_final']),\n"
    "    float(np.mean(true_quality_history[-30:])),\n"
    "    float(beta_results[1.0]['tq_final']),\n"
    "    float(np.mean(dpo_tq[-30:])),\n"
    "]\n"
    "kl_divs = [\n"
    "    0.0,\n"
    "    float(beta_results[0.01]['kl_final']),\n"
    "    float(beta_results[0.1]['kl_final']),\n"
    "    float(beta_results[1.0]['kl_final']),\n"
    "    0.0,  # DPO: no explicit KL constraint\n"
    "]\n"
    "compute_stages = [1, 3, 3, 3, 2]  # SFT=1, RLHF=3 (SFT+RM+PPO), DPO=2 (SFT+DPO)\n"
    "\n"
    "colors_m = ['#636363', '#d7191c', '#2c7bb6', '#1a9641', '#fd8d3c']\n"
    "fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n"
    "\n"
    "x = np.arange(len(methods))\n"
    "bars = axes[0].bar(x, qualities, color=colors_m, alpha=0.85, edgecolor='black')\n"
    "axes[0].set_xticks(x)\n"
    "axes[0].set_xticklabels(methods, fontsize=10)\n"
    "axes[0].set_ylabel('True Quality Score', fontsize=12)\n"
    "axes[0].set_title('True Quality by Alignment Method', fontsize=12)\n"
    "axes[0].set_facecolor('#f8f8f8')\n"
    "axes[0].grid(True, alpha=0.4, axis='y')\n"
    "for bar, val in zip(bars, qualities):\n"
    "    axes[0].text(\n"
    "        bar.get_x() + bar.get_width() / 2,\n"
    "        bar.get_height() + 0.003,\n"
    "        f'{val:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold'\n"
    "    )\n"
    "\n"
    "# Quality vs compute\n"
    "for m, q, cost, color in zip(methods, qualities, compute_stages, colors_m):\n"
    "    label = m.replace('\\n', ' ')\n"
    "    axes[1].scatter(cost, q, s=160, color=color, edgecolors='black',\n"
    "                    linewidths=0.8, zorder=5)\n"
    "    axes[1].annotate(label, (cost, q),\n"
    "                     textcoords='offset points', xytext=(6, 3), fontsize=9)\n"
    "\n"
    "axes[1].set_xlabel('Relative Compute Stages', fontsize=12)\n"
    "axes[1].set_ylabel('True Quality Score', fontsize=12)\n"
    "axes[1].set_title('Quality vs Compute Tradeoff', fontsize=12)\n"
    "axes[1].set_facecolor('#f8f8f8'); axes[1].grid(True, alpha=0.4)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/rlhf_comparison.png', dpi=100, bbox_inches='tight')\n"
    "plt.show()\n"
    "\n"
    "print('Comparison Summary:')\n"
    "print(f'{\"Method\":<20} {\"True Quality\":<15} {\"KL Div\":<12} {\"Stages\":<8}')\n"
    "print('-' * 55)\n"
    "for m, q, kl, st in zip(methods, qualities, kl_divs, compute_stages):\n"
    "    print(f'{m.replace(chr(10), \" \"):<20} {q:<15.4f} {kl:<12.4f} {st}')\n"
)

c15 = md(
    "## Key Takeaways\n\n"
    "**Core idea:** RLHF trains a reward model from human preferences (Bradley-Terry loss),\n"
    "then uses PPO with KL penalty to align the policy. DPO removes the RM stage by directly\n"
    "optimizing preferences as a classification objective.\n\n"
    "**Variants and when to use:**\n\n"
    "| Method | RM needed | Online RL | Compute | Use when |\n"
    "|--------|----------|-----------|---------|----------|\n"
    "| SFT only | No | No | Low | Simple instruction following |\n"
    "| RLHF (PPO) | Yes | Yes | High | Complex alignment, growing data |\n"
    "| DPO | No (implicit) | No | Low | Fixed preference dataset, low compute |\n"
    "| KTO | No | No | Low | Single-response binary feedback |\n\n"
    "**Common failure modes:**\n"
    "- beta too small -> reward hacking (RM score up, true quality flat)\n"
    "- RM miscalibrated (low Pearson r) -> PPO optimizes wrong signal\n"
    "- KL term ignored -> policy collapses to degenerate outputs\n"
)

c16 = md(
    "## Exercises\n\n"
    "1. **Reward hacking detection**: In the PPO loop, plot both RM reward and true quality\n"
    "   on the same axes. With beta=0.001, at what step do they diverge?\n"
    "2. **Data efficiency**: Vary `n_pairs` in `run_dpo`. What is the minimum pref pairs\n"
    "   needed for DPO to outperform SFT baseline?\n"
    "3. **DPO beta sweep**: Run DPO with beta={0.01, 0.1, 1.0}.\n"
    "   How does beta affect the quality-diversity tradeoff?\n"
    "4. **RM quality effect**: Train RM with only 50 pairs, then run PPO.\n"
    "   Show that a miscalibrated RM leads to worse final true quality.\n"
)

nb.cells = [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16]
nb.metadata = {
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python", "version": "3.8.0"},
}

out = '/home/sbisw/github/interviewprep-ml/rl/notebooks/17-rlhf.ipynb'
nbformat.write(nb, out)
print(f"Written: {out}")
print(f"Cells: {len(nb.cells)}")
code_lines = sum(
    len(''.join(c['source']).split('\n'))
    for c in nb.cells if c['cell_type'] == 'code'
)
print(f"Code lines: {code_lines}")
