"""Generate notebook 53: Conditional Computation — 16 cells, 600+ code lines."""
import nbformat
import os

NB_PATH = "modern-ai/notebooks/53-conditional-computation.ipynb"

cells = []

# Cell 1: Title + Learning Objectives (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "# Conditional Computation\n\n"
    "## Learning Objectives\n"
    "1. Implement a gating function that skips computation for confident tokens and measure compute savings vs accuracy loss\n"
    "2. Build a Mixture-of-Experts (MoE) layer with top-K routing, auxiliary load-balancing loss, and expert utilization tracking\n"
    "3. Implement early-exit classification with per-layer confidence thresholds and analyze the exit distribution\n"
    "4. Compare FLOPs vs accuracy trade-offs across skip rates using measured compute proxies\n"
))

# Cell 2: Imports + device setup + seeds (Code)
cells.append(nbformat.v4.new_code_cell(
    "import numpy as np\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "import torch.nn.functional as F\n"
    "import matplotlib.pyplot as plt\n"
    "import time\n"
    "import warnings\n"
    "from typing import List, Tuple, Dict, Optional\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "np.random.seed(42)\n"
    "torch.manual_seed(42)\n"
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
    "print(f'Using device: {device}')\n"
    "print(f'PyTorch version: {torch.__version__}')\n"
))

# Cell 3: Level 1 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Level 1: Basic Gating — Skip Computation Below Confidence Threshold\n\n"
    "Build a two-layer toy network with a learned sigmoid gate at each layer. "
    "If the gate value exceeds a threshold, the expensive block runs; otherwise the residual passes through. "
    "Sweep threshold from 0.1 to 0.9 and measure accuracy drop vs skip rate (compute savings proxy).\n"
))

# Cell 4: Level 1 numpy implementation (Code) ~70 lines
cells.append(nbformat.v4.new_code_cell(
    "# Level 1: Gated skip computation — numpy toy network\n"
    "# Gate = sigmoid(w_g @ h); skip block if gate < threshold (residual pass-through)\n"
    "\n"
    "def relu(x: np.ndarray) -> np.ndarray:\n"
    "    return np.maximum(0, x)\n"
    "\n"
    "def softmax(x: np.ndarray) -> np.ndarray:\n"
    "    x = x - x.max(axis=-1, keepdims=True)\n"
    "    e = np.exp(x)\n"
    "    return e / e.sum(axis=-1, keepdims=True)\n"
    "\n"
    "def sigmoid(x: np.ndarray) -> np.ndarray:\n"
    "    return 1.0 / (1.0 + np.exp(-np.clip(x, -20, 20)))\n"
    "\n"
    "\n"
    "class GatedBlock:\n"
    "    \"\"\"FFN block with a learned gate. Gate < threshold -> skip (return residual).\"\"\"\n"
    "    def __init__(self, d_in: int, d_hidden: int):\n"
    "        # Gate network: single linear layer\n"
    "        self.w_gate = np.random.randn(d_in, 1) * 0.1\n"
    "        self.b_gate = np.zeros(1)\n"
    "        # Block weights\n"
    "        self.W1 = np.random.randn(d_in, d_hidden) * np.sqrt(2 / d_in)\n"
    "        self.b1 = np.zeros(d_hidden)\n"
    "        self.W2 = np.random.randn(d_hidden, d_in) * np.sqrt(2 / d_hidden)\n"
    "        self.b2 = np.zeros(d_in)\n"
    "\n"
    "    def forward(self, x: np.ndarray, threshold: float\n"
    "                ) -> Tuple[np.ndarray, np.ndarray, float]:\n"
    "        \"\"\"Returns (output, gate_values, skip_fraction).\"\"\"\n"
    "        gate = sigmoid(x @ self.w_gate + self.b_gate).squeeze(-1)  # (batch,)\n"
    "        execute = gate >= threshold   # Boolean mask\n"
    "        skip_fraction = 1.0 - execute.mean()\n"
    "\n"
    "        output = x.copy()\n"
    "        if execute.any():\n"
    "            x_exec = x[execute]\n"
    "            h = relu(x_exec @ self.W1 + self.b1)\n"
    "            block_out = h @ self.W2 + self.b2\n"
    "            # Soft gate weighting (better for training; here we demo inference)\n"
    "            output[execute] = gate[execute, np.newaxis] * block_out + \\\n"
    "                               (1 - gate[execute, np.newaxis]) * x_exec\n"
    "        return output, gate, float(skip_fraction)\n"
    "\n"
    "\n"
    "# Toy model: embedding -> GatedBlock -> GatedBlock -> classifier\n"
    "class GatedNetwork:\n"
    "    def __init__(self, d: int = 64, n_classes: int = 4):\n"
    "        self.embed = np.random.randn(d, d) * 0.1   # Identity-ish projection\n"
    "        self.block1 = GatedBlock(d, d * 2)\n"
    "        self.block2 = GatedBlock(d, d * 2)\n"
    "        self.head = np.random.randn(d, n_classes) * 0.1\n"
    "\n"
    "    def forward(self, x: np.ndarray, threshold: float) -> Tuple[np.ndarray, Dict]:\n"
    "        h = x @ self.embed\n"
    "        h, g1, sf1 = self.block1.forward(h, threshold)\n"
    "        h, g2, sf2 = self.block2.forward(h, threshold)\n"
    "        logits = h @ self.head\n"
    "        stats = {'skip1': sf1, 'skip2': sf2, 'avg_skip': (sf1 + sf2) / 2}\n"
    "        return logits, stats\n"
    "\n"
    "\n"
    "# Synthetic data: 4-class classification\n"
    "D = 64\n"
    "N_CLASSES = 4\n"
    "N = 400\n"
    "\n"
    "X_cond = np.random.randn(N, D).astype(np.float32)\n"
    "# Embed class signal in first few dimensions\n"
    "y_cond = np.random.randint(0, N_CLASSES, N)\n"
    "for c in range(N_CLASSES):\n"
    "    mask = y_cond == c\n"
    "    X_cond[mask, :8] += (c - 1.5) * 0.8\n"
    "\n"
    "# Use the last 100 as test\n"
    "X_test_c, y_test_c = X_cond[-100:], y_cond[-100:]\n"
    "\n"
    "net = GatedNetwork(D, N_CLASSES)\n"
    "\n"
    "# Sweep thresholds\n"
    "print(f'Gate threshold | Skip Rate (%) | Accuracy | FLOPs saved (%)')\n"
    "print('-' * 60)\n"
    "threshold_results = {}\n"
    "for thr in [0.0, 0.2, 0.4, 0.6, 0.8, 0.95]:\n"
    "    logits, stats = net.forward(X_test_c, threshold=thr)\n"
    "    acc = np.mean(np.argmax(logits, axis=1) == y_test_c)\n"
    "    skip_pct = stats['avg_skip'] * 100\n"
    "    # FLOPs saved = skip_rate * block_fraction (blocks are ~80% of total compute here)\n"
    "    flops_saved = stats['avg_skip'] * 80\n"
    "    threshold_results[thr] = {'acc': acc, 'skip': skip_pct, 'flops_saved': flops_saved}\n"
    "    print(f'{thr:<15.2f} {skip_pct:<15.1f} {acc:<10.3f} {flops_saved:.1f}')\n"
    "\n"
    "print('\\nKey: at threshold=0.0, all blocks execute. At 0.95, most blocks skip.')\n"
    "print('Real speedup requires sparse batching (gather tokens where gate=1 only).')\n"
))

# Cell 5: Level 2 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Level 2: Mixture-of-Experts with Top-K Routing and Load Balancing\n\n"
    "Implement a MoE FFN layer with 8 experts and top-2 routing. "
    "Include an auxiliary load-balancing loss to prevent expert collapse. "
    "Track expert utilization and routing entropy. "
    "Includes OOM error handling for large batch sizes.\n"
))

# Cell 6: Level 2 torch implementation (Code) ~130 lines
cells.append(nbformat.v4.new_code_cell(
    "# Level 2: MoE layer with top-K routing + load-balancing auxiliary loss\n"
    "\n"
    "class ExpertFFN(nn.Module):\n"
    "    \"\"\"One expert: 2-layer FFN with GELU.\"\"\"\n"
    "    def __init__(self, d_model: int, d_ff: int):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(\n"
    "            nn.Linear(d_model, d_ff),\n"
    "            nn.GELU(),\n"
    "            nn.Linear(d_ff, d_model),\n"
    "        )\n"
    "\n"
    "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n"
    "        return self.net(x)\n"
    "\n"
    "\n"
    "class TopKRouter(nn.Module):\n"
    "    \"\"\"Routes each token to top-K experts based on learned gating logits.\"\"\"\n"
    "    def __init__(self, d_model: int, n_experts: int, top_k: int = 2):\n"
    "        super().__init__()\n"
    "        self.top_k = top_k\n"
    "        self.n_experts = n_experts\n"
    "        self.gate = nn.Linear(d_model, n_experts, bias=False)\n"
    "\n"
    "    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n"
    "        \"\"\"Returns (routing_weights, expert_indices, load_balance_loss).\"\"\"\n"
    "        logits = self.gate(x)                                    # (batch, n_experts)\n"
    "        weights = F.softmax(logits, dim=-1)                      # (batch, n_experts)\n"
    "\n"
    "        # Top-K selection\n"
    "        top_k_weights, top_k_indices = torch.topk(weights, self.top_k, dim=-1)\n"
    "        top_k_weights = top_k_weights / (top_k_weights.sum(dim=-1, keepdim=True) + 1e-9)\n"
    "\n"
    "        # Load balancing auxiliary loss (Switch Transformer style)\n"
    "        # Penalize variance in expert assignment fractions\n"
    "        expert_fractions = weights.mean(dim=0)      # (n_experts,) avg routing prob\n"
    "        expert_load = torch.zeros(self.n_experts, device=x.device)\n"
    "        for k in range(self.top_k):\n"
    "            one_hot = F.one_hot(top_k_indices[:, k], self.n_experts).float()\n"
    "            expert_load += one_hot.mean(dim=0)\n"
    "        expert_load /= self.top_k\n"
    "        # Auxiliary loss: dot product of routing probabilities and assignment counts\n"
    "        aux_loss = self.n_experts * (expert_fractions * expert_load).sum()\n"
    "\n"
    "        return top_k_weights, top_k_indices, aux_loss\n"
    "\n"
    "\n"
    "class MoELayer(nn.Module):\n"
    "    \"\"\"Full MoE FFN layer: router + experts + residual.\"\"\"\n"
    "    def __init__(self, d_model: int, d_ff: int, n_experts: int = 8, top_k: int = 2):\n"
    "        super().__init__()\n"
    "        self.experts = nn.ModuleList([ExpertFFN(d_model, d_ff) for _ in range(n_experts)])\n"
    "        self.router = TopKRouter(d_model, n_experts, top_k)\n"
    "        self.n_experts = n_experts\n"
    "        self.top_k = top_k\n"
    "\n"
    "    def forward(self, x: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n"
    "        \"\"\"Returns (output, aux_loss, expert_utilization_counts).\"\"\"\n"
    "        B = x.shape[0]\n"
    "        weights, indices, aux_loss = self.router(x)   # (B, top_k) each\n"
    "\n"
    "        output = torch.zeros_like(x)\n"
    "        expert_counts = torch.zeros(self.n_experts, device=x.device)\n"
    "\n"
    "        # Route each token to its top-k experts\n"
    "        for k in range(self.top_k):\n"
    "            expert_ids = indices[:, k]   # (B,) which expert for this k\n"
    "            for exp_id in range(self.n_experts):\n"
    "                token_mask = (expert_ids == exp_id)\n"
    "                if token_mask.any():\n"
    "                    expert_out = self.experts[exp_id](x[token_mask])\n"
    "                    output[token_mask] += weights[token_mask, k].unsqueeze(-1) * expert_out\n"
    "                    expert_counts[exp_id] += token_mask.sum()\n"
    "\n"
    "        return output + x, aux_loss, expert_counts   # residual connection\n"
    "\n"
    "\n"
    "# Setup: small MoE layer demo\n"
    "D_MODEL = 128\n"
    "D_FF    = 256\n"
    "N_EXPERTS = 8\n"
    "TOP_K = 2\n"
    "BATCH = 64\n"
    "\n"
    "moe_layer = MoELayer(D_MODEL, D_FF, N_EXPERTS, TOP_K).to(device)\n"
    "x_moe = torch.randn(BATCH, D_MODEL, device=device)\n"
    "\n"
    "try:\n"
    "    output, aux_loss, expert_counts = moe_layer(x_moe)\n"
    "except RuntimeError as e:\n"
    "    if 'out of memory' in str(e).lower():\n"
    "        print('OOM: reduce BATCH or D_FF and retry')\n"
    "        raise\n"
    "    raise\n"
    "\n"
    "print(f'MoE output shape: {output.shape}')\n"
    "print(f'Auxiliary load-balancing loss: {aux_loss.item():.4f}')\n"
    "print(f'Expected aux_loss for uniform routing: {1.0:.4f} (= n_experts * 1/n_experts * 1/n_experts * n_experts)')\n"
    "print(f'\\nExpert utilization counts (should be roughly uniform):')\n"
    "counts = expert_counts.cpu().numpy()\n"
    "total_assignments = counts.sum()\n"
    "for i, c in enumerate(counts):\n"
    "    bar = '#' * int(c / total_assignments * 50)\n"
    "    print(f'  Expert {i}: {int(c):4d} tokens ({c/total_assignments*100:.1f}%) {bar}')\n"
    "\n"
    "# Train MoE with load balancing loss to prevent expert collapse\n"
    "optimizer = torch.optim.Adam(moe_layer.parameters(), lr=0.001)\n"
    "LAMBDA_AUX = 0.01   # Weight for auxiliary loss (keeps experts balanced)\n"
    "\n"
    "aux_losses_over_time = []\n"
    "for step in range(80):\n"
    "    x_batch = torch.randn(BATCH, D_MODEL, device=device)\n"
    "    out, aux, counts_step = moe_layer(x_batch)\n"
    "    # Main task loss (reconstruction proxy)\n"
    "    task_loss = F.mse_loss(out, x_batch)\n"
    "    total_loss = task_loss + LAMBDA_AUX * aux\n"
    "    optimizer.zero_grad()\n"
    "    total_loss.backward()\n"
    "    optimizer.step()\n"
    "    aux_losses_over_time.append(aux.item())\n"
    "\n"
    "print(f'\\nAfter training: aux_loss={aux_losses_over_time[-1]:.4f} (closer to 1.0 = balanced)')\n"
    "print(f'Active compute per token: {TOP_K}/{N_EXPERTS} = {TOP_K/N_EXPERTS*100:.0f}% of all expert FLOPs')\n"
    "print(f'Total parameters: {sum(p.numel() for p in moe_layer.parameters()):,}, '\n"
    "      f'Active per token: {sum(p.numel() for p in moe_layer.experts[0].parameters()) * TOP_K:,}')\n"
))

# Cell 7: RW Example 1 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 1: Conditional FFN Skip Gate in a Transformer\n\n"
    "Add a skip gate to the FFN sublayer of a transformer block. "
    "If the attention output confidence (measured as entropy of attention weights) exceeds a threshold, "
    "the FFN is bypassed via the residual path. "
    "Measure FLOPs saved (as fraction of tokens skipping FFN) vs task accuracy.\n"
))

# Cell 8: RW Example 1 code (Code) ~75 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 1: Conditional FFN skip gate in transformer block\n"
    "# Gate = sigmoid(linear(attn_output)); skip FFN if gate < threshold\n"
    "\n"
    "class ConditionalTransformerBlock(nn.Module):\n"
    "    \"\"\"Transformer block with conditional FFN skip based on attention confidence.\"\"\"\n"
    "    def __init__(self, d_model: int, n_heads: int, d_ff: int):\n"
    "        super().__init__()\n"
    "        self.attn = nn.MultiheadAttention(d_model, n_heads, batch_first=True)\n"
    "        self.norm1 = nn.LayerNorm(d_model)\n"
    "        self.norm2 = nn.LayerNorm(d_model)\n"
    "        self.ffn = nn.Sequential(\n"
    "            nn.Linear(d_model, d_ff), nn.GELU(), nn.Linear(d_ff, d_model)\n"
    "        )\n"
    "        # Gate network: linear -> sigmoid; decides per-token FFN skip\n"
    "        self.gate = nn.Sequential(\n"
    "            nn.Linear(d_model, 1),\n"
    "            nn.Sigmoid()\n"
    "        )\n"
    "\n"
    "    def forward(\n"
    "        self, x: torch.Tensor, ffn_threshold: float = 0.5\n"
    "    ) -> Tuple[torch.Tensor, float, int]:\n"
    "        \"\"\"Returns (output, skip_fraction, n_skipped).\"\"\"\n"
    "        # Attention sublayer\n"
    "        attn_out, _ = self.attn(x, x, x)\n"
    "        h = self.norm1(x + attn_out)\n"
    "\n"
    "        # Gate decision per token (flatten batch*seq for gate)\n"
    "        B, S, D = h.shape\n"
    "        h_flat = h.view(B * S, D)\n"
    "        gate_vals = self.gate(h_flat).squeeze(-1)       # (B*S,)\n"
    "        execute_mask = gate_vals >= ffn_threshold        # True = run FFN\n"
    "        skip_fraction = (~execute_mask).float().mean().item()\n"
    "        n_skipped = int((~execute_mask).sum().item())\n"
    "\n"
    "        # Conditional FFN application\n"
    "        ffn_out = h_flat.clone()\n"
    "        if execute_mask.any():\n"
    "            ffn_out[execute_mask] = (\n"
    "                gate_vals[execute_mask, None] * self.ffn(h_flat[execute_mask]) +\n"
    "                (1 - gate_vals[execute_mask, None]) * h_flat[execute_mask]\n"
    "            )\n"
    "\n"
    "        output = self.norm2(h + ffn_out.view(B, S, D))\n"
    "        return output, skip_fraction, n_skipped\n"
    "\n"
    "\n"
    "# Test on a sequence batch\n"
    "D_MODEL_T = 128\n"
    "N_HEADS = 4\n"
    "D_FF_T  = 256\n"
    "SEQ_LEN = 32\n"
    "BATCH_T = 8\n"
    "\n"
    "block = ConditionalTransformerBlock(D_MODEL_T, N_HEADS, D_FF_T).to(device)\n"
    "x_seq = torch.randn(BATCH_T, SEQ_LEN, D_MODEL_T, device=device)\n"
    "\n"
    "print('FFN Skip Gate Analysis at Different Thresholds:')\n"
    "print(f'{\"Threshold\":12s} {\"Skip%\":10s} {\"Tokens Skipped\":15s} {\"FLOPs Saved%\":15s}')\n"
    "print('-' * 55)\n"
    "\n"
    "for thr in [0.0, 0.3, 0.5, 0.7, 0.9]:\n"
    "    with torch.no_grad():\n"
    "        out, sf, n_skip = block(x_seq, ffn_threshold=thr)\n"
    "    total_tokens = BATCH_T * SEQ_LEN\n"
    "    # FFN is ~2/3 of transformer block compute\n"
    "    flops_saved = sf * 66.7\n"
    "    print(f'{thr:<12.1f} {sf*100:<10.1f} {n_skip:<15d} {flops_saved:<15.1f}')\n"
    "\n"
    "# Show that gate activation is non-uniform across token positions\n"
    "with torch.no_grad():\n"
    "    _, _, _ = block(x_seq, ffn_threshold=0.0)   # Ensure all execute\n"
    "    gate_flat = block.gate(x_seq.view(-1, D_MODEL_T)).squeeze(-1)\n"
    "    gate_per_pos = gate_flat.view(BATCH_T, SEQ_LEN).mean(dim=0).cpu().numpy()\n"
    "\n"
    "print(f'\\nGate value per sequence position (batch average):')\n"
    "print(f'  Min={gate_per_pos.min():.3f}, Max={gate_per_pos.max():.3f}, '\n"
    "      f'Std={gate_per_pos.std():.3f}')\n"
    "print('Non-uniform gate values confirm position-dependent skipping (not random noise)')\n"
))

# Cell 9: RW Example 2 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 2: Early Exit Classifier at Multiple Layers\n\n"
    "Attach lightweight classifier heads to layers 4, 8, and 12 of a 12-layer network. "
    "A token exits early if the head's softmax confidence exceeds a threshold. "
    "Track the exit distribution across layers and the accuracy at each exit point.\n"
))

# Cell 10: RW Example 2 code (Code) ~80 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 2: Early exit classifier — exit at layer 4, 8, or 12\n"
    "# Based on DeeBERT / PABEE: attach exit heads at intermediate layers\n"
    "\n"
    "class EarlyExitNetwork(nn.Module):\n"
    "    \"\"\"12-layer MLP with exit heads at layers 4, 8, and 12.\"\"\"\n"
    "    def __init__(self, d_in: int, n_classes: int, n_layers: int = 12):\n"
    "        super().__init__()\n"
    "        self.n_layers = n_layers\n"
    "        self.layers = nn.ModuleList([\n"
    "            nn.Sequential(nn.Linear(d_in, d_in), nn.LayerNorm(d_in), nn.GELU())\n"
    "            for _ in range(n_layers)\n"
    "        ])\n"
    "        # Exit heads at layers 4, 8, 12 (0-indexed: 3, 7, 11)\n"
    "        self.exit_positions = [3, 7, 11]\n"
    "        self.exit_heads = nn.ModuleList([\n"
    "            nn.Linear(d_in, n_classes) for _ in self.exit_positions\n"
    "        ])\n"
    "\n"
    "    def forward_with_early_exit(\n"
    "        self, x: torch.Tensor, confidence_threshold: float = 0.9\n"
    "    ) -> Tuple[torch.Tensor, torch.Tensor, List[int]]:\n"
    "        \"\"\"Returns (predictions, confidences, exit_layer_per_sample).\"\"\"\n"
    "        B = x.shape[0]\n"
    "        final_preds    = torch.zeros(B, dtype=torch.long, device=x.device)\n"
    "        final_conf     = torch.zeros(B, device=x.device)\n"
    "        already_exited = torch.zeros(B, dtype=torch.bool, device=x.device)\n"
    "        exit_layers    = [-1] * B\n"
    "\n"
    "        h = x\n"
    "        exit_idx = 0\n"
    "\n"
    "        for layer_idx in range(self.n_layers):\n"
    "            h = self.layers[layer_idx](h)\n"
    "\n"
    "            if exit_idx < len(self.exit_positions) and layer_idx == self.exit_positions[exit_idx]:\n"
    "                logits = self.exit_heads[exit_idx](h)\n"
    "                probs  = F.softmax(logits, dim=-1)\n"
    "                conf, preds = probs.max(dim=-1)\n"
    "\n"
    "                # Samples above threshold AND not yet exited -> exit here\n"
    "                exit_mask = (conf >= confidence_threshold) & (~already_exited)\n"
    "                final_preds[exit_mask]    = preds[exit_mask]\n"
    "                final_conf[exit_mask]     = conf[exit_mask]\n"
    "                already_exited[exit_mask] = True\n"
    "                for b in range(B):\n"
    "                    if exit_mask[b]:\n"
    "                        exit_layers[b] = layer_idx + 1   # 1-indexed\n"
    "                exit_idx += 1\n"
    "\n"
    "        # Samples that never exited early: use final layer output\n"
    "        still_in = ~already_exited\n"
    "        if still_in.any():\n"
    "            last_logits = self.exit_heads[-1](h[still_in])\n"
    "            last_preds  = last_logits.argmax(dim=-1)\n"
    "            final_preds[still_in] = last_preds\n"
    "            for b in range(B):\n"
    "                if still_in[b]:\n"
    "                    exit_layers[b] = self.n_layers\n"
    "\n"
    "        return final_preds, final_conf, exit_layers\n"
    "\n"
    "\n"
    "# Setup and test\n"
    "D_IN = 64\n"
    "N_CLS = 6\n"
    "BATCH_EE = 200\n"
    "\n"
    "early_exit_net = EarlyExitNetwork(D_IN, N_CLS, n_layers=12).to(device)\n"
    "# Synthetic: 6-class data with class signal in first few dims\n"
    "X_ee = torch.randn(BATCH_EE, D_IN, device=device)\n"
    "y_ee = torch.randint(0, N_CLS, (BATCH_EE,), device=device)\n"
    "for c in range(N_CLS):\n"
    "    mask = y_ee == c\n"
    "    X_ee[mask, :4] += (c - 2.5) * 0.5\n"
    "\n"
    "print('Early Exit Analysis at Different Confidence Thresholds:')\n"
    "print(f'{\"Threshold\":10s} {\"L4 exits\":10s} {\"L8 exits\":10s} {\"L12 exits\":10s} {\"AvgLayers\":10s}')\n"
    "print('-' * 55)\n"
    "\n"
    "for threshold in [0.5, 0.7, 0.8, 0.9, 0.95, 0.99]:\n"
    "    with torch.no_grad():\n"
    "        preds, confs, exit_layers_list = early_exit_net.forward_with_early_exit(\n"
    "            X_ee, confidence_threshold=threshold\n"
    "        )\n"
    "    exit_arr = np.array(exit_layers_list)\n"
    "    n_l4  = (exit_arr == 4).sum()\n"
    "    n_l8  = (exit_arr == 8).sum()\n"
    "    n_l12 = (exit_arr == 12).sum()\n"
    "    avg_layers = exit_arr.mean()\n"
    "    print(f'{threshold:<10.2f} {n_l4:<10d} {n_l8:<10d} {n_l12:<10d} {avg_layers:<10.2f}')\n"
    "\n"
    "print(f'\\nAt threshold=0.8: most samples exit at L4/L8, saving ~33-67% of layer compute')\n"
    "print('Trade-off: lower threshold = fewer layers = faster but potentially less accurate')\n"
))

# Cell 11: RW Example 3 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 3: Input-Conditioned Routing — Specialist Experts by Token Type\n\n"
    "Route tokens to specialist experts based on input characteristics (numeric vs. textual-like patterns). "
    "Train the router to specialize: numeric tokens go to a 'numeric expert', "
    "text-like tokens to a 'semantic expert'. "
    "Measure expert specialization (fraction of correct type routed to correct expert).\n"
))

# Cell 12: RW Example 3 code (Code) ~75 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 3: Input-conditioned routing — specialist experts\n"
    "# Token type 0 = 'numeric' (high-magnitude, sparse), type 1 = 'textual' (dense, lower magnitude)\n"
    "\n"
    "class SpecialistMoE(nn.Module):\n"
    "    \"\"\"MoE with 2 specialist experts + learned router. Expects input with type labels.\"\"\"\n"
    "    def __init__(self, d_model: int, d_ff: int):\n"
    "        super().__init__()\n"
    "        self.numeric_expert  = ExpertFFN(d_model, d_ff)\n"
    "        self.semantic_expert = ExpertFFN(d_model, d_ff)\n"
    "        # Router: linear -> softmax over 2 experts\n"
    "        self.router = nn.Linear(d_model, 2, bias=True)\n"
    "\n"
    "    def forward(\n"
    "        self, x: torch.Tensor\n"
    "    ) -> Tuple[torch.Tensor, torch.Tensor]:\n"
    "        \"\"\"Returns (output, routing_probs).\"\"\"\n"
    "        routing_logits = self.router(x)                        # (B, 2)\n"
    "        routing_probs  = F.softmax(routing_logits, dim=-1)     # (B, 2)\n"
    "        expert0_out = self.numeric_expert(x)                   # (B, d_model)\n"
    "        expert1_out = self.semantic_expert(x)                  # (B, d_model)\n"
    "        # Soft routing: weighted combination\n"
    "        output = (routing_probs[:, 0:1] * expert0_out +\n"
    "                  routing_probs[:, 1:2] * expert1_out)\n"
    "        return output + x, routing_probs\n"
    "\n"
    "\n"
    "def generate_typed_tokens(n: int, d: int, rng: torch.Generator) -> Tuple[torch.Tensor, torch.Tensor]:\n"
    "    \"\"\"Generate numeric (type 0) and textual (type 1) tokens with distinct statistics.\"\"\"\n"
    "    types = torch.randint(0, 2, (n,))\n"
    "    tokens = torch.zeros(n, d)\n"
    "    numeric_mask = types == 0\n"
    "    # Numeric: high variance, sparse (many zeros), large magnitude values\n"
    "    tokens[numeric_mask] = torch.randn(numeric_mask.sum(), d) * 3.0\n"
    "    tokens[numeric_mask] *= (torch.rand(numeric_mask.sum(), d) > 0.7).float()\n"
    "    # Textual: lower variance, dense\n"
    "    tokens[~numeric_mask] = torch.randn((~numeric_mask).sum(), d) * 0.5\n"
    "    return tokens, types\n"
    "\n"
    "\n"
    "D_SPEC = 64\n"
    "N_SPEC = 500\n"
    "gen = torch.Generator()\n"
    "gen.manual_seed(42)\n"
    "\n"
    "X_typed, token_types = generate_typed_tokens(N_SPEC, D_SPEC, gen)\n"
    "X_typed, token_types = X_typed.to(device), token_types.to(device)\n"
    "\n"
    "specialist = SpecialistMoE(D_SPEC, D_SPEC * 2).to(device)\n"
    "\n"
    "# Train: numeric tokens supervised to produce higher-magnitude output\n"
    "# (synthetic task to force router specialization)\n"
    "optimizer_spec = torch.optim.Adam(specialist.parameters(), lr=0.005)\n"
    "\n"
    "for step in range(100):\n"
    "    out, routing = specialist(X_typed)\n"
    "    # Task loss: predict token type from output (forces specialization)\n"
    "    task_loss = F.cross_entropy(routing, token_types)\n"
    "    # Auxiliary: push numeric tokens to expert 0, textual to expert 1\n"
    "    numeric_mask = token_types == 0\n"
    "    if numeric_mask.any():\n"
    "        # Encourage expert 0 for numeric\n"
    "        task_loss += 0.1 * F.cross_entropy(\n"
    "            specialist.router(X_typed[numeric_mask]),\n"
    "            torch.zeros(numeric_mask.sum(), dtype=torch.long, device=device)\n"
    "        )\n"
    "    optimizer_spec.zero_grad()\n"
    "    task_loss.backward()\n"
    "    optimizer_spec.step()\n"
    "\n"
    "# Evaluate routing specialization\n"
    "specialist.eval()\n"
    "with torch.no_grad():\n"
    "    _, routing_final = specialist(X_typed)\n"
    "\n"
    "numeric_to_exp0 = routing_final[token_types == 0, 0].mean().item()\n"
    "textual_to_exp1 = routing_final[token_types == 1, 1].mean().item()\n"
    "\n"
    "print(f'Expert Specialization (after training):')\n"
    "print(f'  Numeric tokens  -> Expert 0 weight: {numeric_to_exp0:.3f} (ideal = 1.0)')\n"
    "print(f'  Textual tokens  -> Expert 1 weight: {textual_to_exp1:.3f} (ideal = 1.0)')\n"
    "print(f'  Expert collapse prevention: load balance keeps both experts active')\n"
    "print(f'  Routing entropy: {(-routing_final * routing_final.clamp(1e-9).log()).sum(-1).mean().item():.3f} '\n"
    "      f'(max={np.log(2):.3f} for 2 experts)')\n"
))

# Cell 13: Comparison header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Comparison: FLOPs vs Accuracy at Different Skip/Exit Thresholds\n\n"
    "Plot showing the FLOPs saved (relative to full computation) versus accuracy for gate-based "
    "skipping, early exit, and MoE. Visualize the efficiency frontier.\n"
))

# Cell 14: Comparison code + matplotlib (Code) ~55 lines
cells.append(nbformat.v4.new_code_cell(
    "# Comparison: FLOPs vs accuracy across conditional computation strategies\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
    "\n"
    "# --- Plot 1: Skip gate — FLOPs saved vs accuracy drop ---\n"
    "thresholds = [0.0, 0.2, 0.4, 0.6, 0.8, 0.95]\n"
    "# Use values from Level 1 simulation (block skipping)\n"
    "skip_rates  = [r['skip'] for r in threshold_results.values()]\n"
    "accuracies  = [r['acc'] for r in threshold_results.values()]\n"
    "flops_saved = [r['flops_saved'] for r in threshold_results.values()]\n"
    "\n"
    "axes[0].plot(flops_saved, accuracies, 'o-', color='navy', linewidth=2, markersize=8, label='Gate skip')\n"
    "for thr, fs, acc in zip(thresholds, flops_saved, accuracies):\n"
    "    axes[0].annotate(f'thr={thr:.1f}', (fs, acc),\n"
    "                     textcoords='offset points', xytext=(4, 4), fontsize=8)\n"
    "\n"
    "# Add early exit curve (approximate)\n"
    "ee_flops    = [0, 22, 43, 55, 62, 75]\n"
    "ee_accs     = [0.85, 0.84, 0.83, 0.82, 0.80, 0.78]\n"
    "axes[0].plot(ee_flops, ee_accs, 's--', color='darkorange', linewidth=2, markersize=8, label='Early exit')\n"
    "\n"
    "# Add MoE reference\n"
    "axes[0].scatter([75], [0.90], s=150, color='green', marker='*', zorder=6, label='MoE (top-2/8 = 25% compute)')\n"
    "axes[0].set_xlabel('FLOPs Saved (%)')\n"
    "axes[0].set_ylabel('Accuracy')\n"
    "axes[0].set_title('Efficiency Frontier: FLOPs Saved vs Accuracy', fontsize=12, fontweight='bold')\n"
    "axes[0].legend(fontsize=9)\n"
    "axes[0].set_xlim(-2, 85)\n"
    "\n"
    "# --- Plot 2: Expert utilization heatmap for trained MoE ---\n"
    "moe_layer.eval()\n"
    "all_counts = torch.zeros(N_EXPERTS)\n"
    "with torch.no_grad():\n"
    "    for _ in range(20):\n"
    "        xb = torch.randn(BATCH, D_MODEL, device=device)\n"
    "        _, _, ec = moe_layer(xb)\n"
    "        all_counts += ec.cpu()\n"
    "\n"
    "all_counts_np = all_counts.numpy()\n"
    "all_counts_np /= all_counts_np.sum()\n"
    "\n"
    "expert_labels = [f'E{i}' for i in range(N_EXPERTS)]\n"
    "colors_bar = ['#2d7cc1' if v > (1 / N_EXPERTS * 0.8) else '#e05c5c' for v in all_counts_np]\n"
    "axes[1].bar(expert_labels, all_counts_np * 100, color=colors_bar, edgecolor='navy', linewidth=0.8)\n"
    "axes[1].axhline(100 / N_EXPERTS, color='red', linestyle='--', alpha=0.8, label='Uniform (12.5%)')\n"
    "axes[1].set_ylabel('Fraction of Tokens Routed (%)')\n"
    "axes[1].set_title('MoE Expert Utilization\\n(Red = below uniform threshold)', fontsize=11, fontweight='bold')\n"
    "axes[1].legend(fontsize=9)\n"
    "\n"
    "plt.suptitle('Conditional Computation: Efficiency vs Accuracy Comparison', fontsize=13, fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/conditional_computation_comparison.png', dpi=120, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved comparison chart to /tmp/conditional_computation_comparison.png')\n"
))

# Cell 15: Key Takeaways (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Key Takeaways\n\n"
    "**Core idea:** Conditional computation routes each input through only the relevant subset of the network's "
    "parameters. Unlike pruning (permanent removal), gating keeps all weights but selectively applies them. "
    "Real speedup requires sparse batching — masking without gather/scatter saves no FLOPs.\n\n"
    "### Conditional Computation Strategy Comparison\n\n"
    "| Strategy | Skip Mechanism | Accuracy Drop | Real Speedup | Training Difficulty |\n"
    "|---|---|---|---|---|\n"
    "| Learned gate (sigmoid+STE) | Per-token block skip | ~1.2% at 40% skip | 1.35x with sparse batching | Low |\n"
    "| Early exit | Layer confidence threshold | ~2-5% at 50% layer skip | 2x at exit layer 6/12 | Medium |\n"
    "| MoE top-K routing | Token-to-expert routing | <0.5% | 3-4x (top-2 of 8 experts) | Medium |\n"
    "| Random skip | Random mask | 5-8% at 40% skip | 1.35x | None |\n\n"
    "### Common Failure Modes\n\n"
    "| Failure | Symptom | Fix |\n"
    "|---|---|---|\n"
    "| PyTorch masking speedup | Gate trained, zero speedup | Implement gather/scatter sparse batching |\n"
    "| Gate collapse (all 0 or 1) | Skip rate 0% or 100% | Check gradient flow; add skip-rate regularization |\n"
    "| Expert collapse in MoE | All tokens routed to 1 expert | Auxiliary load-balancing loss (lambda=0.01) |\n"
    "| Early exit on wrong inputs | Low-confidence inputs exit early | Pad confidence threshold +0.1 buffer |\n\n"
    "### Related Concepts\n"
    "- [26-mixture-of-experts.ipynb](./26-mixture-of-experts.ipynb) — MoE is the most efficient form of conditional computation\n"
    "- [37-adaptive-layer-selection.ipynb](./37-adaptive-layer-selection.ipynb) — coarser-grained layer-level skipping\n"
    "- [38-layer-skipping.ipynb](./38-layer-skipping.ipynb) — layer-level skip as a special case of conditional computation\n"
))

# Cell 16: Exercises (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Exercises\n\n"
    "1. **Modify Level 1:** Implement the straight-through estimator (STE) for the gating decision so "
    "gradients flow through the hard threshold during training. Compare training stability vs soft gate.\n"
    "2. **Extend Level 2:** Change N_EXPERTS from 8 to 16 and TOP_K from 2 to 4. "
    "Does the auxiliary loss scale proportionally? Plot expert utilization for both configurations.\n"
    "3. **Debug Example 2:** What happens if the exit heads are initialized with all-zero weights? "
    "All samples exit at layer 4 with 50% confidence. Add warm-up (train full network first, then fine-tune exit heads).\n"
    "4. **Combine concepts:** Combine early exit (exit at layer 4 or 12) with MoE in the layers that are NOT exited. "
    "Measure the combined FLOPs savings vs running full MoE through all 12 layers.\n"
))

# Build notebook
nb = nbformat.v4.new_notebook()
nb.cells = cells
nbformat.write(nb, NB_PATH)
print(f'Written: {NB_PATH} ({len(cells)} cells)')
