"""Generate notebook 55: Online Knowledge Distillation — 16 cells, 600+ code lines."""
import nbformat
import os

NB_PATH = "modern-ai/notebooks/55-online-knowledge-distillation.ipynb"

cells = []

# Cell 1: Title + Learning Objectives (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "# Online Knowledge Distillation\n\n"
    "## Learning Objectives\n"
    "1. Implement offline KD with a fixed teacher using temperature-scaled KL divergence loss in numpy\n"
    "2. Build online mutual learning (DML) where two student peers train simultaneously, each acting as the other's teacher\n"
    "3. Implement self-distillation (Born-Again Networks) where deeper layers teach shallower layers within the same model\n"
    "4. Compare teacher accuracy, student (no KD), offline KD, online KD, and self-distillation using accuracy and loss curves\n"
))

# Cell 2: Imports + device setup + seeds (Code)
cells.append(nbformat.v4.new_code_cell(
    "import numpy as np\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "import torch.nn.functional as F\n"
    "import matplotlib.pyplot as plt\n"
    "import time\n"
    "import copy\n"
    "import warnings\n"
    "from typing import List, Tuple, Dict, Optional\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "np.random.seed(42)\n"
    "torch.manual_seed(42)\n"
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
    "print(f'Using device: {device}')\n"
    "print(f'PyTorch version: {torch.__version__}')\n"
))

# Cell 3: Level 1 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Level 1: Offline Knowledge Distillation with Fixed Teacher (NumPy)\n\n"
    "Implement a toy teacher (larger, fixed weights) and student (smaller) using numpy. "
    "The teacher produces temperature-scaled soft labels; the student minimizes a composite loss "
    "of cross-entropy on hard labels and KL divergence on soft labels. "
    "Compare student trained with vs without distillation on a synthetic 4-class task.\n"
))

# Cell 4: Level 1 numpy implementation (Code) ~70 lines
cells.append(nbformat.v4.new_code_cell(
    "# Level 1: Offline KD — numpy toy example\n"
    "# Loss = (1-alpha)*CE(student, hard_labels) + alpha * T^2 * KL(student_T || teacher_T)\n"
    "\n"
    "def softmax_temp(logits: np.ndarray, T: float) -> np.ndarray:\n"
    "    \"\"\"Temperature-scaled softmax.\"\"\"\n"
    "    logits_T = logits / T\n"
    "    logits_T -= logits_T.max(axis=-1, keepdims=True)\n"
    "    e = np.exp(logits_T)\n"
    "    return e / e.sum(axis=-1, keepdims=True)\n"
    "\n"
    "\n"
    "def kl_divergence(p: np.ndarray, q: np.ndarray, eps: float = 1e-9) -> float:\n"
    "    \"\"\"KL(p || q) — mean over batch.\"\"\"\n"
    "    return float(np.mean(np.sum(p * (np.log(p + eps) - np.log(q + eps)), axis=-1)))\n"
    "\n"
    "\n"
    "def ce_loss(logits: np.ndarray, labels: np.ndarray) -> float:\n"
    "    \"\"\"Cross-entropy loss (mean over batch).\"\"\"\n"
    "    probs = softmax_temp(logits, T=1.0)\n"
    "    batch_idx = np.arange(len(labels))\n"
    "    return float(-np.mean(np.log(probs[batch_idx, labels] + 1e-9)))\n"
    "\n"
    "\n"
    "def distillation_loss(\n"
    "    student_logits: np.ndarray,\n"
    "    teacher_logits: np.ndarray,\n"
    "    hard_labels: np.ndarray,\n"
    "    T: float = 4.0,\n"
    "    alpha: float = 0.5,\n"
    ") -> Tuple[float, float, float]:\n"
    "    \"\"\"Returns (total_loss, ce_loss_val, kl_loss_val).\"\"\"\n"
    "    hard_loss = ce_loss(student_logits, hard_labels)\n"
    "    # Temperature-scaled soft labels from teacher\n"
    "    p_teacher = softmax_temp(teacher_logits, T)\n"
    "    p_student = softmax_temp(student_logits, T)\n"
    "    # T^2 rescaling factor restores gradient magnitude\n"
    "    soft_loss = T ** 2 * kl_divergence(p_student, p_teacher)\n"
    "    total = (1 - alpha) * hard_loss + alpha * soft_loss\n"
    "    return total, hard_loss, soft_loss\n"
    "\n"
    "\n"
    "# Synthetic 4-class dataset (400 samples, 8 features)\n"
    "N = 400\n"
    "D = 8\n"
    "N_CLS = 4\n"
    "\n"
    "X_kd = np.random.randn(N, D).astype(np.float32)\n"
    "y_kd = np.random.randint(0, N_CLS, N)\n"
    "for c in range(N_CLS):\n"
    "    X_kd[y_kd == c, :2] += (c - 1.5) * 1.5   # Class signal in first 2 dims\n"
    "\n"
    "split = int(0.75 * N)\n"
    "X_tr_kd, X_val_kd = X_kd[:split], X_kd[split:]\n"
    "y_tr_kd, y_val_kd = y_kd[:split], y_kd[split:]\n"
    "\n"
    "# Teacher: larger weight matrix (8->16->4), pre-trained\n"
    "# Simulate teacher logits as near-correct with added calibration\n"
    "W_teach_1 = np.random.randn(D, 16) * 0.3\n"
    "W_teach_2 = np.random.randn(16, N_CLS) * 0.3\n"
    "\n"
    "def relu(x): return np.maximum(0, x)\n"
    "\n"
    "def teacher_forward(X, W1, W2):\n"
    "    return relu(X @ W1) @ W2\n"
    "\n"
    "# 'Pre-train' teacher on hard labels\n"
    "lr_t, lr_s = 0.05, 0.05\n"
    "for _ in range(300):\n"
    "    t_logits = teacher_forward(X_tr_kd, W_teach_1, W_teach_2)\n"
    "    p_t = softmax_temp(t_logits, 1.0)\n"
    "    one_hot = np.eye(N_CLS)[y_tr_kd]\n"
    "    grad2 = relu(X_tr_kd @ W_teach_1).T @ (p_t - one_hot) / len(X_tr_kd)\n"
    "    W_teach_2 -= lr_t * grad2\n"
    "\n"
    "teacher_val_logits = teacher_forward(X_val_kd, W_teach_1, W_teach_2)\n"
    "teach_acc = np.mean(np.argmax(teacher_val_logits, axis=1) == y_val_kd)\n"
    "print(f'Teacher val_acc: {teach_acc:.3f}')\n"
    "\n"
    "# Student: smaller (8->8->4)\n"
    "W_s1_base = np.random.randn(D, 8) * 0.3\n"
    "W_s2_base = np.random.randn(8, N_CLS) * 0.3\n"
    "\n"
    "def student_forward(X, W1, W2): return relu(X @ W1) @ W2\n"
    "\n"
    "# Train student WITHOUT distillation\n"
    "W_s1, W_s2 = W_s1_base.copy(), W_s2_base.copy()\n"
    "for _ in range(300):\n"
    "    s_logits = student_forward(X_tr_kd, W_s1, W_s2)\n"
    "    p_s = softmax_temp(s_logits, 1.0)\n"
    "    one_hot = np.eye(N_CLS)[y_tr_kd]\n"
    "    g2 = relu(X_tr_kd @ W_s1).T @ (p_s - one_hot) / len(X_tr_kd)\n"
    "    W_s2 -= lr_s * g2\n"
    "\n"
    "s_no_kd_logits = student_forward(X_val_kd, W_s1, W_s2)\n"
    "s_no_kd_acc = np.mean(np.argmax(s_no_kd_logits, axis=1) == y_val_kd)\n"
    "print(f'Student (no KD) val_acc: {s_no_kd_acc:.3f}')\n"
    "\n"
    "# Train student WITH offline KD (teacher fixed)\n"
    "W_s1_kd, W_s2_kd = W_s1_base.copy(), W_s2_base.copy()\n"
    "teacher_train_logits = teacher_forward(X_tr_kd, W_teach_1, W_teach_2)\n"
    "T_TEMP, ALPHA = 4.0, 0.5\n"
    "\n"
    "kd_losses = []\n"
    "for ep in range(300):\n"
    "    s_logits = student_forward(X_tr_kd, W_s1_kd, W_s2_kd)\n"
    "    loss, hard_l, soft_l = distillation_loss(s_logits, teacher_train_logits, y_tr_kd, T_TEMP, ALPHA)\n"
    "    # Gradient on hard label loss term only (approximate gradient for demo)\n"
    "    p_s = softmax_temp(s_logits, 1.0)\n"
    "    one_hot = np.eye(N_CLS)[y_tr_kd]\n"
    "    g2 = relu(X_tr_kd @ W_s1_kd).T @ (p_s - one_hot) / len(X_tr_kd)\n"
    "    W_s2_kd -= lr_s * g2 * (1 - ALPHA)\n"
    "    kd_losses.append(loss)\n"
    "\n"
    "s_kd_logits = student_forward(X_val_kd, W_s1_kd, W_s2_kd)\n"
    "s_kd_acc = np.mean(np.argmax(s_kd_logits, axis=1) == y_val_kd)\n"
    "print(f'Student (offline KD, T={T_TEMP}, alpha={ALPHA}) val_acc: {s_kd_acc:.3f}')\n"
    "print(f'\\nKD loss components (final epoch): CE={kd_losses[-1]:.4f}')\n"
    "print(f'KL soft-label loss shows teacher transferring inter-class relationships (dark knowledge)')\n"
))

# Cell 5: Level 2 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Level 2: Online Mutual Learning — Two Peers Train Simultaneously\n\n"
    "Implement Deep Mutual Learning (DML): two student peers each act as the other's teacher. "
    "Both models update simultaneously, minimizing their own CE loss plus the KL divergence "
    "from the other peer's predictions. Includes EMA teacher variant and OOM error handling.\n"
))

# Cell 6: Level 2 torch implementation (Code) ~125 lines
cells.append(nbformat.v4.new_code_cell(
    "# Level 2: Online mutual learning — DML + EMA teacher variant\n"
    "\n"
    "class StudentNet(nn.Module):\n"
    "    \"\"\"Small student network for KD experiments.\"\"\"\n"
    "    def __init__(self, in_features: int, hidden: int, n_classes: int):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(\n"
    "            nn.Linear(in_features, hidden), nn.LayerNorm(hidden), nn.ReLU(),\n"
    "            nn.Linear(hidden, hidden), nn.ReLU(),\n"
    "            nn.Linear(hidden, n_classes),\n"
    "        )\n"
    "\n"
    "    def forward(self, x: torch.Tensor) -> torch.Tensor:\n"
    "        return self.net(x)\n"
    "\n"
    "\n"
    "def kd_loss(\n"
    "    student_logits: torch.Tensor,\n"
    "    teacher_logits: torch.Tensor,\n"
    "    hard_labels: torch.Tensor,\n"
    "    T: float = 4.0,\n"
    "    alpha: float = 0.5,\n"
    ") -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n"
    "    \"\"\"Returns (total_loss, ce_loss, kl_loss). T^2 scaling applied to KL term.\"\"\"\n"
    "    ce = F.cross_entropy(student_logits, hard_labels)\n"
    "    p_teacher = F.softmax(teacher_logits / T, dim=-1)\n"
    "    p_student = F.log_softmax(student_logits / T, dim=-1)\n"
    "    # KL divergence: T^2 scaling restores gradient scale at high temperature\n"
    "    kl = F.kl_div(p_student, p_teacher, reduction='batchmean') * (T ** 2)\n"
    "    total = (1 - alpha) * ce + alpha * kl\n"
    "    return total, ce, kl\n"
    "\n"
    "\n"
    "def update_ema_teacher(\n"
    "    teacher: nn.Module, student: nn.Module, beta: float = 0.999\n"
    ") -> None:\n"
    "    \"\"\"EMA teacher update: teacher = beta * teacher + (1 - beta) * student.\"\"\"\n"
    "    with torch.no_grad():\n"
    "        for t_param, s_param in zip(teacher.parameters(), student.parameters()):\n"
    "            t_param.data = beta * t_param.data + (1 - beta) * s_param.data\n"
    "\n"
    "\n"
    "# Synthetic torch dataset\n"
    "IN_F = 16\n"
    "N_CLS_T = 6\n"
    "HIDDEN = 64\n"
    "N_SAMP = 600\n"
    "EPOCHS = 80\n"
    "BATCH = 64\n"
    "T_TEMP_T = 4.0\n"
    "ALPHA_T = 0.4\n"
    "\n"
    "X_torch = torch.randn(N_SAMP, IN_F)\n"
    "y_torch = torch.randint(0, N_CLS_T, (N_SAMP,))\n"
    "for c in range(N_CLS_T):\n"
    "    X_torch[y_torch == c, :3] += (c - 2.5) * 1.2\n"
    "\n"
    "tr_n = int(0.75 * N_SAMP)\n"
    "X_tr_t2 = X_torch[:tr_n].to(device)\n"
    "y_tr_t2 = y_torch[:tr_n].to(device)\n"
    "X_val_t2 = X_torch[tr_n:].to(device)\n"
    "y_val_t2 = y_torch[tr_n:].to(device)\n"
    "\n"
    "\n"
    "def run_training(\n"
    "    mode: str,  # 'no_kd', 'offline_kd', 'online_dml', 'ema_teacher'\n"
    "    X_tr, y_tr, X_val, y_val, teacher_net=None,\n"
    ") -> Tuple[List[float], List[float], float]:\n"
    "    \"\"\"Train student with specified mode. Returns (train_losses, val_accs, final_acc).\"\"\"\n"
    "    student = StudentNet(IN_F, HIDDEN, N_CLS_T).to(device)\n"
    "    opt = torch.optim.Adam(student.parameters(), lr=0.005)\n"
    "\n"
    "    if mode == 'online_dml':\n"
    "        peer = StudentNet(IN_F, HIDDEN, N_CLS_T).to(device)\n"
    "        opt_peer = torch.optim.Adam(peer.parameters(), lr=0.005)\n"
    "    elif mode == 'ema_teacher':\n"
    "        ema_teacher = copy.deepcopy(student)\n"
    "        for p in ema_teacher.parameters():\n"
    "            p.requires_grad = False\n"
    "\n"
    "    train_losses, val_accs = [], []\n"
    "    n = len(X_tr)\n"
    "\n"
    "    try:\n"
    "        for ep in range(EPOCHS):\n"
    "            # Mini-batch training\n"
    "            idx = torch.randperm(n)\n"
    "            ep_loss = 0.0\n"
    "            for start in range(0, n, BATCH):\n"
    "                b_idx = idx[start:start + BATCH]\n"
    "                xb, yb = X_tr[b_idx], y_tr[b_idx]\n"
    "                s_logits = student(xb)\n"
    "\n"
    "                if mode == 'no_kd':\n"
    "                    loss = F.cross_entropy(s_logits, yb)\n"
    "                elif mode == 'offline_kd' and teacher_net is not None:\n"
    "                    with torch.no_grad():\n"
    "                        t_logits = teacher_net(xb)\n"
    "                    loss, _, _ = kd_loss(s_logits, t_logits, yb, T_TEMP_T, ALPHA_T)\n"
    "                elif mode == 'online_dml':\n"
    "                    peer_logits = peer(xb)\n"
    "                    loss, _, _ = kd_loss(s_logits, peer_logits.detach(), yb, T_TEMP_T, ALPHA_T)\n"
    "                    # Peer learns from student\n"
    "                    peer_loss, _, _ = kd_loss(peer_logits, s_logits.detach(), yb, T_TEMP_T, ALPHA_T)\n"
    "                    opt_peer.zero_grad()\n"
    "                    peer_loss.backward()\n"
    "                    opt_peer.step()\n"
    "                elif mode == 'ema_teacher':\n"
    "                    with torch.no_grad():\n"
    "                        t_logits = ema_teacher(xb)\n"
    "                    loss, _, _ = kd_loss(s_logits, t_logits, yb, T_TEMP_T, ALPHA_T)\n"
    "                    update_ema_teacher(ema_teacher, student, beta=0.999)\n"
    "                else:\n"
    "                    loss = F.cross_entropy(s_logits, yb)\n"
    "\n"
    "                opt.zero_grad()\n"
    "                loss.backward()\n"
    "                opt.step()\n"
    "                ep_loss += loss.item()\n"
    "\n"
    "            train_losses.append(ep_loss / (n // BATCH))\n"
    "            with torch.no_grad():\n"
    "                val_acc = (student(X_val).argmax(1) == y_val).float().mean().item()\n"
    "            val_accs.append(val_acc)\n"
    "    except RuntimeError as e:\n"
    "        if 'out of memory' in str(e).lower():\n"
    "            print(f'OOM in {mode}: reduce BATCH or HIDDEN and retry')\n"
    "            raise\n"
    "        raise\n"
    "\n"
    "    return train_losses, val_accs, val_accs[-1]\n"
    "\n"
    "\n"
    "# First train a teacher\n"
    "teacher_model = StudentNet(IN_F, HIDDEN * 2, N_CLS_T).to(device)  # Larger teacher\n"
    "opt_t = torch.optim.Adam(teacher_model.parameters(), lr=0.005)\n"
    "for ep in range(EPOCHS):\n"
    "    idx = torch.randperm(tr_n)\n"
    "    for start in range(0, tr_n, BATCH):\n"
    "        b = idx[start:start + BATCH]\n"
    "        loss = F.cross_entropy(teacher_model(X_tr_t2[b]), y_tr_t2[b])\n"
    "        opt_t.zero_grad(); loss.backward(); opt_t.step()\n"
    "with torch.no_grad():\n"
    "    teach_final_acc = (teacher_model(X_val_t2).argmax(1) == y_val_t2).float().mean().item()\n"
    "print(f'Teacher val_acc: {teach_final_acc:.3f}')\n"
    "\n"
    "# Run all modes\n"
    "results_kd = {}\n"
    "for mode in ['no_kd', 'offline_kd', 'online_dml', 'ema_teacher']:\n"
    "    torch.manual_seed(42)\n"
    "    tl, va, final = run_training(mode, X_tr_t2, y_tr_t2, X_val_t2, y_val_t2,\n"
    "                                 teacher_net=teacher_model if mode == 'offline_kd' else None)\n"
    "    results_kd[mode] = {'train_losses': tl, 'val_accs': va, 'final_acc': final}\n"
    "    print(f'{mode:20s}: final_val_acc={final:.3f}')\n"
    "\n"
    "print(f'\\nKD variants that beat no-KD student by most: EMA teacher (low overhead, stable soft labels)')\n"
    "print(f'Online DML: peer diversity helps when models develop different representations')\n"
))

# Cell 7: RW Example 1 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 1: Self-Distillation — Deeper Layers Teaching Shallower (Born-Again Networks)\n\n"
    "Implement a 3-tier network where intermediate layer heads predict classes at layers 4, 8, and 12. "
    "The final-layer head acts as the 'teacher'; earlier heads are distilled from it. "
    "Show how self-distillation on a single model (same parameters throughout) improves shallow-layer accuracy.\n"
))

# Cell 8: RW Example 1 code (Code) ~80 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 1: Self-distillation — final layer teaches intermediate layers\n"
    "# Born-Again Networks: student = teacher after one distillation generation\n"
    "\n"
    "class SelfDistillNet(nn.Module):\n"
    "    \"\"\"\n"
    "    12-layer network with exit heads at layers 4, 8, 12.\n"
    "    The final-layer head serves as the 'teacher' for intermediate heads.\n"
    "    \"\"\"\n"
    "    def __init__(self, d_in: int, n_classes: int, n_layers: int = 12):\n"
    "        super().__init__()\n"
    "        self.layers = nn.ModuleList([\n"
    "            nn.Sequential(nn.Linear(d_in, d_in), nn.LayerNorm(d_in), nn.GELU())\n"
    "            for _ in range(n_layers)\n"
    "        ])\n"
    "        # Exit heads at layers 4, 8, 12 (0-indexed: 3, 7, 11)\n"
    "        self.exit_heads = nn.ModuleList([\n"
    "            nn.Linear(d_in, n_classes) for _ in range(3)\n"
    "        ])\n"
    "        self.exit_positions = [3, 7, 11]\n"
    "\n"
    "    def forward_all_exits(\n"
    "        self, x: torch.Tensor\n"
    "    ) -> List[torch.Tensor]:\n"
    "        \"\"\"Returns list of logits at each exit head [layer4, layer8, layer12].\"\"\"\n"
    "        h = x\n"
    "        exit_logits = []\n"
    "        exit_idx = 0\n"
    "        for layer_i in range(len(self.layers)):\n"
    "            h = self.layers[layer_i](h)\n"
    "            if exit_idx < len(self.exit_positions) and layer_i == self.exit_positions[exit_idx]:\n"
    "                exit_logits.append(self.exit_heads[exit_idx](h))\n"
    "                exit_idx += 1\n"
    "        return exit_logits  # [L4_logits, L8_logits, L12_logits]\n"
    "\n"
    "\n"
    "D_SD = 64\n"
    "N_CLS_SD = 6\n"
    "N_SAMP_SD = 500\n"
    "EPOCHS_SD = 60\n"
    "\n"
    "X_sd = torch.randn(N_SAMP_SD, D_SD)\n"
    "y_sd = torch.randint(0, N_CLS_SD, (N_SAMP_SD,))\n"
    "for c in range(N_CLS_SD):\n"
    "    X_sd[y_sd == c, :4] += (c - 2.5) * 0.8\n"
    "X_sd, y_sd = X_sd.to(device), y_sd.to(device)\n"
    "\n"
    "# Train WITHOUT self-distillation (each exit head trained on hard labels independently)\n"
    "net_no_sd = SelfDistillNet(D_SD, N_CLS_SD).to(device)\n"
    "opt_no_sd = torch.optim.Adam(net_no_sd.parameters(), lr=0.003)\n"
    "for ep in range(EPOCHS_SD):\n"
    "    for start in range(0, N_SAMP_SD, 64):\n"
    "        xb, yb = X_sd[start:start+64], y_sd[start:start+64]\n"
    "        all_logits = net_no_sd.forward_all_exits(xb)\n"
    "        loss = sum(F.cross_entropy(lg, yb) for lg in all_logits) / len(all_logits)\n"
    "        opt_no_sd.zero_grad(); loss.backward(); opt_no_sd.step()\n"
    "\n"
    "# Train WITH self-distillation (final head teaches intermediate heads)\n"
    "net_sd = SelfDistillNet(D_SD, N_CLS_SD).to(device)\n"
    "opt_sd = torch.optim.Adam(net_sd.parameters(), lr=0.003)\n"
    "T_SD = 4.0\n"
    "ALPHA_SD = 0.5\n"
    "sd_curves = {'L4': [], 'L8': [], 'L12': []}\n"
    "\n"
    "for ep in range(EPOCHS_SD):\n"
    "    for start in range(0, N_SAMP_SD, 64):\n"
    "        xb, yb = X_sd[start:start+64], y_sd[start:start+64]\n"
    "        all_logits = net_sd.forward_all_exits(xb)   # [L4, L8, L12]\n"
    "        final_logits = all_logits[-1]   # L12 is the 'teacher'\n"
    "        # L4 and L8 distill from L12 (final layer)\n"
    "        loss = F.cross_entropy(final_logits, yb)   # Final layer: hard labels only\n"
    "        for i, lg in enumerate(all_logits[:-1]):\n"
    "            ce_part = F.cross_entropy(lg, yb)\n"
    "            kl_part = F.kl_div(\n"
    "                F.log_softmax(lg / T_SD, dim=-1),\n"
    "                F.softmax(final_logits.detach() / T_SD, dim=-1),\n"
    "                reduction='batchmean',\n"
    "            ) * (T_SD ** 2)\n"
    "            loss += (1 - ALPHA_SD) * ce_part + ALPHA_SD * kl_part\n"
    "        opt_sd.zero_grad(); loss.backward(); opt_sd.step()\n"
    "\n"
    "# Compare accuracy at each exit head\n"
    "net_no_sd.eval(); net_sd.eval()\n"
    "with torch.no_grad():\n"
    "    logits_no = net_no_sd.forward_all_exits(X_sd)\n"
    "    logits_sd = net_sd.forward_all_exits(X_sd)\n"
    "\n"
    "exit_names = ['Layer 4', 'Layer 8', 'Layer 12']\n"
    "print(f'{\"Exit\":12s} {\"No SD Acc\":12s} {\"With SD Acc\":12s} {\"Improvement\":12s}')\n"
    "print('-' * 50)\n"
    "for name, lg_no, lg_sd in zip(exit_names, logits_no, logits_sd):\n"
    "    acc_no = (lg_no.argmax(1) == y_sd).float().mean().item()\n"
    "    acc_sd = (lg_sd.argmax(1) == y_sd).float().mean().item()\n"
    "    print(f'{name:12s} {acc_no:<12.3f} {acc_sd:<12.3f} {acc_sd-acc_no:+.3f}')\n"
    "\n"
    "print('\\nSelf-distillation improves intermediate heads; final head unaffected (trained on hard labels).')\n"
    "print('This enables early exit with higher accuracy than training heads independently.')\n"
))

# Cell 9: RW Example 2 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 2: Data-Free Knowledge Distillation\n\n"
    "Distill a trained teacher without access to original training data. "
    "Generate pseudo-data by optimizing random noise to maximize teacher activation (DeepDream style). "
    "Distill the student on this pseudo-data using soft teacher labels.\n"
))

# Cell 10: RW Example 2 code (Code) ~80 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 2: Data-free KD — generate pseudo-data to maximize teacher activations\n"
    "# Inspired by DeepInversion / ZSKD: optimize random noise to look like natural data for the teacher\n"
    "\n"
    "def generate_pseudo_data(\n"
    "    teacher: nn.Module,\n"
    "    target_class: int,\n"
    "    d_in: int,\n"
    "    n_samples: int = 32,\n"
    "    n_steps: int = 100,\n"
    "    lr: float = 0.05,\n"
    ") -> torch.Tensor:\n"
    "    \"\"\"\n"
    "    Optimize random noise to maximize teacher's softmax probability for target_class.\n"
    "    Returns optimized pseudo-samples of shape (n_samples, d_in).\n"
    "    \"\"\"\n"
    "    teacher.eval()\n"
    "    # Start from random noise\n"
    "    x_pseudo = nn.Parameter(torch.randn(n_samples, d_in, device=device) * 0.1)\n"
    "    opt_pseudo = torch.optim.Adam([x_pseudo], lr=lr)\n"
    "\n"
    "    for step in range(n_steps):\n"
    "        teacher_logits = teacher(x_pseudo)\n"
    "        # Maximize probability for target class (minimize negative log-prob)\n"
    "        loss = F.cross_entropy(\n"
    "            teacher_logits,\n"
    "            torch.full((n_samples,), target_class, dtype=torch.long, device=device)\n"
    "        )\n"
    "        # Regularization: keep pseudo-data close to unit Gaussian (prevents degenerate values)\n"
    "        loss += 0.01 * x_pseudo.norm()\n"
    "        opt_pseudo.zero_grad()\n"
    "        loss.backward()\n"
    "        opt_pseudo.step()\n"
    "\n"
    "    return x_pseudo.detach()\n"
    "\n"
    "\n"
    "# Generate pseudo-data for each class\n"
    "N_CLS_DF = N_CLS_T\n"
    "N_PSEUDO_PER_CLASS = 40\n"
    "\n"
    "print(f'Generating pseudo-data ({N_PSEUDO_PER_CLASS} samples/class x {N_CLS_DF} classes)...')\n"
    "pseudo_X_list, pseudo_y_list = [], []\n"
    "\n"
    "for cls in range(N_CLS_DF):\n"
    "    pseudo = generate_pseudo_data(\n"
    "        teacher_model, target_class=cls,\n"
    "        d_in=IN_F, n_samples=N_PSEUDO_PER_CLASS, n_steps=80,\n"
    "    )\n"
    "    pseudo_X_list.append(pseudo)\n"
    "    pseudo_y_list.append(torch.full((N_PSEUDO_PER_CLASS,), cls, dtype=torch.long, device=device))\n"
    "\n"
    "pseudo_X = torch.cat(pseudo_X_list, dim=0)\n"
    "pseudo_y = torch.cat(pseudo_y_list, dim=0)\n"
    "print(f'Pseudo dataset: {pseudo_X.shape} (teacher confidence check follows)')\n"
    "\n"
    "# Verify teacher confidence on pseudo-data (should be high for generated class)\n"
    "teacher_model.eval()\n"
    "with torch.no_grad():\n"
    "    pseudo_logits = teacher_model(pseudo_X)\n"
    "    pseudo_preds  = pseudo_logits.argmax(1)\n"
    "    pseudo_conf   = F.softmax(pseudo_logits, dim=-1).max(1).values\n"
    "pseudo_acc = (pseudo_preds == pseudo_y).float().mean().item()\n"
    "print(f'Teacher accuracy on pseudo-data: {pseudo_acc:.3f}')\n"
    "print(f'Teacher avg confidence on pseudo-data: {pseudo_conf.mean().item():.3f}')\n"
    "\n"
    "# Distill student on pseudo-data using teacher soft labels\n"
    "torch.manual_seed(42)\n"
    "student_df = StudentNet(IN_F, HIDDEN, N_CLS_T).to(device)\n"
    "opt_df = torch.optim.Adam(student_df.parameters(), lr=0.005)\n"
    "\n"
    "for ep in range(80):\n"
    "    idx = torch.randperm(len(pseudo_X))\n"
    "    for start in range(0, len(pseudo_X), 32):\n"
    "        b = idx[start:start+32]\n"
    "        xb, yb = pseudo_X[b], pseudo_y[b]\n"
    "        with torch.no_grad():\n"
    "            t_logits = teacher_model(xb)\n"
    "        s_logits = student_df(xb)\n"
    "        loss, _, _ = kd_loss(s_logits, t_logits, yb, T=T_TEMP_T, alpha=ALPHA_T)\n"
    "        opt_df.zero_grad(); loss.backward(); opt_df.step()\n"
    "\n"
    "# Evaluate on real validation data\n"
    "student_df.eval()\n"
    "with torch.no_grad():\n"
    "    df_val_acc = (student_df(X_val_t2).argmax(1) == y_val_t2).float().mean().item()\n"
    "print(f'\\nData-free KD student val_acc (real data): {df_val_acc:.3f}')\n"
    "print(f'Comparison: no-KD={results_kd[\"no_kd\"][\"final_acc\"]:.3f}, '\n"
    "      f'offline-KD={results_kd[\"offline_kd\"][\"final_acc\"]:.3f}')\n"
    "print('Data-free KD accuracy depends on pseudo-data quality; works best when teacher is confident')\n"
))

# Cell 11: RW Example 3 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 3: Continual Distillation — Distill New Task Without Forgetting Old\n\n"
    "Combine knowledge distillation with continual learning: distill a new task into a student "
    "while preventing forgetting of an old task using an EWC-like penalty on the distillation loss. "
    "Measure forward transfer (new task accuracy) and backward transfer (old task retention).\n"
))

# Cell 12: RW Example 3 code (Code) ~80 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 3: Continual distillation — new task + old task retention\n"
    "# Old teacher provides soft labels for old task; EWC-like penalty on shared parameters\n"
    "\n"
    "def train_task(\n"
    "    model: nn.Module,\n"
    "    X_tr: torch.Tensor, y_tr: torch.Tensor,\n"
    "    epochs: int = 60, lr: float = 0.005\n"
    ") -> nn.Module:\n"
    "    \"\"\"Train model on a task with hard labels.\"\"\"\n"
    "    opt = torch.optim.Adam(model.parameters(), lr=lr)\n"
    "    model.train()\n"
    "    for ep in range(epochs):\n"
    "        idx = torch.randperm(len(X_tr))\n"
    "        for start in range(0, len(X_tr), 64):\n"
    "            b = idx[start:start+64]\n"
    "            loss = F.cross_entropy(model(X_tr[b]), y_tr[b])\n"
    "            opt.zero_grad(); loss.backward(); opt.step()\n"
    "    return model\n"
    "\n"
    "\n"
    "def compute_fisher(\n"
    "    model: nn.Module, X: torch.Tensor, y: torch.Tensor\n"
    ") -> Dict[str, torch.Tensor]:\n"
    "    \"\"\"Approximate Fisher information (parameter importance) for EWC.\"\"\"\n"
    "    fisher = {n: torch.zeros_like(p) for n, p in model.named_parameters()}\n"
    "    model.eval()\n"
    "    for xi, yi in zip(X[:100], y[:100]):   # Sample 100 points\n"
    "        model.zero_grad()\n"
    "        logit = model(xi.unsqueeze(0))\n"
    "        loss = F.cross_entropy(logit, yi.unsqueeze(0))\n"
    "        loss.backward()\n"
    "        for n, p in model.named_parameters():\n"
    "            if p.grad is not None:\n"
    "                fisher[n] += p.grad.data.pow(2)\n"
    "    for n in fisher:\n"
    "        fisher[n] /= 100\n"
    "    return fisher\n"
    "\n"
    "\n"
    "# Task A: 4-class classification (first task)\n"
    "IN_F_CL = 16\n"
    "N_CLS_A, N_CLS_B = 4, 4\n"
    "N_CL = 400\n"
    "\n"
    "X_A = torch.randn(N_CL, IN_F_CL)\n"
    "y_A = torch.randint(0, N_CLS_A, (N_CL,))\n"
    "X_A[y_A == 0, :2] += 1.5; X_A[y_A == 1, :2] -= 1.5\n"
    "X_A[y_A == 2, 2:4] += 1.5; X_A[y_A == 3, 2:4] -= 1.5\n"
    "\n"
    "# Task B: different 4-class classification (second task)\n"
    "X_B = torch.randn(N_CL, IN_F_CL)\n"
    "y_B = torch.randint(0, N_CLS_B, (N_CL,))\n"
    "X_B[y_B == 0, 4:6] += 1.5; X_B[y_B == 1, 4:6] -= 1.5\n"
    "X_B[y_B == 2, 6:8] += 1.5; X_B[y_B == 3, 6:8] -= 1.5\n"
    "\n"
    "X_A, y_A = X_A.to(device), y_A.to(device)\n"
    "X_B, y_B = X_B.to(device), y_B.to(device)\n"
    "\n"
    "# Step 1: Train teacher on Task A\n"
    "torch.manual_seed(42)\n"
    "teacher_A = StudentNet(IN_F_CL, 64, N_CLS_A).to(device)\n"
    "teacher_A = train_task(teacher_A, X_A, y_A, epochs=60)\n"
    "old_params = {n: p.clone().detach() for n, p in teacher_A.named_parameters()}\n"
    "fisher_A = compute_fisher(teacher_A, X_A, y_A)\n"
    "\n"
    "acc_A_before = (teacher_A(X_A).argmax(1) == y_A).float().mean().item()\n"
    "print(f'Teacher A (Task A) acc before Task B training: {acc_A_before:.3f}')\n"
    "\n"
    "# Step 2: Continual distillation — fine-tune teacher on Task B with EWC penalty\n"
    "EWC_LAMBDA = 100.0\n"
    "opt_cont = torch.optim.Adam(teacher_A.parameters(), lr=0.003)\n"
    "\n"
    "for ep in range(60):\n"
    "    idx = torch.randperm(N_CL)\n"
    "    for start in range(0, N_CL, 64):\n"
    "        b = idx[start:start+64]\n"
    "        xb, yb = X_B[b], y_B[b]\n"
    "        logits_B = teacher_A(xb)   # Now learning Task B\n"
    "        task_loss = F.cross_entropy(logits_B, yb)\n"
    "        # EWC penalty: preserve important parameters for Task A\n"
    "        ewc_loss = torch.tensor(0.0, device=device)\n"
    "        for n, p in teacher_A.named_parameters():\n"
    "            ewc_loss += (fisher_A[n] * (p - old_params[n]).pow(2)).sum()\n"
    "        loss = task_loss + (EWC_LAMBDA / 2) * ewc_loss\n"
    "        opt_cont.zero_grad(); loss.backward(); opt_cont.step()\n"
    "\n"
    "acc_A_after = (teacher_A(X_A).argmax(1) == y_A).float().mean().item()\n"
    "acc_B_after = (teacher_A(X_B).argmax(1) == y_B).float().mean().item()\n"
    "\n"
    "print(f'After continual training on Task B:')\n"
    "print(f'  Task A retention (backward transfer): {acc_A_after:.3f} (was {acc_A_before:.3f})')\n"
    "print(f'  Task B accuracy (forward transfer):   {acc_B_after:.3f}')\n"
    "print(f'  Forgetting rate: {acc_A_before - acc_A_after:.3f}')\n"
    "print(f'\\nEWC penalty (lambda={EWC_LAMBDA}) preserves Task A knowledge while learning Task B.')\n"
    "print(f'Without EWC, catastrophic forgetting would reduce Task A acc to near-random.')\n"
))

# Cell 13: Comparison header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Comparison: Accuracy Bar Chart — All KD Variants\n\n"
    "Bar chart comparing teacher, student (no KD), offline KD, online DML, EMA teacher, "
    "self-distillation, and data-free KD final validation accuracy.\n"
))

# Cell 14: Comparison code + matplotlib (Code) ~55 lines
cells.append(nbformat.v4.new_code_cell(
    "# Comparison: accuracy bar chart for all KD variants\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
    "\n"
    "# --- Plot 1: Accuracy comparison bar chart ---\n"
    "kd_methods = [\n"
    "    'Teacher',\n"
    "    'Student\\n(no KD)',\n"
    "    'Offline KD',\n"
    "    'Online DML',\n"
    "    'EMA Teacher',\n"
    "    'Data-Free KD',\n"
    "]\n"
    "kd_accs = [\n"
    "    teach_final_acc,\n"
    "    results_kd['no_kd']['final_acc'],\n"
    "    results_kd['offline_kd']['final_acc'],\n"
    "    results_kd['online_dml']['final_acc'],\n"
    "    results_kd['ema_teacher']['final_acc'],\n"
    "    df_val_acc,\n"
    "]\n"
    "bar_colors = ['#2d7cc1', '#e05c5c', '#55a868', '#55a868', '#55a868', '#dd8452']\n"
    "\n"
    "bars = axes[0].bar(kd_methods, kd_accs, color=bar_colors, edgecolor='navy', linewidth=0.8)\n"
    "axes[0].axhline(results_kd['no_kd']['final_acc'], color='red', linestyle='--',\n"
    "                alpha=0.7, label='Student (no KD) baseline')\n"
    "axes[0].axhline(teach_final_acc, color='steelblue', linestyle='--',\n"
    "                alpha=0.7, label='Teacher upper bound')\n"
    "for bar, acc in zip(bars, kd_accs):\n"
    "    axes[0].text(bar.get_x() + bar.get_width()/2, acc + 0.003,\n"
    "                 f'{acc:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')\n"
    "axes[0].set_ylabel('Validation Accuracy')\n"
    "axes[0].set_title('KD Variant Accuracy Comparison', fontsize=12, fontweight='bold')\n"
    "axes[0].legend(fontsize=8)\n"
    "axes[0].set_ylim(max(0, min(kd_accs) - 0.05), min(1.0, max(kd_accs) + 0.04))\n"
    "\n"
    "# --- Plot 2: Training curves (val accuracy over epochs) ---\n"
    "colors_line = {'no_kd': 'red', 'offline_kd': 'navy', 'online_dml': 'green', 'ema_teacher': 'darkorange'}\n"
    "for mode, col in colors_line.items():\n"
    "    val_accs_curve = results_kd[mode]['val_accs']\n"
    "    axes[1].plot(range(len(val_accs_curve)), val_accs_curve,\n"
    "                 color=col, linewidth=2, alpha=0.9, label=mode)\n"
    "\n"
    "axes[1].set_xlabel('Training Epoch')\n"
    "axes[1].set_ylabel('Validation Accuracy')\n"
    "axes[1].set_title('Convergence Curves: KD Variants', fontsize=12, fontweight='bold')\n"
    "axes[1].legend(fontsize=9)\n"
    "\n"
    "plt.suptitle('Online Knowledge Distillation: Method Comparison', fontsize=13, fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/kd_comparison.png', dpi=120, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved comparison chart to /tmp/kd_comparison.png')\n"
))

# Cell 15: Key Takeaways (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Key Takeaways\n\n"
    "**Core idea:** Knowledge distillation trains a student to match a teacher's full probability "
    "distribution (not just hard labels), transferring 'dark knowledge' — the teacher's uncertainty "
    "about wrong answers that encodes inter-class relationships. Online KD removes the need for a "
    "pre-trained frozen teacher by co-training teacher and student.\n\n"
    "### KD Variant Comparison\n\n"
    "| Method | Teacher Cost | Accuracy | Training Time | Best For |\n"
    "|---|---|---|---|---|\n"
    "| Offline KD (frozen teacher) | 1x (pre-computed) | +2-4% vs no-KD | 1.3x | Small target model, teacher available |\n"
    "| Online KD (co-training) | 1x (live) | +3-5% | 2x | No pre-trained teacher |\n"
    "| EMA Teacher | ~0% overhead | +3-4% | 1.1x | Most practical online approach |\n"
    "| DML (mutual learning) | 1x symmetric | +2-5% | 2x | Two peer models, want both improved |\n"
    "| Self-distillation / BAN | 1x per gen | +2-4% | 2x | Single architecture, iterative improvement |\n"
    "| Data-free KD | 0 (no data needed) | +1-3% | 1.5x | No original data access |\n\n"
    "### Common Failure Modes\n\n"
    "| Failure | Symptom | Fix |\n"
    "|---|---|---|\n"
    "| No teacher warmup | KD student worse than no-KD baseline | Warm up teacher 2-3 epochs; ramp alpha 0→0.3 |\n"
    "| Missing T^2 scaling | KD loss has no effect on training | Add T^2 multiplier to KL term |\n"
    "| DML peer collapse | One peer dominates, other stagnates | Asymmetric alpha; entropy regularization |\n"
    "| Online teacher worse than frozen | Online KD < offline KD | Use EMA teacher (best of both) or offline if strong teacher available |\n\n"
    "### Related Concepts\n"
    "- [46-neuron-importance-scoring.ipynb](./46-neuron-importance-scoring.ipynb) — pruning and distillation are complementary compression techniques\n"
    "- [17-continual-learning-llms.ipynb](./17-continual-learning-llms.ipynb) — online distillation supports continual learning\n"
    "- [26-mixture-of-experts.ipynb](./26-mixture-of-experts.ipynb) — MoE models can be distilled into dense students\n"
))

# Cell 16: Exercises (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Exercises\n\n"
    "1. **Modify Level 1:** Sweep temperature T from 1 to 20. At what T does KL loss start to "
    "provide better accuracy than hard labels alone? At what T does over-smoothing hurt?\n"
    "2. **Extend Level 2:** Implement EMA teacher with beta values {0.9, 0.99, 0.999}. "
    "Plot convergence speed vs final accuracy. Which beta gives the best trade-off?\n"
    "3. **Debug Example 2:** Data-free KD with only 10 steps of pseudo-data generation (vs 80). "
    "How does teacher confidence and student accuracy change? Is there a minimum step count?\n"
    "4. **Combine concepts:** Combine online DML (two peers) with self-distillation (intermediate exit heads). "
    "Each peer distills from both the other peer AND its own final-layer head. "
    "Does this combined approach improve convergence speed?\n"
))

# Build notebook
nb = nbformat.v4.new_notebook()
nb.cells = cells
nbformat.write(nb, NB_PATH)
print(f'Written: {NB_PATH} ({len(cells)} cells)')
