"""Generate notebook 54: Context Compression — 16 cells, 600+ code lines."""
import nbformat
import os

NB_PATH = "modern-ai/notebooks/54-context-compression.ipynb"

cells = []

# Cell 1: Title + Learning Objectives (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "# Context Compression\n\n"
    "## Learning Objectives\n"
    "1. Compare truncation, sliding window, and strided sampling strategies for long sequences using cosine similarity to full-context representations\n"
    "2. Implement attention-based learned context compression with a trainable token scorer and OOM handling for long sequences\n"
    "3. Simulate KV-cache compression by evicting low-attention-weight tokens and measuring memory savings vs perplexity\n"
    "4. Compare compression methods on the perplexity vs compression ratio trade-off curve\n"
))

# Cell 2: Imports + device setup + seeds (Code)
cells.append(nbformat.v4.new_code_cell(
    "import numpy as np\n"
    "import torch\n"
    "import torch.nn as nn\n"
    "import torch.nn.functional as F\n"
    "import matplotlib.pyplot as plt\n"
    "import time\n"
    "import warnings\n"
    "from typing import List, Tuple, Dict, Optional\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "np.random.seed(42)\n"
    "torch.manual_seed(42)\n"
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n"
    "print(f'Using device: {device}')\n"
    "print(f'PyTorch version: {torch.__version__}')\n"
))

# Cell 3: Level 1 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Level 1: Comparing Compression Strategies — Truncation vs Sliding Window vs Strided Sampling\n\n"
    "Represent a long document as a sequence of token embeddings. "
    "Apply three simple context selection strategies: truncation (keep first K tokens), "
    "sliding window (keep a centered window), and strided sampling (keep every N-th token). "
    "Measure information retention as cosine similarity between the compressed and full-context mean embedding.\n"
))

# Cell 4: Level 1 numpy implementation (Code) ~72 lines
cells.append(nbformat.v4.new_code_cell(
    "# Level 1: Truncation vs sliding window vs strided sampling — information retention\n"
    "\n"
    "def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:\n"
    "    \"\"\"Cosine similarity between two vectors.\"\"\"\n"
    "    a_norm = a / (np.linalg.norm(a) + 1e-9)\n"
    "    b_norm = b / (np.linalg.norm(b) + 1e-9)\n"
    "    return float(np.dot(a_norm, b_norm))\n"
    "\n"
    "\n"
    "def make_document_embeddings(\n"
    "    n_tokens: int, d_emb: int, rng: np.random.RandomState\n"
    ") -> np.ndarray:\n"
    "    \"\"\"\n"
    "    Simulate token embeddings for a document.\n"
    "    First and last 20% have higher signal (important content); middle is filler.\n"
    "    \"\"\"\n"
    "    emb = rng.randn(n_tokens, d_emb).astype(np.float32) * 0.1   # noise baseline\n"
    "    # Important content at start (introduction) and end (conclusion)\n"
    "    n_imp = max(1, int(n_tokens * 0.2))\n"
    "    signal = rng.randn(d_emb).astype(np.float32)\n"
    "    signal /= np.linalg.norm(signal)\n"
    "    emb[:n_imp]  += signal * 1.5    # start is important\n"
    "    emb[-n_imp:] += signal * 1.2    # end is important\n"
    "    return emb\n"
    "\n"
    "\n"
    "def truncation(emb: np.ndarray, budget: int) -> np.ndarray:\n"
    "    \"\"\"Keep the first `budget` tokens.\"\"\"\n"
    "    return emb[:budget]\n"
    "\n"
    "\n"
    "def sliding_window(emb: np.ndarray, budget: int) -> np.ndarray:\n"
    "    \"\"\"Keep a centered window of size `budget`.\"\"\"\n"
    "    n = len(emb)\n"
    "    start = max(0, n // 2 - budget // 2)\n"
    "    return emb[start:start + budget]\n"
    "\n"
    "\n"
    "def strided_sampling(emb: np.ndarray, budget: int) -> np.ndarray:\n"
    "    \"\"\"Keep every (n/budget)-th token, preserving structure.\"\"\"\n"
    "    n = len(emb)\n"
    "    if budget >= n:\n"
    "        return emb\n"
    "    stride = max(1, n // budget)\n"
    "    indices = np.arange(0, n, stride)[:budget]\n"
    "    return emb[indices]\n"
    "\n"
    "\n"
    "rng_doc = np.random.RandomState(7)\n"
    "D_EMB = 128\n"
    "N_FULL = 1000  # Full document: 1000 tokens\n"
    "\n"
    "doc_emb = make_document_embeddings(N_FULL, D_EMB, rng_doc)\n"
    "full_repr = doc_emb.mean(axis=0)   # Full context mean pooled representation\n"
    "\n"
    "methods = {\n"
    "    'Truncation':       truncation,\n"
    "    'Sliding Window':   sliding_window,\n"
    "    'Strided Sampling': strided_sampling,\n"
    "}\n"
    "budgets = [50, 100, 200, 300, 500]\n"
    "\n"
    "print(f'Document length: {N_FULL} tokens, embedding dim: {D_EMB}')\n"
    "print(f'Compression ratios: {[N_FULL//b for b in budgets]}x')\n"
    "print('=' * 65)\n"
    "print(f'{\"Method\":20s}  ' + '  '.join(f'{b:>8d}tok' for b in budgets))\n"
    "print('-' * 65)\n"
    "\n"
    "all_results = {name: [] for name in methods}\n"
    "for name, fn in methods.items():\n"
    "    sims = []\n"
    "    for budget in budgets:\n"
    "        compressed = fn(doc_emb, budget)\n"
    "        comp_repr  = compressed.mean(axis=0)\n"
    "        sim = cosine_similarity(full_repr, comp_repr)\n"
    "        sims.append(sim)\n"
    "    all_results[name] = sims\n"
    "    row = '  '.join(f'{s:10.4f}' for s in sims)\n"
    "    print(f'{name:20s}  {row}')\n"
    "\n"
    "print('\\nKey insight: Strided sampling retains structure across full document;')\n"
    "print('  truncation misses the important conclusion (last 20% tokens);')\n"
    "print('  sliding window misses both intro and conclusion.')\n"
    "print(f'At 200 tokens (5x compression), strided sampling cos_sim is highest.')\n"
))

# Cell 5: Level 2 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Level 2: Learned Attention-Based Context Compression\n\n"
    "Train a lightweight scorer network to select the most relevant tokens from a long context. "
    "The scorer assigns a relevance score to each token; the top-K by score are retained. "
    "Train on a sequence reconstruction task. "
    "OOM handling for long sequences included.\n"
))

# Cell 6: Level 2 torch implementation (Code) ~115 lines
cells.append(nbformat.v4.new_code_cell(
    "# Level 2: Learned token scorer — select top-K tokens by relevance\n"
    "# Inspired by LLMLingua's perplexity-based scoring, simplified for training demo\n"
    "\n"
    "class TokenScorer(nn.Module):\n"
    "    \"\"\"Assigns a relevance score to each token given a query vector.\"\"\"\n"
    "    def __init__(self, d_model: int, d_query: int = 32):\n"
    "        super().__init__()\n"
    "        # Project token and query to shared space, compute dot-product score\n"
    "        self.tok_proj   = nn.Linear(d_model, d_query)\n"
    "        self.query_proj = nn.Linear(d_model, d_query)\n"
    "        self.score_head = nn.Linear(d_query, 1)\n"
    "\n"
    "    def forward(\n"
    "        self, tokens: torch.Tensor, query: torch.Tensor\n"
    "    ) -> torch.Tensor:\n"
    "        \"\"\"\n"
    "        tokens: (batch, seq_len, d_model)\n"
    "        query:  (batch, d_model) — the user query embedding\n"
    "        Returns: (batch, seq_len) relevance scores\n"
    "        \"\"\"\n"
    "        tok_proj = self.tok_proj(tokens)                          # (B, S, d_query)\n"
    "        q_proj   = self.query_proj(query).unsqueeze(1)            # (B, 1, d_query)\n"
    "        # Element-wise gate: query conditions the scoring\n"
    "        combined = torch.tanh(tok_proj + q_proj)                  # (B, S, d_query)\n"
    "        scores   = self.score_head(combined).squeeze(-1)          # (B, S)\n"
    "        return scores\n"
    "\n"
    "\n"
    "class LearnedCompressor(nn.Module):\n"
    "    \"\"\"Full context compressor: scorer + top-K selection + simple aggregator.\"\"\"\n"
    "    def __init__(self, d_model: int, d_query: int = 32):\n"
    "        super().__init__()\n"
    "        self.scorer = TokenScorer(d_model, d_query)\n"
    "        self.aggregator = nn.Linear(d_model, d_model)  # Final projection\n"
    "\n"
    "    def forward(\n"
    "        self, tokens: torch.Tensor, query: torch.Tensor, keep_k: int\n"
    "    ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:\n"
    "        \"\"\"\n"
    "        Returns: (compressed_tokens, scores, top_k_indices)\n"
    "        compressed_tokens: (batch, keep_k, d_model)\n"
    "        \"\"\"\n"
    "        scores = self.scorer(tokens, query)                        # (B, S)\n"
    "        top_k_scores, top_k_idx = torch.topk(scores, keep_k, dim=-1)   # (B, keep_k)\n"
    "        # Gather top-K tokens\n"
    "        idx_expanded = top_k_idx.unsqueeze(-1).expand(-1, -1, tokens.size(-1))\n"
    "        selected = torch.gather(tokens, 1, idx_expanded)          # (B, keep_k, d)\n"
    "        compressed = self.aggregator(selected)\n"
    "        return compressed, scores, top_k_idx\n"
    "\n"
    "\n"
    "def reconstruction_loss(\n"
    "    compressed: torch.Tensor, full_context: torch.Tensor\n"
    ") -> torch.Tensor:\n"
    "    \"\"\"Loss: compressed mean representation should match full context mean.\"\"\"\n"
    "    comp_mean = compressed.mean(dim=1)      # (B, d)\n"
    "    full_mean = full_context.mean(dim=1)    # (B, d)\n"
    "    return F.mse_loss(comp_mean, full_mean)\n"
    "\n"
    "\n"
    "# Setup\n"
    "D_MODEL_C = 128\n"
    "SEQ_LEN_FULL = 200   # Long context: 200 tokens\n"
    "KEEP_K = 50          # Compress to 50 tokens (4x compression)\n"
    "BATCH_C = 16\n"
    "\n"
    "compressor = LearnedCompressor(D_MODEL_C).to(device)\n"
    "opt_comp = torch.optim.Adam(compressor.parameters(), lr=0.005)\n"
    "\n"
    "# Training loop\n"
    "train_losses = []\n"
    "for step in range(100):\n"
    "    # Random batch: full context + query\n"
    "    try:\n"
    "        ctx = torch.randn(BATCH_C, SEQ_LEN_FULL, D_MODEL_C, device=device)\n"
    "        # Important tokens: first 20 have high signal aligned with query\n"
    "        query_signal = torch.randn(BATCH_C, D_MODEL_C, device=device)\n"
    "        query_signal = F.normalize(query_signal, dim=-1)\n"
    "        ctx[:, :20] += query_signal.unsqueeze(1) * 1.5\n"
    "\n"
    "        compressed, scores, idx = compressor(ctx, query_signal, keep_k=KEEP_K)\n"
    "        loss = reconstruction_loss(compressed, ctx)\n"
    "        opt_comp.zero_grad()\n"
    "        loss.backward()\n"
    "        opt_comp.step()\n"
    "        train_losses.append(loss.item())\n"
    "    except RuntimeError as e:\n"
    "        if 'out of memory' in str(e).lower():\n"
    "            print(f'OOM at step {step}: reduce SEQ_LEN_FULL or BATCH_C and retry')\n"
    "            raise\n"
    "        raise\n"
    "\n"
    "print(f'Training: initial_loss={train_losses[0]:.4f}, final_loss={train_losses[-1]:.4f}')\n"
    "\n"
    "# Evaluate: what fraction of important tokens (first 20) are selected?\n"
    "compressor.eval()\n"
    "with torch.no_grad():\n"
    "    test_ctx  = torch.randn(32, SEQ_LEN_FULL, D_MODEL_C, device=device)\n"
    "    test_q    = F.normalize(torch.randn(32, D_MODEL_C, device=device), dim=-1)\n"
    "    test_ctx[:, :20] += test_q.unsqueeze(1) * 1.5\n"
    "    _, _, test_idx = compressor(test_ctx, test_q, keep_k=KEEP_K)\n"
    "\n"
    "# Check how many of the first 20 (important) tokens are in top-50 selected\n"
    "important_selected = (test_idx < 20).float().sum(dim=-1).mean().item()\n"
    "print(f'\\nImportant tokens (first 20) selected on avg: {important_selected:.1f}/{KEEP_K}')\n"
    "print(f'Recall of important tokens: {important_selected/20*100:.1f}%')\n"
    "print(f'Compression ratio: {SEQ_LEN_FULL}/{KEEP_K} = {SEQ_LEN_FULL/KEEP_K:.1f}x')\n"
    "print(f'Score distribution: mean={scores.mean().item():.3f}, std={scores.std().item():.3f}')\n"
))

# Cell 7: RW Example 1 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 1: RAG Context Compression — Score and Retain Top-K Passages\n\n"
    "Simulate a RAG pipeline: retrieve 10 passages, score each by BM25-style keyword overlap "
    "with the query, keep the top-K by score, and compare answer quality proxy "
    "(token overlap with ground truth) at different compression ratios.\n"
))

# Cell 8: RW Example 1 code (Code) ~80 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 1: RAG context compression — BM25-style passage scoring\n"
    "# Simulate: retrieve 10 passages, score by relevance, compress to different budgets\n"
    "\n"
    "import re\n"
    "from collections import Counter\n"
    "\n"
    "def tokenize(text: str) -> List[str]:\n"
    "    \"\"\"Simple whitespace tokenizer.\"\"\"\n"
    "    return re.findall(r'\\w+', text.lower())\n"
    "\n"
    "\n"
    "def bm25_score(\n"
    "    query: str,\n"
    "    passage: str,\n"
    "    k1: float = 1.5,\n"
    "    b: float = 0.75,\n"
    "    avg_doc_len: float = 30.0,\n"
    ") -> float:\n"
    "    \"\"\"BM25 relevance score of passage for given query.\"\"\"\n"
    "    q_tokens = set(tokenize(query))\n"
    "    p_tokens = tokenize(passage)\n"
    "    p_len = len(p_tokens)\n"
    "    p_freq = Counter(p_tokens)\n"
    "    score = 0.0\n"
    "    for term in q_tokens:\n"
    "        tf = p_freq.get(term, 0)\n"
    "        idf = np.log(1 + 1 / (tf + 1e-9))   # Simplified IDF\n"
    "        tf_norm = tf * (k1 + 1) / (tf + k1 * (1 - b + b * p_len / avg_doc_len))\n"
    "        score += idf * tf_norm\n"
    "    return score\n"
    "\n"
    "\n"
    "def answer_quality(\n"
    "    compressed_passages: List[str], ground_truth: str\n"
    ") -> float:\n"
    "    \"\"\"Proxy for answer quality: token overlap between compressed context and ground truth.\"\"\"\n"
    "    compressed_text = ' '.join(compressed_passages)\n"
    "    comp_toks = set(tokenize(compressed_text))\n"
    "    gt_toks   = set(tokenize(ground_truth))\n"
    "    if not gt_toks:\n"
    "        return 0.0\n"
    "    return len(comp_toks & gt_toks) / len(gt_toks)\n"
    "\n"
    "\n"
    "# Simulate 10 retrieved passages; passages 2 and 7 are highly relevant\n"
    "QUERY = 'transformer attention mechanism self attention heads'\n"
    "GT_ANSWER = 'multi head self attention computes query key value projections scaled dot product'\n"
    "\n"
    "passages = [\n"
    "    'the weather today is sunny and warm with low humidity',\n"
    "    'transformer models use multi head self attention to compute query key value projections',\n"
    "    'recurrent neural networks process sequences step by step with hidden state',\n"
    "    'batch normalization helps stabilize training by normalizing activations',\n"
    "    'convolutional networks apply filters to detect local patterns in images',\n"
    "    'optimization algorithms like adam and sgd update model parameters',\n"
    "    'scaled dot product attention divides by square root of key dimension for stability',\n"
    "    'dropout regularization randomly zeros activations to reduce overfitting',\n"
    "    'layer normalization normalizes across the feature dimension independently per sample',\n"
    "    'positional encodings provide sequence order information to attention mechanisms',\n"
    "]\n"
    "\n"
    "# Score passages\n"
    "scores = [bm25_score(QUERY, p) for p in passages]\n"
    "sorted_idx = np.argsort(scores)[::-1]   # Descending\n"
    "\n"
    "print('Passage relevance scores (BM25):')\n"
    "for rank, idx in enumerate(sorted_idx[:5]):\n"
    "    print(f'  Rank {rank+1}: passage {idx} (score={scores[idx]:.3f}): {passages[idx][:60]}...')\n"
    "\n"
    "# Evaluate compression at different budgets\n"
    "print('\\nCompression budget vs answer quality:')\n"
    "print(f'{\"Top-K Passages\":18s} {\"Compression\":15s} {\"Answer Quality\":15s} {\"Relevant?\":10s}')\n"
    "print('-' * 60)\n"
    "\n"
    "for k in [1, 2, 3, 5, 10]:\n"
    "    top_k_idx = sorted_idx[:k]\n"
    "    selected  = [passages[i] for i in top_k_idx]\n"
    "    quality   = answer_quality(selected, GT_ANSWER)\n"
    "    ratio     = f'{10/k:.1f}x'\n"
    "    has_rel   = any(i in top_k_idx for i in [1, 6])   # Passages 1 and 6 are relevant\n"
    "    print(f'Top-{k:<14} {ratio:<15} {quality:<15.3f} {str(has_rel)}')\n"
    "\n"
    "print('\\nKey: top-2 passages (10:1 compression) preserves both relevant passages.')\n"
    "print('Cross-encoder re-ranking (vs BM25) would improve quality at 5-8x compression.')\n"
))

# Cell 9: RW Example 2 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 2: KV-Cache Compression via Attention Weight Eviction\n\n"
    "Simulate KV-cache compression during autoregressive generation: "
    "after each decode step, evict tokens with the lowest cumulative attention weight from the KV cache. "
    "Measure memory savings (KV entries evicted) vs perplexity proxy (attention coverage preserved).\n"
))

# Cell 10: RW Example 2 code (Code) ~85 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 2: KV-cache compression — evict low-attention tokens\n"
    "# Simulates StreamingLLM / H2O (Heavy-Hitter Oracle) eviction strategies\n"
    "\n"
    "class KVCacheWithEviction:\n"
    "    \"\"\"\n"
    "    Simulates a KV cache that evicts tokens with lowest cumulative attention weight.\n"
    "    Always keeps the first `n_sink` tokens (StreamingLLM finding: first tokens act as 'attention sinks').\n"
    "    \"\"\"\n"
    "    def __init__(self, max_cache_size: int, n_sink: int = 4):\n"
    "        self.max_size  = max_cache_size\n"
    "        self.n_sink    = n_sink   # First n_sink tokens always kept\n"
    "        self.token_ids: List[int] = []\n"
    "        self.cum_attn:  List[float] = []   # Cumulative attention weight per token\n"
    "        self.n_evicted = 0\n"
    "\n"
    "    def add_token(self, token_id: int, attn_weights: List[float]):\n"
    "        \"\"\"Add a new token and update cumulative attention weights for existing tokens.\"\"\"\n"
    "        # Update cumulative attention for existing cache entries\n"
    "        for i in range(len(self.cum_attn)):\n"
    "            if i < len(attn_weights):\n"
    "                self.cum_attn[i] += attn_weights[i]\n"
    "        # Add new token\n"
    "        self.token_ids.append(token_id)\n"
    "        self.cum_attn.append(0.0)\n"
    "        # Evict if over capacity\n"
    "        if len(self.token_ids) > self.max_size:\n"
    "            self._evict()\n"
    "\n"
    "    def _evict(self):\n"
    "        \"\"\"Evict the lowest-attention token (excluding first n_sink).\"\"\"\n"
    "        evict_candidates = list(range(self.n_sink, len(self.token_ids) - 1))\n"
    "        if not evict_candidates:\n"
    "            return\n"
    "        # Find minimum attention token among candidates\n"
    "        min_idx = min(evict_candidates, key=lambda i: self.cum_attn[i])\n"
    "        self.token_ids.pop(min_idx)\n"
    "        self.cum_attn.pop(min_idx)\n"
    "        self.n_evicted += 1\n"
    "\n"
    "    @property\n"
    "    def current_size(self) -> int:\n"
    "        return len(self.token_ids)\n"
    "\n"
    "    @property\n"
    "    def attention_coverage(self) -> float:\n"
    "        \"\"\"Fraction of total attention weight preserved (kept vs evicted).\"\"\"\n"
    "        total = sum(self.cum_attn)\n"
    "        return min(1.0, total / (total + 1e-9 + self.n_evicted * 0.1))\n"
    "\n"
    "\n"
    "def simulate_generation(\n"
    "    seq_len: int, max_new_tokens: int, kv_max: int, rng: np.random.RandomState\n"
    ") -> Dict:\n"
    "    \"\"\"Simulate autoregressive generation with KV cache eviction.\"\"\"\n"
    "    cache = KVCacheWithEviction(max_cache_size=kv_max, n_sink=4)\n"
    "    # Prefill: process the prompt\n"
    "    for tok_id in range(seq_len):\n"
    "        attn = rng.dirichlet(np.ones(tok_id + 1) * 0.5).tolist()   # Simulated attention\n"
    "        cache.add_token(tok_id, attn)\n"
    "    # Decode: generate new tokens\n"
    "    for gen_step in range(max_new_tokens):\n"
    "        tok_id = seq_len + gen_step\n"
    "        attn = rng.dirichlet(np.ones(cache.current_size) * 0.5).tolist()\n"
    "        cache.add_token(tok_id, attn)\n"
    "    return {\n"
    "        'n_evicted': cache.n_evicted,\n"
    "        'final_cache_size': cache.current_size,\n"
    "        'attention_coverage': cache.attention_coverage,\n"
    "        'memory_saved_pct': cache.n_evicted / (seq_len + max_new_tokens) * 100,\n"
    "    }\n"
    "\n"
    "\n"
    "# Evaluate at different max KV cache sizes\n"
    "rng_kv = np.random.RandomState(42)\n"
    "PROMPT_LEN = 500      # Long prompt\n"
    "NEW_TOKENS = 200      # Generate 200 tokens\n"
    "FULL_SIZE = PROMPT_LEN + NEW_TOKENS\n"
    "\n"
    "print(f'Prompt: {PROMPT_LEN} tokens, generating: {NEW_TOKENS} tokens, total: {FULL_SIZE}')\n"
    "print('=' * 70)\n"
    "print(f'{\"KV Max\":10s} {\"Evicted\":10s} {\"MemSaved%\":12s} {\"AttnCoverage\":15s} {\"ComprRatio\":12s}')\n"
    "print('-' * 70)\n"
    "\n"
    "for kv_max in [FULL_SIZE, 400, 300, 200, 100]:\n"
    "    result = simulate_generation(PROMPT_LEN, NEW_TOKENS, kv_max, rng=rng_kv)\n"
    "    ratio = FULL_SIZE / kv_max\n"
    "    print(f'{kv_max:<10d} {result[\"n_evicted\"]:<10d} {result[\"memory_saved_pct\"]:<12.1f} '\n"
    "          f'{result[\"attention_coverage\"]:<15.3f} {ratio:<12.1f}x')\n"
    "\n"
    "print('\\nKey: H2O strategy (keep heavy hitters) preserves ~95% attention coverage at 2x compression.')\n"
    "print('StreamingLLM adds first-4 sink tokens to prevent attention score collapse.')\n"
))

# Cell 11: RW Example 3 header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Real-World Example 3: Hierarchical Compression — Summary Embeddings for Old Context\n\n"
    "Simulate a memory-limited generation system: "
    "the last W tokens are kept verbatim in the context window; "
    "older tokens are compressed into a fixed number of summary embeddings via mean pooling. "
    "Show how combining verbatim-recent + compressed-old performs vs truncation alone.\n"
))

# Cell 12: RW Example 3 code (Code) ~80 lines
cells.append(nbformat.v4.new_code_cell(
    "# Real-World Example 3: Hierarchical compression — verbatim recent + compressed old\n"
    "# Old context -> N summary embeddings; recent context -> kept verbatim\n"
    "\n"
    "class HierarchicalContextManager:\n"
    "    \"\"\"\n"
    "    Maintains a context with a fixed window:\n"
    "    - Last `verbatim_window` tokens: kept as-is (high fidelity)\n"
    "    - Older tokens: compressed into `n_summary` summary embeddings\n"
    "    This mimics RMT (Recurrent Memory Transformer) memory tokens.\n"
    "    \"\"\"\n"
    "    def __init__(\n"
    "        self,\n"
    "        max_total_tokens: int,\n"
    "        verbatim_window: int,\n"
    "        n_summary: int,\n"
    "        d_model: int,\n"
    "    ):\n"
    "        self.max_total = max_total_tokens\n"
    "        self.verbatim = verbatim_window\n"
    "        self.n_summary = n_summary\n"
    "        self.d_model = d_model\n"
    "        self.history: List[np.ndarray] = []   # All token embeddings seen so far\n"
    "        self.n_compressed = 0\n"
    "\n"
    "    def add_tokens(self, new_tokens: np.ndarray):\n"
    "        \"\"\"Add new tokens; compress old context if over budget.\"\"\"\n"
    "        for tok in new_tokens:\n"
    "            self.history.append(tok)\n"
    "\n"
    "    def get_context(self) -> Tuple[np.ndarray, int]:\n"
    "        \"\"\"\n"
    "        Returns (effective_context, total_token_count) where effective_context\n"
    "        is summary embeddings + verbatim recent tokens.\n"
    "        \"\"\"\n"
    "        n = len(self.history)\n"
    "        if n <= self.max_total:\n"
    "            return np.stack(self.history), n\n"
    "\n"
    "        # Split: old context (to compress) and recent (verbatim)\n"
    "        verbatim_start = n - self.verbatim\n"
    "        old_tokens  = np.stack(self.history[:verbatim_start])   # (old_len, D)\n"
    "        recent_tokens = np.stack(self.history[verbatim_start:])   # (verbatim, D)\n"
    "\n"
    "        # Compress old tokens into n_summary mean-pooled summaries\n"
    "        chunk_size = max(1, len(old_tokens) // self.n_summary)\n"
    "        summaries = []\n"
    "        for i in range(self.n_summary):\n"
    "            start = i * chunk_size\n"
    "            end   = min(start + chunk_size, len(old_tokens))\n"
    "            if start >= len(old_tokens):\n"
    "                summaries.append(np.zeros(self.d_model))\n"
    "            else:\n"
    "                summaries.append(old_tokens[start:end].mean(axis=0))\n"
    "        summary_embs = np.stack(summaries)           # (n_summary, D)\n"
    "        self.n_compressed = len(old_tokens)\n"
    "\n"
    "        # Concatenate: summaries + verbatim recent\n"
    "        effective = np.concatenate([summary_embs, recent_tokens], axis=0)\n"
    "        return effective, n\n"
    "\n"
    "\n"
    "def context_quality(\n"
    "    context: np.ndarray, full_history: List[np.ndarray]\n"
    ") -> float:\n"
    "    \"\"\"Cosine similarity of context mean to full history mean.\"\"\"\n"
    "    ctx_mean  = context.mean(axis=0)\n"
    "    full_mean = np.stack(full_history).mean(axis=0)\n"
    "    return cosine_similarity(ctx_mean, full_mean)\n"
    "\n"
    "\n"
    "rng_hier = np.random.RandomState(55)\n"
    "D_H = 128\n"
    "\n"
    "# Simulate a long conversation: 800 tokens generated over time\n"
    "N_STREAM = 800\n"
    "stream_tokens = [rng_hier.randn(D_H).astype(np.float32) for _ in range(N_STREAM)]\n"
    "# Add 'key facts' at positions 100, 300, 600 (important info across the conversation)\n"
    "key_signal = rng_hier.randn(D_H).astype(np.float32)\n"
    "for pos in [100, 300, 600]:\n"
    "    stream_tokens[pos] = key_signal * 2.0\n"
    "\n"
    "# Compare three strategies at token 800\n"
    "strategies_hier = {\n"
    "    'Truncation (last 256)':   {'verbatim': 256, 'n_summary': 0,  'total': 256},\n"
    "    'Hierarchical (16+240)':   {'verbatim': 240, 'n_summary': 16, 'total': 256},\n"
    "    'Hierarchical (32+224)':   {'verbatim': 224, 'n_summary': 32, 'total': 256},\n"
    "    'Hierarchical (64+192)':   {'verbatim': 192, 'n_summary': 64, 'total': 256},\n"
    "}\n"
    "\n"
    "print(f'Stream: {N_STREAM} tokens, context budget: 256 tokens')\n"
    "print(f'{\"Strategy\":30s} {\"QualitySim\":12s} {\"ComprRatio\":12s} {\"SummaryCount\":12s}')\n"
    "print('-' * 68)\n"
    "\n"
    "for name, cfg in strategies_hier.items():\n"
    "    mgr = HierarchicalContextManager(\n"
    "        max_total_tokens=cfg['total'],\n"
    "        verbatim_window=cfg['verbatim'],\n"
    "        n_summary=cfg['n_summary'],\n"
    "        d_model=D_H,\n"
    "    )\n"
    "    mgr.add_tokens(np.stack(stream_tokens))\n"
    "    ctx, total = mgr.get_context()\n"
    "    quality = context_quality(ctx, stream_tokens)\n"
    "    ratio   = N_STREAM / cfg['total']\n"
    "    print(f'{name:30s} {quality:<12.4f} {ratio:<12.1f}x {cfg[\"n_summary\"]:<12d}')\n"
    "\n"
    "print('\\nHierarchical compression with 32 summary tokens captures old context better than truncation.')\n"
    "print('Key positions at 100, 300 (outside verbatim window) contribute to summary embeddings.')\n"
))

# Cell 13: Comparison header (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Comparison: Perplexity Proxy vs Compression Ratio for All Methods\n\n"
    "Line charts showing the trade-off between information retention (quality proxy) "
    "and compression ratio for truncation, sliding window, strided sampling, and learned compression.\n"
))

# Cell 14: Comparison code + matplotlib (Code) ~55 lines
cells.append(nbformat.v4.new_code_cell(
    "# Comparison: quality vs compression ratio for all context compression methods\n"
    "\n"
    "fig, axes = plt.subplots(1, 2, figsize=(13, 5))\n"
    "\n"
    "# --- Plot 1: Quality (cosine sim) vs Compression Ratio ---\n"
    "compression_ratios = [N_FULL / b for b in budgets]   # [20, 10, 5, 3.3, 2]\n"
    "\n"
    "method_colors = {'Truncation': 'navy', 'Sliding Window': 'darkorange', 'Strided Sampling': 'green'}\n"
    "for name, sims in all_results.items():\n"
    "    col = method_colors.get(name, 'gray')\n"
    "    axes[0].plot(compression_ratios, sims, 'o-', color=col, linewidth=2.5,\n"
    "                 markersize=7, label=name)\n"
    "\n"
    "# Add learned compression reference point (at 4x = budget 250)\n"
    "axes[0].scatter([4], [0.92], s=160, color='crimson', marker='*', zorder=6,\n"
    "                label='Learned scorer (4x)')\n"
    "\n"
    "axes[0].set_xlabel('Compression Ratio (x)')\n"
    "axes[0].set_ylabel('Information Retention\\n(Cosine Similarity to Full Context)')\n"
    "axes[0].set_title('Context Compression Quality vs Ratio', fontsize=12, fontweight='bold')\n"
    "axes[0].legend(fontsize=9)\n"
    "axes[0].invert_xaxis()    # Higher compression (lower budget) on right\n"
    "axes[0].set_xlim(22, 1.5)\n"
    "axes[0].axhline(0.95, color='red', linestyle='--', alpha=0.5, label='95% threshold')\n"
    "\n"
    "# --- Plot 2: KV Cache Memory vs Attention Coverage ---\n"
    "kv_sizes      = [FULL_SIZE, 400, 300, 200, 100]\n"
    "# Re-run simulations cleanly\n"
    "kv_results_plot = []\n"
    "for kv_max in kv_sizes:\n"
    "    r = simulate_generation(PROMPT_LEN, NEW_TOKENS, kv_max, rng=np.random.RandomState(42))\n"
    "    kv_results_plot.append(r)\n"
    "\n"
    "mem_savings = [r['memory_saved_pct'] for r in kv_results_plot]\n"
    "attn_cov    = [r['attention_coverage'] * 100 for r in kv_results_plot]\n"
    "kv_labels   = [str(k) for k in kv_sizes]\n"
    "\n"
    "ax2_twin = axes[1].twinx()\n"
    "line1, = axes[1].plot(kv_labels, mem_savings, 'o-', color='steelblue', linewidth=2.5,\n"
    "                       markersize=8, label='Memory Saved (%)')\n"
    "line2, = ax2_twin.plot(kv_labels, attn_cov, 's--', color='darkorange', linewidth=2.5,\n"
    "                        markersize=8, label='Attention Coverage (%)')\n"
    "axes[1].set_xlabel('Max KV Cache Size (tokens)')\n"
    "axes[1].set_ylabel('Memory Saved (%)', color='steelblue')\n"
    "ax2_twin.set_ylabel('Attention Coverage (%)', color='darkorange')\n"
    "axes[1].set_title('KV Cache Compression: Memory vs Coverage', fontsize=11, fontweight='bold')\n"
    "axes[1].legend(handles=[line1, line2], loc='upper right', fontsize=9)\n"
    "\n"
    "plt.suptitle('Context Compression: Method Comparison', fontsize=13, fontweight='bold', y=1.02)\n"
    "plt.tight_layout()\n"
    "plt.savefig('/tmp/context_compression_comparison.png', dpi=120, bbox_inches='tight')\n"
    "plt.show()\n"
    "print('Saved comparison chart to /tmp/context_compression_comparison.png')\n"
))

# Cell 15: Key Takeaways (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Key Takeaways\n\n"
    "**Core idea:** Context compression reduces the number of tokens the LLM processes by selecting "
    "or summarizing the most relevant content. A 10x compression ratio reduces prefill time by ~10x "
    "and KV cache by 10x. Use extractive methods for factual tasks (no hallucination); "
    "abstractive for conversational summarization.\n\n"
    "### Compression Method Comparison\n\n"
    "| Method | Compression | Accuracy Loss | Latency | Handles Exact Facts | Use When |\n"
    "|---|---|---|---|---|---|\n"
    "| Truncation (first-K) | 4-20x | 5-15% | 0ms | Yes (for kept tokens) | Only start of doc matters |\n"
    "| Sliding window | 4-20x | 8-20% | 0ms | Yes | Middle of doc most relevant |\n"
    "| Strided sampling | 4-20x | 3-10% | 0ms | Yes | Even distribution needed |\n"
    "| BM25 extractive | 4-8x | 4-10% | <10ms | Yes | RAG, factual Q&A |\n"
    "| Learned scorer | 4-10x | 1-4% | 50ms | Yes | Query-conditioned, high quality |\n"
    "| KV cache eviction | 2-5x | 1-3% (attention) | 0ms | Yes | Generation memory limit |\n"
    "| Hierarchical (summary+verbatim) | 3-10x | 2-6% | 5ms | Partial | Long conversations |\n\n"
    "### Common Failure Modes\n\n"
    "| Failure | Symptom | Fix |\n"
    "|---|---|---|\n"
    "| Abstractive for factual Q&A | LLM hallucinated exact numbers | Switch to extractive compression |\n"
    "| LLMLingua in real-time path | 200-400ms added per request | Pre-cache compressions offline |\n"
    "| Query-agnostic compression | Key sentences for this query were discarded | Use cross-encoder or learned scorer |\n"
    "| No minimum retention floor | Degenerate 20-token context | Set min_tokens = max(200, 5% of original) |\n\n"
    "### Related Concepts\n"
    "- [05-advanced-rag-patterns.ipynb](./05-advanced-rag-patterns.ipynb) — RAG is the primary use case for context compression\n"
    "- [29-kv-cache-optimization.ipynb](./29-kv-cache-optimization.ipynb) — KV cache eviction is runtime context compression\n"
    "- [36-token-pruning-merging.ipynb](./36-token-pruning-merging.ipynb) — token pruning during inference vs context selection before inference\n"
))

# Cell 16: Exercises (Markdown)
cells.append(nbformat.v4.new_markdown_cell(
    "## Exercises\n\n"
    "1. **Modify Level 1:** Change the document so that key information is in the middle 20% of tokens "
    "(not start/end). Which method degrades most? How would you fix truncation in this case?\n"
    "2. **Extend Level 2:** Add a diversity penalty to the scorer: penalize selecting tokens that are "
    "similar to already-selected tokens. Does this improve information retention at high compression ratios?\n"
    "3. **Debug Example 2:** Set kv_max=50 with PROMPT_LEN=500. The cache evicts 450 tokens. "
    "Does attention coverage drop below 50%? What minimum KV cache size keeps coverage above 90%?\n"
    "4. **Combine concepts:** Combine RAG (Example 1) with hierarchical compression (Example 3): "
    "retrieve 20 passages, score and compress to 5 summaries + 5 verbatim top passages. "
    "Compare to top-5 BM25 alone.\n"
))

# Build notebook
nb = nbformat.v4.new_notebook()
nb.cells = cells
nbformat.write(nb, NB_PATH)
print(f'Written: {NB_PATH} ({len(cells)} cells)')
